### ISSUE TITLE
Package is closed for extension

### ISSUE THREAD

**Issue by etki** [googlemaps/google-maps-services-java#113]
Hi, maintainers!

I just wanted to let you know that package (as it seems for me) is a little bit to cautious about hiding everything it can. I do understand why you may not want end user to mess with internals, but you also prohibit end user from extending package and implementing missing features. For example, i want to perform `nearbysearch` from Places API, but i can't implement my own request, because base request classes are invisible for outside world, so i need to build API from scratch, while i could simply integrate my own type of request into existing system.

I know that i can do a pull request, then wait for release or even bring up my own maven repo, but, unfortunately, i don't have that much of time.

**Comment by domesticmouse** [comment]
For implementation reasons, you will be better off doing [text search](https://developers.google.com/places/web-service/search?hl=en#TextSearchRequests) with a `location` parameter than a nearby search.
