### ISSUE TITLE
Supporting ClientID for Roads API

### ISSUE THREAD

**Issue by tq-jappy** [googlemaps/google-maps-services-java#116]
I want to use client ID and secret to authenticate for Roads API,
but in ``RoadsAPI.java``,  it set supportsClientId as false:

https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/RoadsApi.java#L40-L48

Why Roads API not supports ClientID?
And is it possible to use ClientID for Roads API?

Regards,

**Comment by markmcd** [comment]
The web service API does not support client IDs, so we can't do much in the client library. If you have a client ID (and therefore a Maps for Work license), then an API key generated under that account will grant the same permissions as a client ID.

More info here: https://developers.google.com/maps/documentation/roads/get-api-key
