### ISSUE TITLE
Unknown type for enum postal_town ...

### ISSUE THREAD

**Issue by oakstair** [googlemaps/google-maps-services-java#117]
I get this when calling GeocodingApi.reverseGeocode ...

nov 21, 2015 12:39:01 EM com.google.maps.internal.SafeEnumAdapter read
VARNING: Unknown type for enum com.google.maps.model.AddressType: 'postal_town'

.. and I am using the latest and greatest version 0.1.9

**Comment by domesticmouse** [comment]
Can you give me the sample query that is causing this condition? I'd like to add it to the test suite so I can fix this issue and make sure it stays fixed. Thanks!

**Comment by jayenashar** [comment]
I got some of these with 0.1.14.  sorry i don't have a sample query because i did a large batch and the request was printed at the time of starting the batch not when it did the read.

```
Jun 03, 2016 10:55:09 AM com.google.maps.internal.SafeEnumAdapter read
WARNING: Unknown type for enum com.google.maps.model.AddressType: 'store'
Jun 03, 2016 10:55:09 AM com.google.maps.internal.SafeEnumAdapter read
WARNING: Unknown type for enum com.google.maps.model.AddressType: 'food'
Jun 03, 2016 10:55:09 AM com.google.maps.internal.SafeEnumAdapter read
WARNING: Unknown type for enum com.google.maps.model.AddressType: 'general_contractor'
```

**Comment by lsoares** [comment]
same here:
`c.google.maps.internal.SafeEnumAdapter   : Unknown type for enum com.google.maps.model.AddressType: 'postal_code_prefix'`

**Comment by mhubbard** [comment]
Have the same issue a Isoares
> com.google.maps.internal.SafeEnumAdapter read WARNING: Unknown type for enum com.google.maps.model.AddressType: 'postal_code_prefix'

Caused by:

`GeocodingApi.reverseGeocode(context, new LatLng(43.7601992, -79.2334543)).await()`

on version 0.1.15

**Comment by domesticmouse** [comment]
This was fixed at some point, but not closed out. Sorry for the delay!
