### ISSUE TITLE
Support for places autocomplete service (along with existing queryautocomplete)

### ISSUE THREAD

**Issue by kromit** [googlemaps/google-maps-services-java#119]
Places autocomplete supports more parameters like place `types` and `components` as described on
https://developers.google.com/places/web-service/autocomplete

**Comment by dopse** [comment]
+1

**Comment by abdavid** [comment]
+1

**Comment by markmcd** [comment]
Keep the :+1:'s coming :)

I'm curious about how you would use this feature - if we build it, would there be any particular adapters or types from frameworks you use that would be useful for us to build?

**Comment by domesticmouse** [comment]
I believe this is now fixed with our v0.1.11 release. Please check it out and let me know if I missed anything!
