### ISSUE TITLE
Setting duration in traffic to false in DistanceMatrixApi request.

### ISSUE THREAD

**Issue by anirban-metal** [googlemaps/google-maps-services-java#121]
For now, I think it's only possible to get duration in traffic. Would be very convenient if that could be turned off.

**Comment by domesticmouse** [comment]
Is this something we aren't exposing that the underlying [Distance Matrix API](https://developers.google.com/maps/documentation/distance-matrix/) does actually do, or something that you wish Distance Matrix API would allow? If it is the former, I'll be happy to fix, if the later then this request belongs on the [Google Maps bug tracker](https://code.google.com/p/gmaps-api-issues/) as a feature request for the Distance Matrix API.

**Comment by anirban-metal** [comment]
Thank you for your response. I apologise for not having phrased the feature request correctly. I shall do the same correctly now.
In google distance matrix api, if one sets the arrival time/departure time of the vehicle (car/bus/transit etc), the json response contains the fields "duration" and "duration_in_traffic". Presently, if we set the vehicle arrival/departure time in the java api, we can only get the "duration" from DistanceMatrixElement. I think another instance variable of "durationInTraffic" should be present in the DistanceMatrixElement class, which should have some illegal value in case if the arrival/departure time is not set for the vehicle, and the value returned by the google distance matrix API if the arrival/departure time is set. There happens to be a "durationInTraffic" instance variable in the DirectionsLeg class of the API.

**Comment by ctmckenna** [comment]
I'm also wondering why there's no durationInTraffic in DistanceMatrixElement.  Meanwhile it exists in the directions api response (DirectionsLeg)

**Comment by domesticmouse** [comment]
I believe that @ctmckenna fixed this issue with https://github.com/googlemaps/google-maps-services-java/pull/139

Please re-open if this isn't the case.
