### ISSUE TITLE
Server Service API key is not recognized by Google Maps Geocoding API

### ISSUE THREAD

**Issue by hyuan** [googlemaps/google-maps-services-java#122]
The request URL generated by this lib put the API key as the first parameter in the URL whereas on the Google Maps service side it requires to put the API key at the end of the URL or a com.google.maps.errors.RequestDeniedException will be thrown.

**Comment by domesticmouse** [comment]
Which API call is requiring the API key param be last in the URL? If you supply example URLs we can chase down what the issue is and get it fixed. Thanks!

**Comment by hyuan** [comment]
It happens when I test the Geocoding API from Heroku. The lib generates the URL like this:   `https://maps.googleapis.com/maps/api/geocode/json?key=myApiKey&address=550+King+St+N,+Waterloo,+ON+Canada`, and this is how the response like this:

    {
       "error_message" : "This site or IP is not authorized to use this API key.",
       "results" : [],
       "status" : "REQUEST_DENIED"
    }

However after I put the `key` param after the `address` like this: `https://maps.googleapis.com/maps/api/geocode/json?address=550+King+St+N,+Waterloo,+ON+Canada&key=myApiKey`, then it works fine.

Normally the param's order in URL shouldn't matter. So it's more like an issue on Google's side. But that's how it is working for now. And seems it has been working like this for a while. The client ID and signature could have the same issue. I haven't tried though.

Please be noticed that the problem is gone when my app is run locally (Well, it works even without API key). Maybe it's because of the shared IP at Heroku.

Thanks!

**Comment by markmcd** [comment]
The Geocoding API is not sensitive to URL param ordering. I suspect that Heroku, being a shared hosting platform, is using a number of IP addresses and you may not have granted them all as allowed IPs. I've never used Heroku though, so it's a guess.

To test, you could remove the IP restriction from the key completely and retry. If it starts working, then the IP list is the problem.

**Comment by domesticmouse** [comment]
Given the lack of follow up I'm assuming this issue is closed. Please comment to re-open.

**Comment by hyuan** [comment]
Sorry about the late reply. I don't think this issue is resolved. Removing the IP restriction doesn't fix the issue. You can find some discuss about this issue at [here](http://stackoverflow.com/questions/21933247/this-ip-site-or-mobile-application-is-not-authorized-to-use-this-api-key).

**Comment by domesticmouse** [comment]
Anthony, the URLs mentioned above and in the linked StackOverflow question work for me using my keys. Can you email me directly at brettmorgan@google.com with your API key so I can chase up what is going on?

**Comment by hyuan** [comment]
I sent my API key to you. Please check your email.

The Google Map API works properly on my local machine with or without the
API key. So you need to verify it on a shared server like Heroku.

According to the linked StackOverflow question, seems the key just cannot
be the first parameter. I didn't verify this though.

I guess it could be caused by a simple regex issue. e.g.  &key=([^&]+)
won't find the key from the URL like
https://maps.googleapis.com/maps/api/geocode/json?key=myApiKey&address=550+King+St+N,+Waterloo,+ON+Canada
but it will work with the URL like
https://maps.googleapis.com/maps/api/geocode/json?address=550+King+St+N,+Waterloo,+ON+Canada&key=myApiKey

**Comment by domesticmouse** [comment]
The fact that it works fine from your local machine (and my desktop) means that the issue here isn't with the API, or the client library. Please work with Heroku to debug and fix their stack. Or failing that, move to a cloud infrastructure that doesn't break your ability to make outbound HTTPS calls.

**Comment by hyuan** [comment]
First of all, thanks for building this great lib and spending time on
answering my questions! It helps me a lot.

Based on my understanding, the root cause is on the Google Map service
side. Neither Heroku nor the client library causes the issue. I don't think
Heroku can do anything with this. Same as other shared service providers.
I think why it works locally is because the Map service falls back to
different ways to control the quota, e.g. using IP address. You can check
the local api access won't affect the stats of the key - which means the
key is not actually recognized.

I adjusted the parameter order in my app, and it works fine on Heroku now.
But it is not a elegant solution. It would be better if you can help to fix
the issue from the library side. If you don't think it's a good idea to fix
this in your lib, I can understand.

**Comment by Artuscha** [comment]
Hey guys,

i have the same issue and couln't find a way to get the api key to be at the end of the request-url. I don't want to parse the json response myself so i'd like to know if and when you could come up with a solution or if there is a workaround.

Thanks

**Comment by domesticmouse** [comment]
@Artuscha Which platform are you using? The Google Maps Web Service APIs don't require the arguments to be in a specific order.

**Comment by Artuscha** [comment]
Hey, thanks for the fast reply. My service runs on linux. I've tried to access the API by a curl command and got a 400 - Bad Request when i copied the link that this library generates. However when i tried to put the key at the end of the request i got a 200 and a valid response.

**Comment by domesticmouse** [comment]
Can you mail me the generated request URL that is causing the 400? My email is brettmorgan@google.com. Thanks!

**Comment by Artuscha** [comment]
I have to admit that i've made a mistake in my configuration and only found it by debugging my code on the remote server. The curl command worked as well when i quoted it so you were right. Sorry for any inconvenience. Your code works!!!
