### ISSUE TITLE
Retries indefinitely when API limits reached

### ISSUE THREAD

**Issue by pablote** [googlemaps/google-maps-services-java#123]
I've reached my daily limit of 2500 reqs for the directions api, and the client seems to get stuck retrying the call over and over again. I would have expected an exception thrown since this is not recoverable,  am I wrong in assuming this?

Relevant parts of my code:
```
this.geoApiContext = new GeoApiContext();
this.geoApiContext.setApiKey(googleApiKey);
...
DirectionsRoute[] routes = DirectionsApi
                            .getDirections(geoApiContext, origin, destination)
                            .units(Unit.METRIC)
                            .await();
```

This prints to the console:
```
Jan 19, 2016 10:30:35 PM com.google.maps.GeoApiContext getWithPath
INFO: Request: https://maps.googleapis.com/maps/api/directions/json?key=somekey&origin=-34.6202964%2C-58.5139567&destination=-34.5757411%2C-58.463964&units=metric
Jan 19, 2016 10:31:02 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #1
Jan 19, 2016 10:31:04 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #2
Jan 19, 2016 10:31:05 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #3
Jan 19, 2016 10:31:07 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #4
Jan 19, 2016 10:31:11 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #5
Jan 19, 2016 10:31:13 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #6
Jan 19, 2016 10:31:18 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #7
Jan 19, 2016 10:31:26 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #8
Jan 19, 2016 10:31:34 PM com.google.maps.internal.OkHttpPendingResult retry
INFO: Retrying request. Retry #9
Disconnected from the target VM, address: '127.0.0.1:50148', transport: 'socket'
```

thanks

**Comment by pablote** [comment]
Ok, I was just watching the source code and saw that the retries were expected for this response type, and that there's a way to limit the time it runs. I had seen the retryTimeout param on the context object but thought that it was per retry call, not an accumulated value, it's a little misleading.

**Comment by markmcd** [comment]
I still think this is a valid bug report - we have an exception (OverDailyLimitException) that should be thrown when you hit the daily limit.

**Comment by domesticmouse** [comment]
@markmcd I don't believe we can currently tell the difference between failures due to rate limit and being out of daily quota.

**Comment by pablote** [comment]
Ah so the reason this is a retryable error it's because you get the same error back from Google when you send more queries per second than allowed, makes sense.

**Comment by stratosgear** [comment]
Sorry, still not get it.  If I'm over my quota (eg 2500 req/day) I want to fail fast, with no retries. I thought the OverDailyLimitException was triggered if I exceeded my quota.

How can I prevent these retry attempts?

**Comment by MSimonart** [comment]
To prevent retry attempts, my GeoApiContext looks like this:

`
GeoApiContext distanceCalculator = new GeoApiContext.Builder().apiKey(DISTANCE_CALULATOR_API)
					.retryTimeout(0, TimeUnit.MICROSECONDS).build();`
