### ISSUE TITLE
Too many thread alive in jvm

### ISSUE THREAD

**Issue by alldone** [googlemaps/google-maps-services-java#126]
Hi to all, and thank's for this work .......

i've a problem, 

using the quartz scheduler, my app invoke 2000 reverse geocoding service 
( obviusly  under free limit quota ) 
with sychronous req.await() method.....

after these 2000 call ... in jvm i've 2000 thead alive with name Thread-1 .... Thread-2000 that make too slow system ( server centOs 6 and tomcat 7.... jdk 1.7)

please, a suggestion??

thank's in advance.

best regards
Aldo

**Comment by domesticmouse** [comment]
Hey Aldo,

Can you first confirm for me that you only have one [GeoApiContext](http://googlemaps.github.io/google-maps-services-java/v0.1.10/javadoc/com/google/maps/GeoApiContext.html) object that you are using across all of your geocoding requests? 

If the above is good, then the next step is debugging a thread dump of your running app...

**Comment by alldone** [comment]
Hi,

mmmmm.... no, i can't confirm.......

there are  many instances of GeoApiContext .... ( 2 thousand at day :)  )  


from documentation i haven't read or understood that is necessary only one instance,... the problem is here? correct?

using a static instance of GeoApiContext,   i will solve the problem?


thank's,
Aldo

_here_the_code_



		GeoApiContext Context = new GeoApiContext().setApiKey(ApiKey);
		String output = "";
		String message = "";
		String updateCounter = "0";
		String countOfResults = "";
		try {

			GeocodingResult[] results = null;
			try {
				results = GeocodingApi.newRequest(Context).language("it").address(address).await();
..................................................................................................

**Comment by domesticmouse** [comment]
Ok, please create a single `GeoApiContext` and use it over the whole life of the program. Do not re-construct it for each API call.
