### ISSUE TITLE
Override base URL

### ISSUE THREAD

**Issue by aelamrani** [googlemaps/google-maps-services-java#132]
I'd like to override my base URL, in order to call a VIP instead of directly the GMap URL...

I can see a private attribute 'baseUrlOverride' but it's on visibility package, and for test purpose. It will be interesting to allow users to configure this URL.

**Comment by domesticmouse** [comment]
Can you please explain what you mean by 'call a VIP' ?

**Comment by aelamrani** [comment]
Thanks for your quick answer.

I mean a Virtual IP. I can figure it out with introspection, but it's a bit weird :)

**Comment by markmcd** [comment]
We made the decision to explicitly not implement this in the library as a security feature. Leaving it as un-modifiable means we can enforce a base level of security (i.e. we use HTTPS, not HTTP and ensure that certificate validation is enabled). Overriding this could open you up to potential security issues, such as traffic snooping or MITM attacks.

That's not to say that users can't set it up safely but at the moment at least, we feel strongly enough about this that we suggest forking this project to make this modification. If we were ever to implement this, we would likely require that the overridden URL still use HTTPS.

You may be able to get what you need by using [`GeoApiContext.setProxy(..)`](http://googlemaps.github.io/google-maps-services-java/v0.1.10/javadoc/com/google/maps/GeoApiContext.html#setProxy-java.net.Proxy-)
