### ISSUE TITLE
Not Able to Query multiple places types.

### ISSUE THREAD

**Issue by xavierxc14** [googlemaps/google-maps-services-java#134]
Making a NearbySearchRequest.type replace the last type selected. It must be appended using the pipe, for example, church|food.

```
NearbySearchRequest nearbySearchRequest = new NearbySearchRequest(geoApiContext);
nearbySearchRequest.type(PlaceType.CHURCH);
nearbySearchRequest.type(PlaceType.LODGING);
```

**Comment by domesticmouse** [comment]
Per [Changes and quality improvements in Google Places API Search](http://googlegeodevelopers.blogspot.com/2016/02/changes-and-quality-improvements-in_16.html) we are deprecating the types restriction in favor of the singular type parameter. As such, I've only implemented the singular type parameter.
