### ISSUE TITLE
Can not restrict general place type in place autocomplete

### ISSUE THREAD

**Issue by Grcko** [googlemaps/google-maps-services-java#138]
I am not sure if I haven't missed something but I am afraid I can not restrict place type like _geocode_, _address_, _establishment_, etc as described in Table 3 [here](https://developers.google.com/places/supported_types). PlaceType enum contains only values from Table 1 and I can't find other way to do this.

Please let me know the right way to do this if I am wrong. Thank you.

**Comment by apjanke** [comment]
Hi @Grcko,

Use objects of type `com.google.maps.model.PlaceAutocompleteType` as arguments to `types(PlaceAutocompleteType types)` on your PlaceAutocompleteRequest. It supports `geocode`, `address`, `establishment`, and so on.

This was [introduced on Mar 9, 2016](https://github.com/googlemaps/google-maps-services-java/commit/cc5f53402b4a5ded9e5f4248253a6e5bd4ebdf9b), so you wouldn't have seen it when you originally posted this issue.

@domesticmouse I think this can be marked as Closed.

**Comment by domesticmouse** [comment]
Thanks @apjanke!

**Comment by gloompi** [comment]
@apjanke Thanks a lot!!!!
