### ISSUE TITLE
Upgrade to okhttp3

### ISSUE THREAD

**Issue by broady** [googlemaps/google-maps-services-java#148]
https://square.github.io/okhttp/3.x/okhttp/okhttp3/package-summary.html

**Comment by domesticmouse** [comment]
Reading through the [upgrade notes](https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-300-rc1) looks like there is some interesting changes. I suspect we are architected correctly for the change, but not something I'm going to do before I/O =)

**Comment by kyso84** [comment]
Any news about OkHttp3 support ?

**Comment by domesticmouse** [comment]
We gladly accept pull requests =)

**Comment by shmuelr** [comment]
Working on this in my fork here https://github.com/shmuelr/google-maps-services-java/commits/master

One issue, OkHttp moved some methods from the Client to the Builder class. Most noticeably, 
client.setConnectTimeout()
client.setReadTimeout()
client.setWriteTimeout()
client.setProxy()

These methods are now on the Builder. https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html

This project only uses these methods in the tests, but I'm hesitant to remove them as that will affect the public api of google-maps-services-java.

Any suggestions?

**Comment by domesticmouse** [comment]
Here was my initial stab at upgrading to OkHttp3:
https://github.com/googlemaps/google-maps-services-java/compare/master...domesticmouse:master

I hit a couple of issues, and I can't remember how I was going to move this forward. Have a looksee and see if it helps. 

On the API front, the version of this API is still 0.x, so I'm happy enough to introduce required API breakage. I'd prefer for something to break at compile time rather than run time, for instance.

**Comment by domesticmouse** [comment]
Hey @shmuelr, I've just ditched my first attempt (joys of leaving changes off head), I'd like to investigate your code, but you haven't yet signed a CLA. Do you want to put together a PR with your changes, after you have signed said CLA? Please see https://cla.developers.google.com/ for more detail. Thanks!

**Comment by shmuelr** [comment]
Sure thing, just signed CLA and I'll make a pr when I get a chance.

**Comment by jagan120** [comment]
@shmuelr Did you make any progress on doing this? Please let me know, I can take a dig at this when I get sometime.

**Comment by shmuelr** [comment]
@jagan120 Haven't looked at it in a while.
It was pretty straight forward to do. The only issue was that okhttp3 has api changes and some of the public methods in this library would have to be dropped.

**Comment by domesticmouse** [comment]
Unless someone has a dramatic reason why I shouldn't I'm planning on landing https://github.com/googlemaps/google-maps-services-java/pull/293 tomorrow, and then cutting a version 0.2.0 release with OkHttp3. I'd like to get this settled in, and then start moving towards a 1.0RC train.

Thoughts?

**Comment by domesticmouse** [comment]
I'm going to go ahead and mark this as closed, now that version 0.2.0 is in circulation with OkHttp3 support. Thanks!
