### ISSUE TITLE
java.lang.RuntimeException: Unknown address component type 'postal_code_suffix'

### ISSUE THREAD

**Issue by bpgriner** [googlemaps/google-maps-services-java#150]
`GeocodingApi.reverseGeocode(context, new LatLng(32.861283,-79.788139)).await();`

This code (above) throws this exception:
`java.lang.RuntimeException: Unknown address component type 'postal_code_suffix'`

Perhaps I'm doing something incorrect, but other valid latitude and longitude values are working fine for me.  This just happens to be a lat/lng for a test location I'm using, and I ran into this error.

Does the address associated with this lat/lng have a postal code suffix that the `GeocodingApi.reverseGeocode` method can't handle?

These coordinates were grabbed directly from Google Maps by clicking on a spot inside this address:  `3000 Proprietors Pl, Mt. Pleasant, SC, 29466`

Thanks,
Ben

P.S.  I'm using Java 1.8.0_77 as well as:

```
<dependency>
    <groupId>com.google.maps</groupId>
    <artifactId>google-maps-services</artifactId>
    <version>0.1.1</version>
</dependency>
```

**Comment by bpgriner** [comment]
Upgrading from 0.1.1 to 0.1.9 has solved the issue.

**Comment by domesticmouse** [comment]
Seriously consider upgrading to 0.1.12, there are more bug fixes to be had. Thanks!

**Comment by bpgriner** [comment]
Thanks, will do!

**Comment by navidakhan** [comment]
wow thanks helped save my day worked for me
