### ISSUE TITLE
sending email

### ISSUE THREAD

**Issue by jayenashar** [googlemaps/google-maps-services-java#155]
copied from https://github.com/googlemaps/google-maps-services-java/commit/e59c5d3e8116aa2393c7ed4cc0d53ad3669066f2#commitcomment-17567820

>  this [app engine] dependency seems to implement the javax.mail package and is interfering with my ability to use `javax.mail:mail:1.4.7`. it's throwing the error below and i can't figure out how to send email.
> `The API package 'mail' or call 'Send()' was not found.`

will make a small test case when i have a chance, but i'm using Transport.send() to send emails.

i managed to work around it by excluding the app engine dependency.  (i'm using maven, not sure if gradle has an equivalent.)

**Comment by crazed-developer** [comment]
Okay, I just diagnosed the same problem.

My dependency on the maps library was updated to the newest version.. Which also pulled in the appengine api.. Which is in conflict with the java.mail library..

My fix: downgraded maps to version 0.1.11, which does not full in appengine..

-Steffen

**Comment by domesticmouse** [comment]
Version 0.1.15 is in the process of propagating through the release pipeline, and includes a fix for the email issue. Once 0.1.15 is visible (~hours) please test and let me know if we can close this bug. Thanks!

**Comment by jayenashar** [comment]
works for me!  do you still want a test case if i get time?

**Comment by domesticmouse** [comment]
Sure, sounds good to me!
