### ISSUE TITLE
OverDailyLimitException not being thrown. How to know if I am over the daily limit ?

### ISSUE THREAD

**Issue by Ismamai** [googlemaps/google-maps-services-java#156]
When I am over the daily limit, I do not get an OverDailyLimitException and requests just keep being retried forever.

I am using a free api key that has a 2.500 daily limit on geocodes. While geocoding I want to know if I am over the daily limit, as it does not make sense to keep sending new requests until the day limit gets cleared.

**Comment by Ismamai** [comment]
I am trying with a development key, and when I get close to the limit, it just stops responding. The library keeps retrying instead of just throwing the exception. Is this the expected behaviour ? 
If I have reached my daily limit, I do not see why retrying is being used.

**Comment by Ismamai** [comment]
I just created a pull request with a small change to detect when the error is related to OverDailyLimitException

**Comment by domesticmouse** [comment]
Is this covered by https://github.com/googlemaps/google-maps-services-java/pull/188 ?

**Comment by Ismamai** [comment]
yes, it is :)

**Comment by domesticmouse** [comment]
Thanks @Ismamai =)
