### ISSUE TITLE
Including v0.1.14 as a dependency forces emails to be sent using GMTransport

### ISSUE THREAD

**Issue by tazmaniax** [googlemaps/google-maps-services-java#157]
After upgrading the google-maps-services dependency in my Java/Play app to v0.1.14, all emails are being sent using com.google.appengine.api.mail.stdimpl.GMTransport and not the standard SMTP transport which breaks my application. It looks like appengine-api-1.0-sdk has JavaMail packages which might be overriding standard behaviour. The only solution was to exclude the sub dependency of appengine-api-1.0-sdk

**Comment by domesticmouse** [comment]
I believe this is a duplicate of https://github.com/googlemaps/google-maps-services-java/issues/155

Thanks!

**Comment by tazmaniax** [comment]
Great, thx

**Comment by domesticmouse** [comment]
This should be now fixed in 0.1.15. Thanks for the report!
