### ISSUE TITLE
Not able to specify language while reverse geocoding

### ISSUE THREAD

**Issue by lsoares** [googlemaps/google-maps-services-java#173]
[The Google Place Search API allows to specify the language in the results](https://developers.google.com/places/web-service/search), using `language` parameter.

I tried to do the same using the Java client but I couldn't.

Is this a limitation? thanks

**Comment by domesticmouse** [comment]
Does the following test show you how to move forward? 

```
  @Test
  public void testPlacesTextSearchWithLanguage() throws Exception {
    PlacesSearchResponse response = PlacesApi.textSearchQuery(context, "Pizza in NYC").language("es").await();
    assertNotNull(response);
    assertNotNull(response.results[0]);
  }
```

**Comment by lsoares** [comment]
Yes. It it showed. 
(I thought the parameter made part of the context.).
Thank you.
