### ISSUE TITLE
Allow requests without any authorisation?

### ISSUE THREAD

**Issue by matze09** [googlemaps/google-maps-services-java#183]
Hi,

in general it is possible to make requests against a Google API without any authorisation, e.g.

`https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA`

This is of course not recommended for production use. However, it can be useful for testing in local environments, where no API Keys / Crypto Keys etc. are present/known and only a small number of test requests are being made.

However, the google-maps-services-java library does not allow this at all but enforces either an API Key or Client ID / Crypto Key to be present instead.

Is this intentional behaviour? Otherwise, it would be great if a "no auth" option could be added to the GeoApiContext. 

Do you think it is a better approach to just create a free API key for local testing purposes instead?

Many thanks for your help/suggestions and best regards,
Matthias

**Comment by domesticmouse** [comment]
Part of the goal of this client library was to encourage best usage practices of our APIs, and supplying API keys is most certainly one of these best practices. Thus this client library will always require a API Key. Sorry about the pain that causes, but it helps reduce the pain we have to deal with when we have to rate limit keyless API request storms that are causing issues on our backends.

**Comment by matze09** [comment]
Thanks Brett for your answer. That's totally fine and does make sense indeed. I went ahead and generated a free API key already anyway and just wanted to be sure that I did not overlook anything in your API. Cheers

**Comment by domesticmouse** [comment]
Thanks for your understanding @matze09 =)
