### ISSUE TITLE
Logging facade instead of direct usage of the Java Logging

### ISSUE THREAD

**Issue by mprus** [googlemaps/google-maps-services-java#184]
It would be much convenient for the end user. Without it they have to struggle with Java Logging

**Comment by domesticmouse** [comment]
I'm curious which logging facade you would suggest? Maybe spin up a small pull request that demonstrates what you'd like to see?

**Comment by mprus** [comment]
I would suggest the simple logging facade http://www.slf4j.org/

**Comment by hth** [comment]
Recently I have been dealing with **Google billing** for `GeocodingApi` and `PlaceApi`. They seem to claim I have been using more number of hits than what my logs shows. Discrepancy is almost of **340 times**. I have logs to prove, but some how I am missing capturing logs for `google-maps-services-java` api. If I can capture logs for this api, I can prove it is the Google and not the API issue either. So this will be helpful as Google billing is not able to provide any logs as they only count **HTTP 200** status response for billing. 

I would put this request on higher priority.

**Comment by domesticmouse** [comment]
@hth Please raise an issue through the [Google Maps Issue Tracker](https://developers.google.com/maps/documentation/geocoding/support#issue-tracker). This issue tracker is for the Client Library. We aren't in a position to help with Billing issues. Thanks!

I'm closing out this bug as I believe it has been covered off by merging #186.
