### ISSUE TITLE
Unknown type for enum:  'light_rail_station'

### ISSUE THREAD

**Issue by rammrain** [googlemaps/google-maps-services-java#191]
Got this warning with request to https://maps.googleapis.com/maps/api/geocode/json?language=et&region=ee&latlng=59.41404330%2C24.73965640

c.google.maps.internal.SafeEnumAdapter   : Unknown type for enum com.google.maps.model.AddressType: 'light_rail_station'

**Comment by domesticmouse** [comment]
I believe this has been fixed. Thanks!
