### ISSUE TITLE
Useable on Android?

### ISSUE THREAD

**Issue by aadithyb** [googlemaps/google-maps-services-java#195]
More of a question than a issue because I have not found regarding this anywhere. Can this library be used on Android as well?

**Comment by domesticmouse** [comment]
This client library isn't designed to be used on Android, as there are issues with API key security. Please see [Making the most of the Google Maps Web Service APIs](https://googlegeodevelopers.blogspot.com.au/2016/09/making-most-of-google-maps-web-service.html) for a run down of why, and options for working around this limitation. Thanks!
