### ISSUE TITLE
use env variable or D property to set the hostName

### ISSUE THREAD

**Issue by zvrablik** [googlemaps/google-maps-services-java#196]
Hi,
I would like to be able to override the hostName to test with mockServer I created
https://github.com/zvrablik/geocodingMockServer

I was about to add check to the ApiConfig constructor, but I see there are GeolocationApi and RoadsApi overriding the hostName with ApiConfig.hostName method.
So I would like to move the hostName to constructor and remove the hostName method.
There will be two constructors one with path and hostName and the existing one just with path.
In all cases if hostName property is set the constructor parameters will be ignored.

Would you accept such pull request?

**Comment by domesticmouse** [comment]
My priority is to make sure a change like this is only really for test code, so I'd prefer not to expose it as a constructor.

**Comment by AndreSchulzBerlin** [comment]
Replacing the hostName would be also useful for productive purposes:
We are behind a proxy, so we need to replace https://maps.googleapis.com by something like https://localhost:7799

The only way to do it (at the moment) is, to use reflection…

**Comment by domesticmouse** [comment]
I'm guessing the underlying OkHttp client library exposes a proxy server configuration, so for this specific use case I'm happy to take a PR that exposes proxy configuration.
