### ISSUE TITLE
Support for rxjava/rxandroid

### ISSUE THREAD

**Issue by Zulqurnain** [googlemaps/google-maps-services-java#201]
i would like to use this api with rxandroid , are there any good ways/examples to illustrate that , i'm more concerned about placesapi

**Comment by domesticmouse** [comment]
This API isn't designed to be used on Android. Please see my blogpost [Making the most of the Google Maps Web Service APIs](https://googlegeodevelopers.blogspot.com.au/2016/09/making-most-of-google-maps-web-service.html) for more information.
