### ISSUE TITLE
Make GeoApiContext.setBaseUrlForTesting public?

### ISSUE THREAD

**Issue by matze09** [googlemaps/google-maps-services-java#202]
Hi,

in order to ease testing, it would be great to have the scope of this method

`GeoApiContext.setBaseUrlForTesting(String baseUrl)`

adjusted to be public instead of package-private. 
This way a mock server URL (e.g. Wiremock) could be specified for integration testing.

Would that be reasonable or am I missing something which would allow me to do this right now already?

Many thanks for your help and ideas,
Matthias

**Comment by domesticmouse** [comment]
Hey Matthias,

I'd rather not make setBaseUrlForTesting as public as it is not intended to be a part of the public API. For testing purposes you can over ride it by subclassing it in your test suite.

brett

**Comment by matze09** [comment]
Brett,

thanks for your reply. That's fine with me, I'll try that. :)

Best,
Matthias

**Comment by markhobson** [comment]
Would it be possible to make `setBaseUrlForTesting` protected rather than package-protected? It's currently hard to subclass as we would have to use the Google package name. Even then it's possible to get `IllegalAccessError`s when the split package classloaders are different.
