### ISSUE TITLE
Distance Matrix requests not properly rate limited

### ISSUE THREAD

**Issue by amc6** [googlemaps/google-maps-services-java#214]
It seems like the distance matrix qps is calculated differently than other requests.  (https://developers.google.com/maps/documentation/distance-matrix/usage-limits) It appears that the rate is based on the number of elements in the matrix not the number of requests. So for example, a 25 by 25 matrix counts as 625 not 1. Because of this, the rates for distance matrix and driving directions are not necessarily the same. i.e. it might be 10 qps for the directions service but 200 qps for the distance matrix service. 

The `GeoApiContext` object only accepts a single qps parameter. Because the distance matrix has a higher limit but that limit is per element, requests are not properly limited. They end up being made faster than they should be. In other words, a qps parameter of 10 would allow 6250 distance matrix requests.

**Comment by domesticmouse** [comment]
The Distance Matrix limits, and the Places API limits for that matter, are different restrictions to the QPS limit that this library is concerned with. The over arching limits for both Distance Matrix and Places API on the total number of requests per day is something that I feel is better handled at a different layer than a per second throttle. As to enforcing Distance Matrix element limits (100 elements per request), I'm happy to review Pull Requests, if you feel this functionality would be helpful

**Comment by amc6** [comment]
Oh sorry. I agree that its not the library's concern to keep track of the daily limit. The problem is that the distance matrix's qps is both a different number and it is counted differently.

Normally I'd be happy to implement a fix. But I think fixing this is going to require a fairly large change that I unfortunately don't have time for. The point at which this library does rate limiting is too far removed from the point where it knows what the request actually is. So it would require some refactoring so that the rate limiter knew what a Distance Matrix request was and how to treat it differently. Additionally all of the requests seem to go into one queue. So a different qps number would require rewriting how that works.

In the meantime, I've been able to wrap our calls to the distance matrix with my own rate limiting code. But I'm doing it in a way that doesn't make sense to add to this library.

**Comment by domesticmouse** [comment]
The various QPS limit is over and above the QPD limits. Given how tight these limits are, I'd argue that your approach of adding additional infrastructure to monitor and limit usage of this resource is the correct approach.
