### ISSUE TITLE
Testing PlaceAutocompleteRequest is not working

### ISSUE THREAD

**Issue by Chanuuu** [googlemaps/google-maps-services-java#224]
Hi ,

Can you please help me with the below error . I am getting this error from the attached test code .Below is my Pom and error

Pom.xml 
<dependencies>
  	<dependency>
  		<groupId>com.google.maps</groupId>
  		<artifactId>google-maps-services</artifactId>
  		<version>0.1.17</version>
  	</dependency>
  </dependencies>

Error Message :
Exception in thread "main" java.lang.NoClassDefFoundError: com/squareup/okhttp/MediaType
	at com.google.maps.OkHttpRequestHandler.<clinit>(OkHttpRequestHandler.java:43)
	at TestHarness.main(TestHarness.java:12)
Caused by: java.lang.ClassNotFoundException: com.squareup.okhttp.MediaType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

**Comment by domesticmouse** [comment]
Can you please try this simple test case?

```java
package com.domesticmouse;

import com.google.maps.GeoApiContext;
import com.google.maps.PlacesApi;
import com.google.maps.model.AutocompletePrediction;

/**
 * Created by brettmorgan on 1/20/17.
 */
public class PlaceAutocompleteTest {

  public static void main(String[] args) throws Exception {
    GeoApiContext context = new GeoApiContext().setApiKey("AIza...");
    final AutocompletePrediction[] autocompletePredictions = PlacesApi.placeAutocomplete(context, "Sydney Town Ha").await();
    for(AutocompletePrediction prediction : autocompletePredictions) {
      System.out.println(prediction.description);
    }
  }
}
```

I'm using the following gradle config:

```groovy
group 'com.domesticmouse'
version '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'application'

mainClassName = "com.domesticmouse.PlaceAutocompleteTest"
sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.google.maps:google-maps-services:0.1.17'
}
```

**Comment by domesticmouse** [comment]
Please re-open if this is still an issue. Thanks!
