### ISSUE TITLE
How to use DirectionsApiRequest?

### ISSUE THREAD

**Issue by FilenkovMaxim** [googlemaps/google-maps-services-java#227]
How to use DirectionsApiRequest class?
Did you forget make DirectionsApiRequest constructor public or there is only one properly way with DirectionsApi.newRequest(geoApiContext) ?

**Comment by domesticmouse** [comment]
It looks like there is a variety of calling conventions in the library. It's almost like this library has had a variety of maintainers over the years. Sigh.

**Comment by domesticmouse** [comment]
Given that I am about to break all of the calling conventions by migrating to OkHttp3, I'm going to close out this issue at this time. For the time being I suggest you go with DirectionsApi.newRequest(...).
