### ISSUE TITLE
Question about QPS using google-maps-service

### ISSUE THREAD

**Issue by irineuruiz** [googlemaps/google-maps-services-java#228]
We have a premium account, so we assume we can made 50 qps for geocoding when we send various geocoding request.

We made a simple code to test our performance.

``

	private static int TOTAL_REQ = 50;
	
	private static final GeoApiContext context = new GeoApiContext().setQueryRateLimit(50, 0)
			.setApiKey("OUR_API_KEY")
			.setEnterpriseCredentials("CREDENTIAL", "CRENDENTIAL");

	public static void main(String[] args) throws Exception {
		List<LatLng> latLngs = new ArrayList<LatLng>();
		// Random locations
		Random randomGenerator = new Random();
		for (int i = 0; i < TOTAL_REQ; i++) {
			LatLng point = new LatLng(randomGenerator.nextDouble() - 23.5798154,
					randomGenerator.nextDouble() - 46.6945082);
			latLngs.add(point);
		}

		//First take always too long
		LatLng point = new LatLng(randomGenerator.nextDouble() - 23.5798154, randomGenerator.nextDouble() - 46.6945082);
		new GeocodingApiRequest(context).language("pt-BR").latlng(point).await();

		//Stopwatch clock = Stopwatch.createStarted();
		long millis = System.currentTimeMillis();
		
		final AtomicInteger counter = new AtomicInteger(TOTAL_REQ);
		for (final LatLng latLng : latLngs) {
			GeocodingApiRequest request = new GeocodingApiRequest(context).language("pt-BR");
			request.latlng(latLng).setCallback(new Callback<GeocodingResult[]>() {
				public void onResult(GeocodingResult[] result) {
					System.out.println(result[0].formattedAddress);
					counter.decrementAndGet();
				}

				public void onFailure(Throwable e) {
					e.printStackTrace();
				}
			});
		}

		while (counter.get() > 0){
			Thread.sleep(100);
		}
		millis = System.currentTimeMillis() - millis;
		System.out.println("Time taken: " + millis);
		System.out.println("QPS achieved: " + TOTAL_REQ/(double)millis/1000);
	}

``

That is the result obtained:

Time taken: 13108
QPS achieved: 3.8144644491913335E-6

Our question is: 
Why we have such QPS? Is this normal?
We expected something near 50 QPS..

We looked the network during the execution and we saw that only 2 or 3 http connections was opened by OkHttpClient to make the requests...
Looks like this is related with this lower qps.

**Comment by nbluis** [comment]
I've encountered the same problem.  Theres more information about on #256.

**Comment by domesticmouse** [comment]
I believe this is fixed by the just released v0.1.20 build. Please re-open if this isn't the case.
