### ISSUE TITLE
to add support for AddressTypes

### ISSUE THREAD

**Issue by beshkin** [googlemaps/google-maps-services-java#229]
Hi,

there are some AddressTypes map are missing.
- food
- grocery_or_supermarket
- store
- synagogue

The following requests return the set of address types:
https://maps.googleapis.com/maps/api/geocode/json?key=API_KEY&address=Noah%27s+Marketplace%2C+21800+W+Eleven+Mile+Rd
https://maps.googleapis.com/maps/api/geocode/json?key=API_KEY&address=Ahavas+Olam%2C+15620+W.+Ten+Mile+Road

thank you in advance for help.

**Comment by rux** [comment]
I am also getting warnings for the types bar and night_club.  An example location is "Fabric, London"

**Comment by zaschim** [comment]
Bump

**Comment by omervk** [comment]
Some more address types that aren't handled by the enum:
- lawyer
- health
- insurance_agency
- gas_station
- car_dealer
- car_repair
- meal_takeaway
- furniture_store
- home_goods_store
- shopping_mall
- gym
- accounting
- moving_company
- lodging
- storage

**Comment by domesticmouse** [comment]
This should now be fixed. I'll bundle this up in a release in the near-ish future.

**Comment by beshkin** [comment]
Cool, thanks a lot


[image: photo]
Misha Beshkin
founder, KosherDev
Phone  +372-534454663  <+372-534454663>
Email  misha@beshkin.lv  <misha@beshkin.lv>
Blog. http://misha.beshkin.lv
Is it kosher?. http://iskosher.com

<http://facebook.com/beshkin> <http://twitter.com/midbar>
<http://instagram.com/beshkin>
Get your own email signature
<https://wisestamp.com/email-install?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>
