### ISSUE TITLE
Want to use google map services with Java6

### ISSUE THREAD

**Issue by ashok-rajpoot** [googlemaps/google-maps-services-java#230]
Our production environment already setup with java6. So i want to use  google map services with Java6. 
Is there any java6 compatible version of google map services available. 
Please help me as soon as possible, i am stuck with that.

Thanks
Ashok

**Comment by daisy1754** [comment]
I believe you can use the latest release ([v0.1.17](https://github.com/googlemaps/google-maps-services-java/releases/tag/v0.1.17) with java 6. 

I updated gradle config to require Java 7 a few days ago with #236 and using Java 7 APIs in #238, but before that there was no Java 7 API is used AFAIK, even though README says Java 7 is required.

**Comment by domesticmouse** [comment]
@ashok-rajpoot Given [Oracle's roadmap](http://www.oracle.com/technetwork/java/eol-135779.html) showing that Java 6 ended public updates back in 2013, I'm not aiming to restrict this client library to a Java 6 subset. 

On the flip side, this is a open source project, so I suggest you look into forking this codebase and strip out the post Java 6 code. Hope that helps!
