### ISSUE TITLE
Use BigDecimal instead of java.lang.Double

### ISSUE THREAD

**Issue by ptahchiev** [googlemaps/google-maps-services-java#231]
Please use `java.math.BigDecimal` instead of `java.lang.Double`. Double is not precise enough when you deal with maps. Please read more about it here:

http://stackoverflow.com/questions/3413448/double-vs-bigdecimal

**Comment by domesticmouse** [comment]
Can you please give examples of where `Double` is insufficient for Mapping? This will be a breaking change for everyone using this API, so before I go about breaking everyone, I'd like to have sufficient evidence to back the claim. The linked discussion on S/O has zero maps or GIS examples, if I read it correctly.

Going by this answer from GIS Stack Exchange: [measuring accuracy of latitude and longitude](https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude/8674#8674), we need about 13 significant decimal digits, and according to [Wikipedia article on Double Precision](https://en.wikipedia.org/wiki/Double-precision_floating-point_format) we have about 15 significant decimal digits in IEEE 754 double precision representation. 

Please re-open this issue with an example or three. Thanks!
