### ISSUE TITLE
Google Static Maps API support

### ISSUE THREAD

**Issue by IvanRF** [googlemaps/google-maps-services-java#233]
I think this library can easily support the [Google Static Maps API](https://developers.google.com/maps/documentation/static-maps/intro) too. Most of the communication protocols are already implemented, like the `UrlSigner` class for [Get a Key and Signature/Authentication](https://developers.google.com/maps/documentation/static-maps/get-api-key).

The only work to do is to map the parameters that can be included in a call to `https://maps.googleapis.com/maps/api/staticmap?...`.

I'm already using both this library and HTTP calls to the Static Maps API to get the `byte[]` of a map's image, which I then convert to a `BufferedImage`.

According to the documentation, Google Static Maps API is listed for the [Web platform](https://developers.google.com/maps/web/) and this library is intended for [Web services](https://developers.google.com/maps/web-services/). Nevertheless, this specific API can be useful for Java applications too, not only webs.

**Comment by domesticmouse** [comment]
This will be fixed in v0.2.2.

**Comment by domesticmouse** [comment]
Actually, I was thinking of the golang implementation. Whups.

**Comment by IvanRF** [comment]
@domesticmouse first of all, thank you very much for adding Static Maps API to the library! 👍 

I just replaced my own implementation and started using the library for Static Maps API calls too. So far everything seems to work fine.

The only thing that I was using and it was not implemented here is `Encoded polyline` as a valid value for `path`.

From https://developers.google.com/maps/documentation/maps-static/dev-guide

> path (optional) defines a single path of two or more connected points to overlay on the image at specified locations. This parameter takes a string of point definitions separated by the pipe character (|), **or an encoded polyline using the `enc:` prefix within the location declaration of the path**.

More info at: [EncodedPolylines](https://developers.google.com/maps/documentation/maps-static/dev-guide#EncodedPolylines).

I was using this in the URL in order to show a map from a `DirectionsRoute`:
```
DirectionsRoute route;
...
EncodedPolyline polyline = route.overviewPolyline;
parameters += "&path=enc" + colon + URLEncoder.encode(polyline.getEncodedPath(), "UTF-8");
```

Now with the library I'm using this:
```
Path path = new Path();
for (LatLng point : polyline.decodePath())
	path.addPoint(point);
req.path(path);
```

**Comment by apjanke** [comment]
Yeah, that seems a little verbose and inconvenient.

There's a direct relationship between an `EncodedPolyline` and a `StaticMapsRequest.Path`, even though `EncodedPolyline` seems like a somewhat lower-level object to me. And it does map directly to an API calling form.

Perhaps a convenience constructor or factory method is in order? Something like one of the following:

```
public class StaticMapsRequest ... {
  public static class Path implements UrlValue {
    public Path(EncodedPolyline ep) // option 1
    public static Path fromEncodedPolyline(EncodedPolyline ep) // option 2
    public void addEncodedPolyline(EncodedPolyline ep) // option 3; works like a sequence of addPpoint() calls
  }
  public StaticMapsRequest path(EncodedPolyline path) // option 4; auto-converts internally
}
```

Option 4 is my favorite, I think.

The architecture astronaut in me says that both `StaticMapsRequest.Path` and `EncodedPolyline` could implement a common `PointSequence` interface and have `StaticMapsRequest.path()` code to that, but that's probably excessive.

**Comment by domesticmouse** [comment]
I like option 4, as it allows the library to pick the shortest encoding at run time. Happy to accept a PR. ;-)

**Comment by apjanke** [comment]
Here's a PR for option 4: https://github.com/googlemaps/google-maps-services-java/pull/511  :)
