### ISSUE TITLE
Best practice for mocking Request object in unit test?

### ISSUE THREAD

**Issue by daisy1754** [googlemaps/google-maps-services-java#234]
Hi,

Currently, ApiRequest object (e.g., GeocodingApiRequest) plays two role: 1) data class containing all request params and 2) sending request to backend. It makes supplying fake response in unit test hard. Indeed, test class in this repo kicks real backend, and have Thread.sleep in test (https://github.com/googlemaps/google-maps-services-java/blob/master/src/test/java/com/google/maps/GeocodingApiTest.java#L88).

We'd love to avoid using real backend in unit test. Is there any workaround or best practice known to team?
Thanks,

**Comment by daisy1754** [comment]
For reference, we currently have code like below. We created class named GeocodeRequestSender so it can be mocked in the unit test.

would love to know if there is better way or team is planning to support better way.  

```
/** Thin wrapper around GeocodingApiRequest.send so we can mock it in unit test */
public class GeocodeRequestSender {

  /** Sends request and waits for the result. */
  public GeocodingResult[] sendRequest(GeocodingApiRequest request) throws Exception {
    return request.await();
  }
}
```

```
/** This class uses Geocoding API for business logic */
public class FooBar {

  // Inject GeocodeRequestSender from outside so it can be replaced with fake in test.
  public void foo(GeocodeRequestSender sender) {
    GeocodingApiRequest request =
      new GeocodingApiRequest(new GeoApiContext().setApiKey(API_KEY))
        .components(
    ComponentFilter.postalCode(postalCode), ComponentFilter.country(countryCode))
        .language(language);

    GeocodingResult[] results = requestSender.sendRequest(request);
  }
}
```

**Comment by domesticmouse** [comment]
I am about to migrate from `OkHttp2` to `OkHttp3` which will require some API breakage. This introduces an opportunity to introduce interfaces and/or layers of indirection to make testing easier. Do you have any suggestions on what changes you'd like to see made to the API?

**Comment by daisy1754** [comment]
My suggestion would be to decouple two roles I mentioned in the first comment. 

For instance, you could define ApiClient class like below, where 1) GeocodingRequest is a data class containing all request params and 2) sending a request to the backend is the job of ApiClient. With this, I could just mock ApiClient while using the real `Request` object.

```:java
public interface ApiClient {
  ListenableFuture<GeocodingResponse> sendRequest(GeocodingRequest request);
}
```

`okhttp3` itself has similar separation (they provide one more layer by `Call` class for more fine grained control) 

```
// Request object contains information about the request, e.g., URL, method and parameters
Request request = new Request.Builder().url("https://example.com").get().build();
// Client determines high-level settings like cache and network configuration, and acts as factory to generate the Call object
OkHttpClient client = client.newBuilder().build();
// Call corresponds to actual HTTP request invocation and provides a hook to set a listener
Call call = client.newCall(request);
Response response = call.execute();
```

**Comment by domesticmouse** [comment]
Thank you @daisy1754, I'll keep that in mind as I migrate to OkHttp3.

**Comment by domesticmouse** [comment]
Closing out this issue for now. Thanks for the input @daisy1754
