### ISSUE TITLE
Problem with 0.1.17 - maybe locale?

### ISSUE THREAD

**Issue by vguna** [googlemaps/google-maps-services-java#235]
Hi.

I recently switched from 0.1.16 to 0.1.17 for looking up addresses.
It seems that something has changed related to locale (?).

My developer machine has german locale set (windows), our buildserver has an english locale (linux) set. Since I switched to 0.1.17 one of our testcases break on the server only, when looking up an address where only street and postalcode is specified.

The funny thing: the requests sent look identical, but the result is different:

Dev machine:
```
INFORMATION: Request: https://maps.googleapis.com/maps/api/geocode/json?key=MYKEY&address=Gemarkenstr.++45147+++DE&language=de&region=de
22:12:28,344 DEBUG [] [GoogleMapsGeoLocationProvider] - google maps returned 1 matches: address matches for: AddressLocation[street=Gemarkenstr., streetNo=null, postalCode=45147, city=null, stateIsoCode=null, countryIsoCode=DE, geoLocation=null],
results: [Gemarkenstraße, 45147 Essen, Deutschland]
```

Build machine:
```
INFO: Request: https://maps.googleapis.com/maps/api/geocode/json?key=MYKEY&address=Gemarkenstr.++45147+++DE&language=de&region=de
22:05:32,424 DEBUG [] [GoogleMapsGeoLocationProvider] - google maps returned 1 matches: address matches for: AddressLocation[street=Gemarkenstr., streetNo=null, postalCode=45147, city=null, stateIsoCode=null, countryIsoCode=DE, geoLocation=null],
results: [Gemarkenstraße, Essen, Deutschland]
```

As you can see, although the request url is the same, the result is different (one with postalcode null the other 45147 - which is expected). You can also see INFORMATION instead of INFO. Which lets me thinking that this might be locale related.

Switching back to 0.1.16 "fixes" the problem.

Any idea what's going on?

**Comment by domesticmouse** [comment]
I had a quick review of the delta between the two versions using GitHub's [compare functionality](https://github.com/googlemaps/google-maps-services-java/compare/v0.1.16...v0.1.17). The diff is not showing me anything that stands out as being able to cause the difference you are seeing.

I believe OkHttp sends language settings based on locale, which our servers use to bias results. That said, it looks more like you are seeing results from different clusters. These kinds of variances in responses are to be expected as we roll forward (and occasionally roll back) functionality in our data centers.
