### ISSUE TITLE
Calling optimizeWaypoints after waypoints

### ISSUE THREAD

**Issue by IvanRF** [googlemaps/google-maps-services-java#237]
Calling `optimizeWaypoints()` after `waypoints()` is not working. This issue was solved on [this commit](https://github.com/googlemaps/google-maps-services-java/commit/c380e05d497d14ed380bd4c4e3bfae6b398ac15f) but it is not part of version 0.1.17.

You can check [Maven sources](http://search.maven.org/remotecontent?filepath=com/google/maps/google-maps-services/0.1.17/google-maps-services-0.1.17-sources.jar).

It's weird since the latest version was released after that commit.

**Comment by domesticmouse** [comment]
I goofed something somewhere. I'll roll a new release in a week or two.

**Comment by domesticmouse** [comment]
This should now be fixed. Please comment to re-open if you are still seeing an issue after upgrading.
