### ISSUE TITLE
After including the maven dependency, project stops working.

### ISSUE THREAD

**Issue by pratiksanglikar** [googlemaps/google-maps-services-java#241]
I am using Java 1.8 for my project.
I included the repo as a maven dependency, but the Apache Tomcat server fails to start when I include this dependency. The server starts normally after removing the dependency.

Any issue with nested dependencies?

**Comment by pratiksanglikar** [comment]
Looks like the problem is because the library resets the `joda-time` library to 2.4
as opposed to `joda-time` 2.9.4 that I'm using.

**Comment by domesticmouse** [comment]
I'm happy to accept pull requests to bring the dependencies up to date. Thanks!

**Comment by domesticmouse** [comment]
This should now be fixed by version 0.1.18. It should show up on Maven Central in the next 24 hours...
