### ISSUE TITLE
GeoApiContext throwing 403 Forbidden with enterprise credentials

### ISSUE THREAD

**Issue by esstwo** [googlemaps/google-maps-services-java#248]
thanks for the new 0.1.18 release.
I tried integrating my code with this new release and get a 403 Forbidden exception.
Same code works fine with the previous release.

All I am doing is getting the context using this:
`new GeoApiContext().setEnterpriseCredentials(CLIENT_ID, CLIENT_SIGNATURE);`

and then using it 
`GeocodingResult[] results = GeocodingApi.reverseGeocode(getContext(), new LatLng(lat, lon)).await();`

this line throws: Server Error: 403 Forbidden

**Comment by mlmilan** [comment]
Confirmed, the problem is GeoApiContext.class line 213, 
`if (canUseClientId && clientId != null) {
   url.append("&signature=").append(urlSigner.getSignature(url.toString()));
}`
url is of StringBuilder type and will append "&signature=" param before actual signature generation.

**Comment by nbluis** [comment]
I'm having same problem. :open_mouth: 
Currently using 'com.google.maps:google-maps-services:0.1.18'

**Comment by nbluis** [comment]
I tested it with version 0.1.17 and it worked correctly.

**Comment by domesticmouse** [comment]
Whups, my bad. I'll fix and get 0.1.19 up ASAP

**Comment by domesticmouse** [comment]
I've just pushed v0.1.19 to Sonatype, should make it out to Maven Central in the next 24 hours.
