### ISSUE TITLE
Rendering the DirectionResults on the map using javascript

### ISSUE THREAD

**Issue by kirankn8** [googlemaps/google-maps-services-java#249]
I have been facing the issue of displaying the Direction results on the google map.
```
result = JSON.parse(this.responseText);
directionsDisplay.setDirections(result);
```

The line of code simply fails to render on the map in the browser giving an error "not a LatLngBounds or LatLngBoundsLiteral: unknown property northeast"

**Comment by domesticmouse** [comment]
I can't really debug what is going on from the supplied snippet. I'd suggest that you instead put together a minimised executable reproduction and post it to [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps-api-3). Thanks!
