### ISSUE TITLE
OkHttp limiting concurrent requests 

### ISSUE THREAD

**Issue by nbluis** [googlemaps/google-maps-services-java#256]
I'm using the API to perform parallel coordinate processing.

But even setting setQueriesPerSecond(20) when building GeoApiContext, apparently it performs on average only 5 querys per second, regardless of the value set.

I use an account with enterprise credentials and outside GAE.

I found the following snippets that I think might be causing the problem.

When creating the [RequestHandler](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/OkHttpRequestHandler.java#L48) is instantiated an okhttp Dispatcher.

By default the Dispatcher has a [request limit per host](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Dispatcher.java#L40).

Since all requests to the API are made to the same host, I believe that when creating the Dispatcher it should invoke [Dispatcher.setMaxRequestsPerHost](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Dispatcher.java#L98) sending the limit coming from GeoApiContext, otherwise this setting will not work properly.

What do you think ?

I can try to verify this and send a pull request with the fix.

**Comment by domesticmouse** [comment]
I'm happy to accept a PR for this once you have verified.
