### ISSUE TITLE
version 0.1.19 doesn't include GeocodingApi class

### ISSUE THREAD

**Issue by chongma** [googlemaps/google-maps-services-java#257]
hi, it is my first time using this api and i tried to install 0.1.19 but it didn't work with the example on the readme.  the GeocodingApi class does not seem to be present.  rolling back to 0.1.18 seems to work so far.  maybe there is a problem or maybe the documentation needs updating?

**Comment by domesticmouse** [comment]
Looks like I goofed while releasing 0.1.19. Let's have a go at rolling out 0.1.20.

**Comment by chongma** [comment]
Hi, thanks for the reply. I had another problem but i am not sure if it is my end or not. I am able to add the package to my project and it works fine during compile. But when i deploy i get an error that it is an invalid zip file. I am using TomEE 7.0.2. i thought it might be my maven so i cleaned it and tried changing the version number of other libraries but i had no problems except with Google maps lib.

**Comment by domesticmouse** [comment]
A clean build of version 0.1.20 should be out in about ~24 hours. There is some delay going through Sonatype's hosting to Maven Central.

**Comment by Stephan202** [comment]
@domesticmouse: version 0.1.20 is now on Maven Central, but I see no corresponding Git tag. Does this mean that 0.1.20 is "merely a rebuild", based off tag [`0.1.19`](https://github.com/googlemaps/google-maps-services-java/tree/v0.1.19)?

**Comment by domesticmouse** [comment]
Version 0.1.20 now tagged and released. I thought it would take longer to propagate. I've tested the release with the following code, and it works fine for me.

```java
package com.google.testing123;

import com.google.maps.GeoApiContext;
import com.google.maps.GeocodingApi;
import com.google.maps.errors.ApiException;
import com.google.maps.model.GeocodingResult;
import java.io.IOException;

public class Main {
  public static void main(String[] args) throws InterruptedException, ApiException, IOException {
    final String query = "1600 Amphitheatre Parkway Mountain View, CA 94043";
    final String apiKey = "AIzaNotARealKey";

    System.out.printf("Running Geocoding request for: %s\n", query);
    GeoApiContext context = new GeoApiContext().setApiKey(apiKey);
    GeocodingResult[] results =  GeocodingApi.geocode(context, query).await();
    System.out.printf("Formatted address: %s\n", results[0].formattedAddress);
    System.out.printf("Location: %s\n", results[0].geometry.location);
  }
}
```
