### ISSUE TITLE
Failed to load class org.slf4j.impl.StaticLoggerBinder

### ISSUE THREAD

**Issue by IvanRF** [googlemaps/google-maps-services-java#266]
Since version 0.1.18 this message is thrown in the console:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
MLog initialization issue: slf4j found no binding or threatened to use its (dangerously silent) NOPLogger. We consider the slf4j library not found.
```

(I use Log4j)

**Comment by domesticmouse** [comment]
Reading up on the documentation linked at the end of that link, the user of the library now needs to depend on one of the `slf4j` adaptor packages. As much as I'd like to just depend straight on nop, that will cause conflicts for anyone who then chooses to use something like [slf4j-log4j12](http://search.maven.org/#artifactdetails%7Corg.slf4j%7Cslf4j-log4j12%7C1.7.25%7Cjar)

I believe if you add the following line (or equivalent) to your `build.gradle` that your error message will go away:
```
    compile 'org.slf4j:slf4j-log4j12:1.7.25'
```

Please re-open if this isn't the case. I'm going to add a note to the README about this dependency. Thanks!

**Comment by IvanRF** [comment]
Yes, I just test it and adding `slf4j-log4j12` removes the message 😃

**Comment by domesticmouse** [comment]
Added some documentation in https://github.com/googlemaps/google-maps-services-java/pull/271

Thanks!
