### ISSUE TITLE
Different results when specifying the "accept-language" header

### ISSUE THREAD

**Issue by snussbaumer** [googlemaps/google-maps-services-java#270]
I get different results when I specify an `accept-language` header. For example : 
```
curl https://maps.googleapis.com/maps/api/geocode/json\?key\={your_key}\&address\=ZAEC+de+l%27Ormeau+32+rue+Jean+Rostand%2C+77380%2C+COMBS+LA+VILLE%2C+Seine-et-Marne%2C+FR\&region\=fr-FR
{
   "results" : [],
   "status" : "ZERO_RESULTS"
}
```

But when I add an `accept-language` header saying I'd prefer french, I get : 

```
curl https://maps.googleapis.com/maps/api/geocode/json\?key\={your_key}\&address\=ZAEC+de+l%27Ormeau+32+rue+Jean+Rostand%2C+77380%2C+COMBS+LA+VILLE%2C+Seine-et-Marne%2C+FR\&region\=fr-FR -H 'accept-language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4'
{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "32",
               "short_name" : "32",
               "types" : [ "street_number" ]
            },
            {
               "long_name" : "Rue Jean Rostand",
               "short_name" : "Rue Jean Rostand",
               "types" : [ "route" ]
            },
            {
               "long_name" : "Combs-la-Ville",
               "short_name" : "Combs-la-Ville",
               "types" : [ "locality", "political" ]
            },
            {
               "long_name" : "Seine-et-Marne",
               "short_name" : "Seine-et-Marne",
               "types" : [ "administrative_area_level_2", "political" ]
            },
            {
               "long_name" : "Île-de-France",
               "short_name" : "Île-de-France",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "France",
               "short_name" : "FR",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "77380",
               "short_name" : "77380",
               "types" : [ "postal_code" ]
            }
         ],
         "formatted_address" : "32 Rue Jean Rostand, 77380 Combs-la-Ville, France",
         "geometry" : {
            "location" : {
               "lat" : 48.6519993,
               "lng" : 2.5595175
            },
            "location_type" : "APPROXIMATE",
            "viewport" : {
               "northeast" : {
                  "lat" : 48.6533482802915,
                  "lng" : 2.560866480291502
               },
               "southwest" : {
                  "lat" : 48.6506503197085,
                  "lng" : 2.558168519708498
               }
            }
         },
         "partial_match" : true,
         "place_id" : "ChIJofgzH03i5UcRjXNSfD6nrJ0",
         "types" : [ "establishment", "general_contractor", "point_of_interest" ]
      }
   ],
   "status" : "OK"
}
```

The second result is way more desirable for me !

I checked that I can reproduce this when copying `OkHttpRequestHandler` and adding the line `.header("accept-language", "fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4")` at Request build time in `handle` and `handlePost`, but it looks to me as this should be something that you could specify at the request level, not the context level, right ? I have to geocode addresses from many countries, and these addresses will probably be formatted in the country way. So geocoding an address in germany I would probably need an `accept-language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4` header. Ideally the region parameter could be added to `handle` and `handlePost`, letting the RequestHandler do the job of adding the right header. Or even better, let GeoApiContext handle the creation of the appropriate headers, and give those headers to `handle` and `handlePost`.

For the time being I could have a context with a specif handler for each country and using the right one for each specific geocoding operation, but this isn't a great solution either.

This looks a lot like a region issue, but using the "region" parameter does not help (it's present in the curls above), whereas this header does.

Side note : I see the same behaviour with the Places API.

Am I doing something wrong here ? Or is there an other workaround ?

Thanks !

**Comment by domesticmouse** [comment]
There is a language parameter to the API that allows you to set the preferred language inline:

```
$ https://maps.googleapis.com/maps/api/geocode/json\?address\=ZAEC+de+l%27Ormeau+32+rue+Jean+Rostand%2C+77380%2C+COMBS+LA+VILLE%2C+Seine-et-Marne%2C+FR\&region\=fr-FR\&language=fr
```

See the [documentation](http://googlemaps.github.io/google-maps-services-java/v0.1.18/javadoc/com/google/maps/GeocodingApiRequest.html#language-java.lang.String-) for more detail. Thanks!

**Comment by domesticmouse** [comment]
Btw, if you believe you should be receiving these results independent of the language parameter (and I suspect you should), please feel free to raise an issue on the [Geocoding API issue tracker](https://developers.google.com/maps/documentation/geocoding/support#issue-tracker).

**Comment by snussbaumer** [comment]
Argh, didn't see that language parameter ! Many thanks !

**Comment by domesticmouse** [comment]
@xpoback please report this to https://developers.google.com/maps/support/#issue_tracker 

This issue tracker is just for the java client library, not the API itself.

**Comment by madness-inc** [comment]
For anyone who's interested in this topic:
Google says this is "intended behaviour", as state in theses (and many related) tickets:
https://issuetracker.google.com/issues/35822155
https://issuetracker.google.com/issues/173897415
