### ISSUE TITLE
WARNING: Unknown type for enum com.google.maps.model.AddressType: 'casino'

### ISSUE THREAD

**Issue by dimashi** [googlemaps/google-maps-services-java#279]
I got this warning trying to geocode "new york new york hotel casino 3790 las vegas boulevard south las vegas nv 89109 united states".

**Comment by apjanke** [comment]
Any chance you could provide a full stack trace for this? `casino` is [present in `PlaceType`](https://github.com/googlemaps/google-maps-services-java/blob/af0ca2621ff8157a2be9f63988aa102f9613d6cd/src/main/java/com/google/maps/model/PlaceType.java#L45), but not `AddressType`; I'm wondering if one of those is being substituted for the other somewhere.

**Comment by dimashi** [comment]
Unfortunately no. Google now returns ZERO_RESULTS for "new york new york hotel casino 3790 las vegas boulevard south las vegas nv 89109 united states", so I cannot reproduce it anymore.
It was code that tried to match string from response json to values in enum AddressType. If it could not match, it logged WARN with message "Unknown type for enum". If you search for this string you should be able to find the code. That's all I remember, sorry....

**Comment by dimashi** [comment]
To reproduce I used search text "new york new york hotel casino 3790 las vegas". Previous one does not work anymore. This json returned:
```{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "3790",
               "short_name" : "3790",
               "types" : [ "street_number" ]
            },
            {
               "long_name" : "South Las Vegas Boulevard",
               "short_name" : "S Las Vegas Blvd",
               "types" : [ "route" ]
            },
            {
               "long_name" : "Las Vegas",
               "short_name" : "Las Vegas",
               "types" : [ "locality", "political" ]
            },
            {
               "long_name" : "Clark County",
               "short_name" : "Clark County",
               "types" : [ "administrative_area_level_2", "political" ]
            },
            {
               "long_name" : "Nevada",
               "short_name" : "NV",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "United States",
               "short_name" : "US",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "89109",
               "short_name" : "89109",
               "types" : [ "postal_code" ]
            }
         ],
         "formatted_address" : "3790 S Las Vegas Blvd, Las Vegas, NV 89109, USA",
         "geometry" : {
            "location" : {
               "lat" : 36.1023715,
               "lng" : -115.1745559
            },
            "location_type" : "ROOFTOP",
            "viewport" : {
               "northeast" : {
                  "lat" : 36.10372048029149,
                  "lng" : -115.1732069197085
               },
               "southwest" : {
                  "lat" : 36.10102251970849,
                  "lng" : -115.1759048802915
               }
            }
         },
         "place_id" : "ChIJZ4lcwszFyIAR7nw_Ba2KrO0",
         "types" : [ "casino", "establishment", "lodging", "point_of_interest" ]
      }
   ],
   "status" : "OK"
}
```

**Comment by laradabreo** [comment]
I have a similar issue with this url and deserialising of the types: 

https://maps.googleapis.com/maps/api/geocode/json?address=Shop+309+Harbourside+Shopping+Centre+Darling+Harbour+NSW+2000

This returns:

{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "Shop 309, Harbourside Shopping Centre",
               "short_name" : "Shop 309, Harbourside Shopping Centre",
               "types" : [ "subpremise" ]
            },
            {
               "long_name" : "Darling Harbour",
               "short_name" : "Darling Harbour",
               "types" : [ "locality", "political" ]
            },
            {
               "long_name" : "Council of the City of Sydney",
               "short_name" : "Sydney",
               "types" : [ "administrative_area_level_2", "political" ]
            },
            {
               "long_name" : "New South Wales",
               "short_name" : "NSW",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "Australia",
               "short_name" : "AU",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "2000",
               "short_name" : "2000",
               "types" : [ "postal_code" ]
            }
         ],
         "formatted_address" : "Shop 309, Harbourside Shopping Centre, Darling Harbour NSW 2000, Australia",
         "geometry" : {
            "location" : {
               "lat" : -33.8721503,
               "lng" : 151.19873
            },
            "location_type" : "ROOFTOP",
            "viewport" : {
               "northeast" : {
                  "lat" : -33.87080131970851,
                  "lng" : 151.2000789802915
               },
               "southwest" : {
                  "lat" : -33.8734992802915,
                  "lng" : 151.1973810197085
               }
            }
         },
         "place_id" : "ChIJmcx0EzquEmsRuTAVSRuHKco",
         "types" : [
            "beauty_salon",
            "establishment",
            "hair_care",
            "health",
            "point_of_interest",
            "spa"
         ]
      }
   ],
   "status" : "OK"
}

Which causes the warnings:

Unknown type for enum com.google.maps.model.AddressType: 'beauty_salon'
Unknown type for enum com.google.maps.model.AddressType: 'hair_care'
Unknown type for enum com.google.maps.model.AddressType: 'spa'

Fixes?
Should the class GeocodingResult use AddressType[] or PlaceType[] ? or
Should the AddressType be extended to support the other types.

**Comment by apjanke** [comment]
Okay, I can reproduce both of these. Looks like new values need to be added to `AddressType`. (`PlaceType` is used in the Google Maps Places API; this is the Geocoding API, which uses `AddressType`).

PRs forthcoming.

**Comment by apjanke** [comment]
Okay, I've submitted #377 and #378, which I think will address all the warnings reported in this thread.

**Comment by laradabreo** [comment]
Thanks. Happy to change it and submit code also. If google are going to evolve AddressType is it worth maintaining this as a strongly typed class?
