### ISSUE TITLE
java.lang.NoClassDefFoundError: com/squareup/okhttp/MediaType

### ISSUE THREAD

**Issue by ivanpolak** [googlemaps/google-maps-services-java#281]
I am using google maps services library and I have an error message:

threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/squareup/okhttp/MediaType] with root cause
java.lang.ClassNotFoundException: com.squareup.okhttp.MediaType
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
    at com.google.maps.OkHttpRequestHandler.<clinit>(OkHttpRequestHandler.java:42)
    at com.google.maps.GeoApiContext.<init>(GeoApiContext.java:90)

libraries in my pom.xml file:

<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.8.1</version>
</dependency>
<dependency>
    <groupId>com.squareup.okio</groupId>
    <artifactId>okio</artifactId>
    <version>1.13.0</version>
</dependency>
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
    <version>3.8.1</version>
</dependency>
<dependency>
    <groupId>com.google.appengine</groupId>
    <artifactId>appengine-api-1.0-sdk</artifactId>
    <version>1.9.54</version>
</dependency>
<dependency>
    <groupId>com.google.maps</groupId>
    <artifactId>google-maps-services</artifactId>
    <version>0.1.20</version>
</dependency>

In Eclipse project everything is OK, MediaType class is in OKHTTP (com\squareup\okhttp\MediaType.class), tested with OKHTTP 2.7.5 and OKHTTP3 3.8.1

please, where is the problem, thanks!

**Comment by domesticmouse** [comment]
This library currently uses OkHttp version 2, not version 3. I'm in the process of upgrading currently.

**Comment by ivanpolak** [comment]
tested with OKHTTP 2.7.5 and OKHTTP3 3.8.1, so this problem is both version.

**Comment by domesticmouse** [comment]
Ok, first question, why are you attempting to specify all the dependencies directly in your pom.xml instead of using the capability of Maven to deal with dependency closure for you? Here's the dependency section for a test maven project I've got on hand:

```xml
<dependencies>
    <dependency>
      <groupId>com.google.maps</groupId>
      <artifactId>google-maps-services</artifactId>
      <version>0.1.20</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-nop</artifactId>
      <version>1.7.25</version>
    </dependency>
  </dependencies>
```

**Comment by ivanpolak** [comment]
sorry, everything is OK, it was my mistake in Eclipse settings. sorry.

**Comment by domesticmouse** [comment]
Cool, I'm glad everything is sorted!

**Comment by DeepaZirius** [comment]
Hi ivanpolak, can you explain me what settings you fixed in eclipse to solve this error. I am facing a similar situation, that during runtime NoClassDefFoundError occurs for CallBack class of okhttp version 2.7.5. I am including a jar file that has this okhttp2.7.5 as a dependency
