### ISSUE TITLE
version 0.1.21 doesn't include GeocodingApi class

### ISSUE THREAD

**Issue by cuquiwi** [googlemaps/google-maps-services-java#292]
Seems like this error happened for 0.1.19 too. #257 
I'm trying to import the GeocodingApi but seems that the class does not exist.
Rolling back to version 0.1.20 seems to work fine.

**Comment by domesticmouse** [comment]
Argh. I hate it when automated processes generate indeterminate results. I think this means I should roll a 0.1.22 before landing the okhttp3 upgrade. Thoughts?

**Comment by domesticmouse** [comment]
Version 0.1.22 should be out in a day or two, depending on propagation delays.

**Comment by domesticmouse** [comment]
Correction, it is out now, and I've confirmed it contains `GeocodingApi`. Sorry about the broken release. Thanks!
