### ISSUE TITLE
Accessing underlying query and response payloads?

### ISSUE THREAD

**Issue by apjanke** [googlemaps/google-maps-services-java#297]
Is there an easy way at the client level to access the encoded query URLs and the JSON or XML result payloads, and to deserialize a stored JSON response payload into response objects? The docs say that we should build a caching layer for this, and stashing the HTTP-level request and response strings in a key/value store would be a convenient way of building one, and in a somewhat language-independent manner.

It looks like I could build a stub server like the `LocalTestServerContext` in the tests does, at least for the deserializing, but I was hoping for a more direct way of doing it. And I don't see a way of grabbing the JSON from a response. (I'm not very familiar with this sort of service implementation; maybe I'm just not seeing how to do it.)

**Comment by domesticmouse** [comment]
I feel like this is a major restructure of the intent of the code base, possibly best approached by a fork. I'm happy to review proposed PRs on this issue, but it isn't something I'm going to implement.

Thoughts?

**Comment by apjanke** [comment]
That sounds reasonable. I'm still getting up to speed on Gson and how it works with POJOs and this API, so maybe an interface change to this library wouldn't be necessary after all. This Issue was more of a question about whether it was supported and I was overlooking something, and not a request for a change to do so.

I'll open a PR if I have a specific request of reasonable scope once I'm more familiar with this.
