### ISSUE TITLE
Android key restriction no working

### ISSUE THREAD

**Issue by powder366** [googlemaps/google-maps-services-java#307]
Not able to use Android key restriction with package name and SHA-1 certificate fingerprint.
Also see this answer from Daniel Nugent:

https://stackoverflow.com/questions/34516858/this-ip-site-or-mobile-application-is-not-authorized-to-use-this-api-key

Get error:

com.google.maps.errors.RequestDeniedException: This IP, site or mobile application is not authorized to use this API key. Request received from IP address 185.180.252.119, with empty referer

**Comment by domesticmouse** [comment]
The Web Services APIs are not designed to be used from mobile platforms, in this case Android. Please see [Making the most of the Google Maps Web Service APIs](https://maps-apis.googleblog.com/2016/09/making-most-of-google-maps-web-service.html) for a blog post where I explain the reasoning behind this. Thanks!
