### ISSUE TITLE
Prose style question: Oxford commas? Punctuation inside quotes?

### ISSUE THREAD

**Issue by apjanke** [googlemaps/google-maps-services-java#312]
A couple questions on prose style for this project, since I've seen some inconsistency in the Javadocs.

Do you use Oxford/serial commas?

And does structural punctuation go inside quotes? By this, I mean if you're quoting a string which itself doesn't contain a period or a comma, but it ends up next to a period or comma due to its place in a sentence, does the period/comma move inside the quote?

For example, this excerpt from the DirectionsStep Javadoc is inconsistent about whether the commas move inside the quotes: they do in the first paragraph, but not in the second.

> E.g. "Turn left at W. 4th St." The step not only describes the instruction but also contains distance and duration information relating to how this step relates to the following step. For example, a step denoted as "Merge onto I-80 West" may contain a duration of "37 miles" and "40 minutes," indicating that the next step is 37 miles/40 minutes from this step.
>
> When using the Directions API to search for transit directions, the steps array will include additional Transit Details in the form of a transitDetails array. If the directions include multiple modes of transportation, detailed directions will be provided for walking or driving steps in a steps array. For example, a walking step will include directions from the start and end locations: "Walk to Innes Ave & Fitch St". That step will include detailed walking directions for that route in the steps array, such as: "Head north-west", "Turn left onto Arelious Walker", and "Turn left onto Innes Ave".

**Comment by domesticmouse** [comment]
I'm not a trained tech writer, and this project has been through quite a few hands. I'd be very surprised if the JavaDoc prose was anywhere near consistent. If you are wanting to do a clean up run, I'll happily review Pull Requests. Thanks!

/cc @sarahmaddox

**Comment by sarahmaddox** [comment]
Hallo Andrew
Nice comment! As Brett says, the docs have been through a few hands and we haven't reviewed them for consistency in punctuation. Consistency is good. :)

We do recommend Oxford serial commas:
https://developers.google.com/style/commas

Our style guide recommends the American style of putting the punctuation marks inside the quotes:
https://developers.google.com/style/quotation-marks

I do admit though, that I find the latter hard to do when it disturbs the pattern that my internal parser expects. ;)

Cheers
Sarah

**Comment by apjanke** [comment]
Thanks folks! I'll follow that when doing future PRs.
