### ISSUE TITLE
Dangling sentence in RoadsApi.snappedSpeedLimits Javadoc

### ISSUE THREAD

**Issue by apjanke** [googlemaps/google-maps-services-java#313]
The [Javadoc for RoadsApi.snappedSpeedLimits](https://github.com/googlemaps/google-maps-services-java/blob/f04f11b9a7a466b4f053f3832d0a34010376b8df/src/main/java/com/google/maps/RoadsApi.java#L140-L141) ends in the middle of a sentence. I don't know what to complete it with, since I don't know what the intended use here is.

> Returns the result of snapping the provided points to roads and retrieving the speed limits. This is useful for interactive applications where you need to

**Comment by domesticmouse** [comment]
Hey @markmcd, you might want to do a late review on #316. Or I can just close this out. Thoughts?

**Comment by domesticmouse** [comment]
Closing this out.
