### ISSUE TITLE
java.net.ProxySelector is a restricted class

### ISSUE THREAD

**Issue by lmgagne** [googlemaps/google-maps-services-java#334]
Why is this error raised even when using the GaeRequestHandler.Builder()?
The error is raised while instantiating the GeoApiContext object.
FYI, we are using v0.2.2.

`GeoApiContext context = new GeoApiContext.Builder()
					.requestHandlerBuilder(new GaeRequestHandler.Builder())   
					.apiKey("AIza...")
					.build();`

**Comment by lmgagne** [comment]
I just tried using v0.2.1. It now complains about about a dependency and compatibility with Java 7.
Unable to stage app: Class file is Java 8 but max supported is Java 7: com/google/common/annotations/Beta.class in /Users/lmgagne/Documents/workspace/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1502841623063/staging-work/WEB-INF/lib/guava-22.0.jar

**Comment by wildcherrycandy** [comment]
Solution:

`new GeoApiContext.Builder(new GaeRequestHandler.Builder()).apiKey(googleApiKey).build();
`

You should parametrize `GeoApiContext.Builder` constructor via `GaeRequestHandler.Builder`

**Comment by domesticmouse** [comment]
@lmgagne v0.2.1 is known not to work with Java7, but v0.2.2 has a fix for the Guava dependency. So, please try v0.2.2, along with @wildcherrycandy's usage. Thanks!

**Comment by lmgagne** [comment]
Works like a charm. Thanks!
