### ISSUE TITLE
proxy authentication in GeoApiContext

### ISSUE THREAD

**Issue by lhomme-a** [googlemaps/google-maps-services-java#336]
GeoApiContext.Builder expose a proxy method and delegate to OkHttpClient.Builder.proxy.
But GeoApiContext.Builder have no any proxyAuthenticator method so this api cannot be use with an authenticated proxy.
Can you expose this method and delegate it to OkHttpClient.Builder.proxyAuthenticator ?

**Comment by domesticmouse** [comment]
Please feel free to submit a PR with your suggested change, thanks!

**Comment by Falydoor** [comment]
Any idea when this feature will be pushed to maven (with version 0.2.3 I guess) ?

Thank you !

**Comment by domesticmouse** [comment]
@Falydoor it is now in the process of rolling out. Check back in a couple of hours.
