### ISSUE TITLE
Proxy Selector is a restricted class

### ISSUE THREAD

**Issue by engeeaitch** [googlemaps/google-maps-services-java#344]
Hi - I have upgraded to version 0.2.2 of the library from 0.1.20.  I am running my app on Google App Engine.
I setup the context as follows:
`    static final GeoApiContext context = new GeoApiContext.Builder()
                    .apiKey(MyGoogleConstants.MAPS_API_KEY)
                    .build();`

When I run this code, I get the following error:

> java.lang.NoClassDefFoundError: java.net.ProxySelector is a restricted class. Please see the Google  App Engine developer's guide for more details.

>
which occurs at line 469 of OkHttpClient.java

Can anyone help please?

**Comment by lmgagne** [comment]
See #334. Are you using this library on GAE by any chance?

**Comment by engeeaitch** [comment]
Thanks - I missed that you need to create a new GaeRequestHandler.  All OK now.
