### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by baltar** [googlemaps/google-maps-services-java#348]
Hi, I recently crossed the 64k max. method DEX file limit. After some digging, I discovered that this library, which the app depends on, added a huge amount of methods due to its dependency on Guava. After searching around here, I found #331 which mentions 

> as has been said many times please don't use google-maps-services-java with android.

However, I haven't seen this advice before. In #309, a [link](https://maps-apis.googleblog.com/2016/09/making-most-of-google-maps-web-service.html) is mentioned "for an explanation as to why you shouldn't be calling our Web Services directly from your mobile application." 

But even therein, it says
> but when you find that your use case requires data that is only available via the Google Maps APIs Web Services, such as Elevation, then using these client libraries is the best way forward.

Which I understand as "it's more inconvenient for cases covered by the proper Android libs, but still ok to use". Otherwise it should never be ok to use them, right? 

Anyway, it would be most helpful to include the recommendation to not use this on Android prominently in the Description section of the README. And probably also on [this page](https://developers.google.com/maps/web-services/client-library).

**Comment by cavarzan** [comment]
@baltar using proguard should reduce the method count by removing unused references

**Comment by roman-ku** [comment]
I don't understand why I can't use this on Android. Because Google doesn't want to have my own API key stolen? Is that it? Is that the only reason?

I am a solo dev working on a transit app, I can't afford to host a server let alone do the coding for a server and an app.

>[However, I must point out that this library is not designed to be used from Android. Please see this for an explanation as to why you shouldn't be calling our Web Services directly from your mobile application.](https://github.com/googlemaps/google-maps-services-java/issues/309#issuecomment-320785535)

The blog post doesn't really have much of an explanation.

**Comment by domesticmouse** [comment]
While I empathize with your situation as a sole developer, where you are attempting to rationally spend your time on user facing features that will gain you that all important product market fit, on your way to being able to grow your company and all that.

It is worth viewing an API Key as akin to a credit card number. Having your API Key stolen opens you up to attackers abusing your API Key and costing you real money.

I also empathize with your claim that running a server as a proxy is expensive and hard. While this may have been true in the past, it really isn't true these days. You can run Google App Engine instances in Java or Kotlin, so you can re-use your Android honed language skills, while being light on the budget as App Engine comes with free usage quota and a server-less style only on while in use model. 

I have built google-maps-services-java to work both in standard Java server environments, as well as Google App Engine to specifically empower this use case.

**Comment by domesticmouse** [comment]
Updated the project README.md to make non-support of Android more specific.

**Comment by baltar** [comment]
Thanks @domesticmouse 

@roman-ku please note that you don't need to use a proxy server; if you can use the standard Android libraries for accessing the services (e.g. com.google.android.gms:play-services-maps, com.google.android.gms:play-services-places etc.), you can create an additional API key for that and restrict it to specific Android applications (identified by package name + a fingerprint which you'd need to obtain first, but the console for the running the app will tell you how to do that if you haven't added them already). That way, even if someone extracts your API keys from the app, they'll not be able to use it.
