### ISSUE TITLE
Getting stack trace in Google Apps Engine

### ISSUE THREAD

**Issue by Ghokuls** [googlemaps/google-maps-services-java#353]
I used Google Client Library in App Engine and received the error shown in the attachment. Request your advise on this.

[Exception Trace1.txt](https://github.com/googlemaps/google-maps-services-java/files/1350194/Exception.Trace1.txt)
[Exception Trace2.txt](https://github.com/googlemaps/google-maps-services-java/files/1350195/Exception.Trace2.txt)
[Exception Trace3.txt](https://github.com/googlemaps/google-maps-services-java/files/1350193/Exception.Trace3.txt)

**Comment by domesticmouse** [comment]
Looks like the Simple Logging for Java adaptor you are using is attempting to create a thread, which is disallowed in Google App Engine standard.

**Comment by Ghokuls** [comment]
It's not what I'm using. It was there  in the Google Client Library.
What can be done to get rid of this error?

**Comment by Ghokuls** [comment]
I disabled the logging that's there in the below Library files and able to get the results. Thanks for your time.
GaeRequestHandler.java
SafeEnumAdapter.java
GaePendingResult.java
