### ISSUE TITLE
Guava conflict: Firebase Admin SDK Runtime exception

### ISSUE THREAD

**Issue by ayyrk27** [googlemaps/google-maps-services-java#355]
**I have a working Java Firebase Admin SDK application.** 

**It has this in build.gradle:**
compile group: 'com.google.firebase', name: 'firebase-admin', version: '5.3.1'

**When I add these two lines:**
compile group: 'com.google.maps', name: 'google-maps-services', version: '0.2.3'
compile 'org.slf4j:slf4j-nop:1.7.25'

**I get this exception:**
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
        at com.google.firebase.FirebaseApp.checkNotDeleted(FirebaseApp.java:317)
        at com.google.firebase.FirebaseApp.getOptions(FirebaseApp.java:263)
        at com.google.firebase.database.FirebaseDatabase.getInstance(FirebaseDatabase.java:75)

So - I am having trouble including google-maps-services-java in my project..  Some searching points to a  Guava conflict.  Any ideas on how to sort this out?

**Comment by domesticmouse** [comment]
In the next revision we have removed the guava dependency by inlining the rate limiter. I'll roll up a release shortly.

**Comment by MartynClark** [comment]
I seem to be experiencing the same sort of issue with NoSuchMethodError

java.lang.NoSuchMethodError: com.google.common.util.concurrent.RateLimiter.acquire()D

**Comment by domesticmouse** [comment]
I've rolled [Version 0.2.4](https://github.com/googlemaps/google-maps-services-java/releases/tag/v0.2.4) which includes the inlined Rate Limiter code. This should be up on the maven central in the next handful of hours. Give or take.

**Comment by ayyrk27** [comment]
0.2.4 fixed things for me. Thanks very much!

**Comment by domesticmouse** [comment]
@ayyrk27 glad to hear =)
