### ISSUE TITLE
Cannot Change Language Parameter.

### ISSUE THREAD

**Issue by DellyArts** [googlemaps/google-maps-services-java#359]
There is no option for geocode, reverse geocode location in desired language.
According to the Google Maps API Guide, there is optional parameters in a geocoding request. One of them is language parameter.

**Comment by domesticmouse** [comment]
Please see the JavaDoc for [GeocodingApiRequest#language](https://googlemaps.github.io/google-maps-services-java/v0.2.3/javadoc/com/google/maps/GeocodingApiRequest.html#language-java.lang.String-)

**Comment by DellyArts** [comment]
Whoa, i didn't know that class. Normally i use direct GeocodingResult without assigning to that class first.

Now it's working, thanks for your help @domesticmouse  !  ;-)

**Comment by domesticmouse** [comment]
Glad to be able to help! =)
