### ISSUE TITLE
Error while using client id and cryptographic key in Geocoding API

### ISSUE THREAD

**Issue by madhanmallow** [googlemaps/google-maps-services-java#361]
In my app, I'm using Geocoding API to fetch address from latitude and longitude. I have premium plan license. When I use the client id and cryptographic key to create an instance of the GeoApiContext, I receive the below error.

java.lang.IllegalStateException: java.lang.CloneNotSupportedException
                                                                            at com.google.maps.internal.UrlSigner.getMac(UrlSigner.java:61)
                                                                            at com.google.maps.internal.UrlSigner.getSignature(UrlSigner.java:52)
                                                                            at com.google.maps.GeoApiContext.getWithPath(GeoApiContext.java:248)
                                                                            at com.google.maps.GeoApiContext.get(GeoApiContext.java:144)
                                                                            at com.google.maps.PendingResultBase.makeRequest(PendingResultBase.java:80)
                                                                            at com.google.maps.PendingResultBase.await(PendingResultBase.java:55)

How to resolve this? or What is the correct way to implement?

My implementation is:

    GeoApiContext geoApiContext = new GeoApiContext.Builder()
                       .enterpriseCredentials(“client-id”,”secret-key”)
            .connectTimeout(AppConstants.GOOGLE_API_TIMEOUT, TimeUnit.SECONDS)
            .readTimeout(AppConstants.GOOGLE_API_TIMEOUT, TimeUnit.SECONDS)
            .build();

**Comment by domesticmouse** [comment]
I'm really unsure what is going wrong for you. Here is some test code I've just run up, and it works fine:

```
package com.domesticmouse;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.maps.GeoApiContext;
import com.google.maps.GeocodingApi;
import com.google.maps.model.GeocodingResult;
import java.util.concurrent.TimeUnit;

public class Main {

  public static void main(String[] args) throws Exception {

    GeoApiContext geoApiContext = new GeoApiContext.Builder()
        .enterpriseCredentials("client-id","client-secret")
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .build();

    GeocodingResult[] results =  GeocodingApi.geocode(geoApiContext,
        "1600 Amphitheatre Parkway Mountain View, CA 94043").await();
    Gson gson = new GsonBuilder().setPrettyPrinting().create();
    System.out.println(gson.toJson(results[0].addressComponents));
  }
}
```

**Comment by nertzy** [comment]
We are using the static map image API and run into a similar issue sporadically. We have the same stacktrace at the top (UrlSigner throwing `CloneNotSupportedException: null` from within getMac()).

We're running on macOS High Sierra and the problem generally goes away if we retry. I don't have a stacktrace handy because right now it's not happening for me.

**Comment by domesticmouse** [comment]
I'm thoroughly confused.

**Comment by nertzy** [comment]
One more bit of detail: We have seen this when running our application in IntelliJ, but we haven't been seeing it when running via Gradle on the command-line (yet). 

Another clue: we are using the [Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy](http://www.oracle.com/technetwork/java/javase/downloads/jce-6-download-429243.html).

**Comment by domesticmouse** [comment]
One investigation that would be interesting would be to insert a try/catch/retry around the `PendingResultBase.makeRequest(...)` level, and see if that makes the issue go away...

**Comment by domesticmouse** [comment]
Closing this out as I can't see what this library can do in the face of a randomly failing JCE.
