### ISSUE TITLE
Cache - Class model not implement java.io.Serializable

### ISSUE THREAD

**Issue by lfochi** [googlemaps/google-maps-services-java#366]
If you want implements a Cache with the same response model is not posible because it does not implement java.io.Serializable

**Comment by domesticmouse** [comment]
Please feel free to create a pull request that adds Serializable to the response model. Thanks!

**Comment by domesticmouse** [comment]
This will show up in [v0.2.5](https://github.com/googlemaps/google-maps-services-java/releases/tag/v0.2.5)

**Comment by lfochi** [comment]
Thanks @domesticmouse !
