### ISSUE TITLE
Unknown address component type 'postal_code_prefix'

### ISSUE THREAD

**Issue by farukzahra** [googlemaps/google-maps-services-java#37]
Create this enum type.

**Comment by aldenquimby** [comment]
any update here? i'm still seeing this `Unknown type for enum com.google.maps.model.AddressComponentType: 'postal_code_prefix'` using version `0.1.6` from maven central

**Comment by markmcd** [comment]
I've done that for you now. v0.1.7 has just been pushed to Maven Central and contains a few of the recent address component type enum PRs.

**Comment by aldenquimby** [comment]
great, thanks!

**Comment by jschuttler** [comment]
I'm having this issue in v0.1.7 with postal_code_suffix, is this working properly?
