### ISSUE TITLE
Null Island should be (0 N/S, 0 E/W)?

### ISSUE THREAD

**Issue by apjanke** [googlemaps/google-maps-services-java#383]
So, I did a Geocoding API lookup for "Null Island" and it got me the following off of Ireland:

```
$ ./bin/gmsj-cli geocode "Null Island"
Results length: 1
Result 0:
Formatted Address: Cappanoole, Mahon, Machain, Co. Cork, Ireland
Types: route
PARTIAL MATCH
PlaceId: ChIJ6_1tl9WEREgRHKS06Ptij4o
Geom: (51.887425, -8.396152) GEOMETRIC_CENTER: [(51.889,-8.395) / (51.887,-8.397)]
Address:
  Mahon [neighborhood / political]
  Machain [locality / political]
  County Cork [administrative_area_level_1 / political]
  IE ("Ireland") [country / political]
```

I think that "Null Island" should resolve to (0 N/S, 0 E/W), since it's an [established joke or map-maker's shorthand](https://en.wikipedia.org/wiki/Null_Island).

How can I report this up to the Google Maps API folks? (I tried doing this manually using maps.google.com in the browser, and it didn't provide a useful interface for doing so; just an interface for editing pins around my IRL location.)

Sorry if this is the wrong place to report this.

**Comment by domesticmouse** [comment]
Please raise an issue on our Google Maps APIs public issue tracker. Here is the component for Geocoding: https://issuetracker.google.com/issues/new?component=188871&template=788907

I'd suggest you pull out the API call that is being made, minus the API Key, for the bug report.

**Comment by apjanke** [comment]
Looks like they're not tracking locations in this area yet. Oh well. :)

<img width="968" alt="screen shot 2018-07-18 at 9 16 34 pm" src="https://user-images.githubusercontent.com/2618447/42915780-f172cee2-8acf-11e8-9e6f-651d7b0c43b4.png">

**Comment by domesticmouse** [comment]
Did you raise an Issue tracker bug? If yes, I can bounce it past the API team and see who I need to hassle. =)

**Comment by apjanke** [comment]
No, the issue tracker template said they didn't want to hear it. :)

> IMPORTANT:  If you are seeing an incorrect location from the geocoder,
please go to http://maps.google.com and enter your query there, and then
select to "report an issue" to ensure it gets routed appropriately.  Do not
file the issue here.

**Comment by domesticmouse** [comment]
I've done some digging, and yes 0,0 is locked down due to the Null Island problem. Thanks!
