### ISSUE TITLE
Does not show Cambodia language on google maps android

### ISSUE THREAD

**Issue by Chomroeun** [googlemaps/google-maps-services-java#390]
I want to show Khmer Language on Google maps but it does not show. I try with

`String languageToLoad = "hl=km";// for Cambodia language 
    Locale locale = new Locale(languageToLoad);
    Locale.setDefault(locale);
    Configuration config = new Configuration();
    config.locale = locale;
    getBaseContext().getResources().updateConfiguration(config,
            getBaseContext().getResources().getDisplayMetrics());`

**Comment by Chomroeun** [comment]
<img width="786" alt="screen shot 2017-11-29 at 4 58 55 pm" src="https://user-images.githubusercontent.com/9971653/33422768-4f4b3640-d5e9-11e7-9378-88b8a11230aa.png">

**Comment by domesticmouse** [comment]
I'm unsure what the above code has to go with Google Maps Services client library. This client library doesn't render map tiles.
