### ISSUE TITLE
LatLng isn't as complete as the Android version

### ISSUE THREAD

**Issue by feinstein** [googlemaps/google-maps-services-java#391]
`LatLng` in the Android API has the following constructor, which is safer:

    public LatLng(double var1, double var3) {
        if(-180.0D <= var3 && var3 < 180.0D) {
            this.longitude = var3;
        } else {
            this.longitude = ((var3 - 180.0D) % 360.0D + 360.0D) % 360.0D - 180.0D;
        }

        this.latitude = Math.max(-90.0D, Math.min(90.0D, var1));
    }

whereas this library's is just:

    public LatLng(double lat, double lng) {
        this.lat = lat;
        this.lng = lng;
    }

Maybe you guys could make a `core -java` API where the Android and the pure Java could use and don't have duplicated code?

**Comment by domesticmouse** [comment]
I understand the desire here, however the use of this `LatLng` class is purely for transferring data to and from the various [Google Maps APIs Web Services](https://developers.google.com/maps/web-services/overview) API endpoints. 

We do minor sanity checks on things that will always fail on the API endpoints, but apart from that I'd rather not put further intelligence into this library.
