### ISSUE TITLE
Bounds should mirror Android LatLngBounds

### ISSUE THREAD

**Issue by feinstein** [googlemaps/google-maps-services-java#392]
Simply put, the Android version of the `LatLngBounds` is a lot more complete and should be included in this library, and `Bounds` should be marked as `@deprecated`.

**Comment by domesticmouse** [comment]
While I understand the desire to have more complete functionality, the model classes of this library are purely data transfer objects to capture the results of the API calls. You will need to use other libraries to do geographic computations like includes and excludes. Sorry!
