### ISSUE TITLE
InvalidRequestException when calling .await() inside a while statement

### ISSUE THREAD

**Issue by chufaca** [googlemaps/google-maps-services-java#399]
Hello, 
I am getting the exception when calling the API inside the loop. It must be thread related, because if I use a Thread.sleep(2000) it works just fine.
I am inside a loop, as I want to colect all the items (regardless the page), so I'm calling the API with the nextPageToken value.

Code:
```
while (!StringUtils.isEmpty(nextPageToken)) {
   NearbySearchRequest nearbySearchRequest = PlacesApi.nearbySearchQuery(this.contextApiKey, 
      location).pageToken(nextPageToken);
   PlacesSearchResponse newPlacesSearchResponse = nearbySearchRequest.await();
   nextPageToken = newPlacesSearchResponse.nextPageToken;
}
```

The error:
**com.google.maps.errors.InvalidRequestException: null
	at com.google.maps.errors.ApiException.from(ApiException.java:42)
	at com.google.maps.NearbySearchRequest$Response.getError(NearbySearchRequest.java:226)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:287)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:176)
	at com.google.maps.PendingResultBase.await(PendingResultBase.java:56)**

Thanks

**Comment by aaryn101** [comment]
I was also encountering InvalidRequestExceptions when getting subsequent pages of a PlacesSearchResponse. Then I found [this](https://developers.google.com/places/web-service/search#PlaceSearchPaging).

And more specifically: 
>  There is a short delay between when a next_page_token is issued, and when it will become valid. Requesting the next page before it is available will return an INVALID_REQUEST response. Retrying the request with the same next_page_token will return the next page of results.

**Comment by domesticmouse** [comment]
@chufaca let me know if @aaryn101's answer doesn't get you out of trouble. Thanks!
