### ISSUE TITLE
Google Maps JavaScript Api

### ISSUE THREAD

**Issue by 8Ozymandias** [googlemaps/google-maps-services-java#403]
I have made use of the current-place and autocomplete code samples (Java, NOT JavaScript), however in order to get use of real time user input for directions I have to make use of the Google Maps JavaScript Api.  

However, I've been using Android Studio to build the app and Android Studio doesn't seem to have the functionality to utilize JavaScript. Or does it? Going through the IDE, I see support for stuff like C++ and Kotlin. 

I wanted to ask, how do I make use of the Google Maps JavaScript Api ([Directions & Autocomplete](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-directions)) with the already set of Java code I have in Android Studio.

Please bare with me, I am a beginner with all this and I am trying to get better. 

Yours respectfully, Ozymandias

**Comment by domesticmouse** [comment]
Hey Ozymandias, not being an Android developer (this library is designed to be used in Java server-side applications), I can't make any solid recommendations.

With that said, there looks to be some reasonable suggestions [here](https://www.google.com.au/search?q=how+to+use+javascript+in+android+application+example). Thanks!
