### ISSUE TITLE
Adding widgets on a GoogleMap 

### ISSUE THREAD

**Issue by faresgh4** [googlemaps/google-maps-services-java#408]
**Hi i recently made an application with a googlemap map  , but i didn't find how to add widgets on the map (Buttons principaly .......) 

please if someone can help me with a java code or xml , it would be wonderful !!! 
thank you !!!!**

**Comment by domesticmouse** [comment]
The best place to ask these style of questions is on [StackOverflow](https://stackoverflow.com/questions/tagged/google-maps-android-api-2)
