### ISSUE TITLE
Get error when using client id & secret in GeolocationApi

### ISSUE THREAD

**Issue by auxor** [googlemaps/google-maps-services-java#411]
I got the following error. It's blocked by [supportsClientId(false)](https://github.com/googlemaps/google-maps-services-java/blob/0301b9f6283389ba06bb23d5c642607d2a09dbb1/src/main/java/com/google/maps/GeolocationApi.java#L41). Why it does't support client id in GeolocationApi? 

onError java.lang.IllegalStateException: API does not support client ID & secret - you must provide a key

04-03 13:53:03.274  1545  1545 E GeoLocationWrapper: onError java.lang.IllegalStateException: API does not support client ID & secret - you must provide a key
04-03 13:53:03.274  1545  1545 E GeoLocationWrapper: 	at com.google.maps.a.a(GeoApiContext.java:277)
04-03 13:53:03.274  1545  1545 E GeoLocationWrapper: 	at com.google.maps.a.b(GeoApiContext.java:202)
04-03 13:53:03.274  1545  1545 E GeoLocationWrapper: 	at com.google.maps.h.b(PendingResultBase.java:82)
04-03 13:53:03.274  1545  1545 E GeoLocationWrapper: 	at com.google.maps.h.c(PendingResultBase.java:55)

**Comment by domesticmouse** [comment]
If you look at the documentation for [Geolocation API](https://developers.google.com/maps/documentation/geolocation/intro) you will see it doesn't support the old style client id. It only supports  using API Keys.
