### ISSUE TITLE
Add library to enum AddressType

### ISSUE THREAD

**Issue by Makabane** [googlemaps/google-maps-services-java#412]
Hi, I got this warning : 
`Unknown type for enum com.google.maps.model.AddressType: 'library'`
when I request 
> https://maps.googleapis.com/maps/api/geocode/json?key=[...]&address=80+FR
with google-maps-services-0.1.15.jar

**Comment by domesticmouse** [comment]
This will be in the next release, which should go out shortly. Thanks!
