### ISSUE TITLE
instead of calling Google Geocode services for testing can we able to virtualize it using tools?

### ISSUE THREAD

**Issue by nponmani** [googlemaps/google-maps-services-java#416]

**Comment by domesticmouse** [comment]
I suggest you test at a layer above this client library, injecting this library as a run time dependency. There should be no need for you to test this library in your unit tests.

**Comment by nponmani** [comment]
We are executing performance testing by virtualize the Geocode. We need to provide the virtualize host instead of maps.googleapis.com host name.

**Comment by domesticmouse** [comment]
I understand your requirement, however it isn't one we are prioritising supporting. Sorry!
