### ISSUE TITLE
How to specify the language for the response data?

### ISSUE THREAD

**Issue by timothyBrake** [googlemaps/google-maps-services-java#417]
E.g. the response of any request should always be in a specific language e.g. English, even if the request contains the French city name like Bruxelles, I would like "Brussels" as the response.

Is this possible?

Thanks,
T

**Comment by domesticmouse** [comment]
All the requests have a `language` parameter.

**Comment by timothyBrake** [comment]
Yes I have noticed the Google maps API has a language and a region parameter but none seem to work properly. There are 2 questions here:

-  how to specify the language in the Java API? 

`GeoApiContext.Builder().language(String language) would be great but haven't found it.
 GeoApiContext.Builder().param(String key, String value) would be great but haven't found it.`

-  how to always get the correct address in the language specified? Here is the issue in more detail:
I always get the actual Dutch version but not the English version.  
Tested it in Chrome directly:
Example 1:
```
GIVEN 
  Language French
 Google Chrome ONLY set to use English language
WHEN
   https://maps.googleapis.com/maps/api/geocode/json?key=[APIKEY]&address=parvis+st+gudule+5+-+1000+Brussels%2C+Belgium+%28Belgium%29&language=fr
THEN
    expect Bruxelles BUT returns "Brussel" Flemish version.
```
<img width="777" alt="screen shot 2018-04-24 at 09 28 15" src="https://user-images.githubusercontent.com/9657088/39172381-e199a8a4-47a1-11e8-8bd5-c27cf035f1ce.png">

Example2:
```
GIVEN 
  Language English
 Google Chrome ONLY set to use English language
WHEN
   https://maps.googleapis.com/maps/api/geocode/json?key=[APIKEY]&address=parvis+st+gudule+5+-+1000+Brussels%2C+Belgium+%28Belgium%29&language=en
THEN
    expect Brussels BUT returns "Brussel" Flemish version.
```
<img width="880" alt="screen shot 2018-04-24 at 09 30 35" src="https://user-images.githubusercontent.com/9657088/39172474-2cb191d0-47a2-11e8-99c0-bacc181bd6d9.png">
The country IS translated correctly but not the city.

I'm thinking this needs to be done in another way? Any help is welcome.

**Comment by domesticmouse** [comment]
Here is the [DirectionsApiRequest language parameter Javadoc](https://googlemaps.github.io/google-maps-services-java/v0.2.7/javadoc/com/google/maps/DirectionsApiRequest.html#language-java.lang.String-). That's how you pass through the language to the web services.

**Comment by domesticmouse** [comment]
That sounds like a bug. Can you raise it on the appropriate web service [bug tracker](https://developers.google.com/maps/support/#issue_tracker)?
