### ISSUE TITLE
profile_photo_url field for Review

### ISSUE THREAD

**Issue by proft** [googlemaps/google-maps-services-java#418]
Hi!
I use the lastest version ``0.2.7`` but I can't get ``profile_photo_url`` field for ``Review`` model.
According to https://developers.google.com/places/web-service/details there is ``profile_photo_url`` field.
Android Studio (3.1.2) just highlight  ``profile_photo_url`` field with red line.

Is it possible to get ``profile_photo_url`` field for ``Review`` model?

**Comment by apjanke** [comment]
Fixed in #432.

In the Java object model, it's [`profilePhotoUrl`](https://github.com/googlemaps/google-maps-services-java/blob/78f52824567b64ba59a71960f79dd2800777300b/src/main/java/com/google/maps/model/PlaceDetails.java#L163-L164), not `profile_photo_url`.

**Comment by proft** [comment]
Thanks for fix.
How I can import it to my project? There is 0.2.8 version in maven but it doesn't have profilePhotoUrl field.

**Comment by proft** [comment]
I managed it ;)

```
    implementation('com.github.googlemaps:google-maps-services-java:7c10cd48a4a7d157da1f70b2bbcaf2438640a6da') {
        exclude module: 'joda-time'
    }
```
