### ISSUE TITLE
Don't use joda-time.

### ISSUE THREAD

**Issue by ptahchiev** [googlemaps/google-maps-services-java#420]
Do you really need to use joda-time? How about plain old `java.time.LocalDateTime`? If you really need to use it, then please mark the dependency as optional and do some checks in your code if the client has it included.

**Comment by domesticmouse** [comment]
Currently the return types include times marked up as `joda-time` types. When this library was written, `java.time.LocalDateTime` was still quite new, and the requiredment for Java 1.8 was unacceptable to many users. 

With that said, I'm happy to accept a PR that migrates all usage of joda-time across to Java 1.8 types. Thanks!

**Comment by domesticmouse** [comment]
This has an active PR: https://github.com/googlemaps/google-maps-services-java/pull/421 

I am holiding this change for six months because of: https://github.com/googlemaps/google-maps-services-java/issues/422

**Comment by domesticmouse** [comment]
I've just landed https://github.com/googlemaps/google-maps-services-java/pull/421
I'll push this out in a new release shortly
