### ISSUE TITLE
StaticMapsRequest.toUrlValue breaks in 1.7

### ISSUE THREAD

**Issue by KiriyaKeat** [googlemaps/google-maps-services-java#422]
String.join() was only introduced as part of Java 1.8 and as such will break anyone running Java 1.7.

Does the project intend on continuing support for 1.7 or will it only be be supporting 1.8?

**Comment by KiriyaKeat** [comment]
Would it be possible to replace the String.join method with the following private method? 
-      return String.join("|", urlParts);
+      return join("|", urlParts);
+    }
+  }
+
+  private String join(String seperator, List<String> urlParts) {
+    StringWriter sw = new StringWriter();
+    if (urlParts != null && !urlParts.isEmpty()) {
+      Iterator<String> it = urlParts.iterator();
+      seperator = seperator != null ? seperator : "|";
+      if (it.hasNext()) {
+        sw.append(it.next());
+        while (it.hasNext()) {
+          sw.append(seperator); 
+          sw.append(it.next());
+        }
+      }
     }
+    return sw.toString();
   }

**Comment by domesticmouse** [comment]
I'm curious what platform you are on that still requires Java 1.7 support. Oracle end of life'd 1.7 back in 2015.

**Comment by KiriyaKeat** [comment]
Yeah I know, will have to upgrade one day. 
I'm still running Jboss in the process of migrating to Wildfly. 

On the code page it states 1.7 or later, so if you don't intend on supporting 1.7 then it should be updated to 1.8 or later.

**Comment by domesticmouse** [comment]
Yeah, good call. I have out standing patches that migrate the codebase from using joda-time to the Java 1.8 included version of same. I'm trying to guess how many people are still on 1.7 and for how long. I'm happy to push back on Java 1.8 for six months if that helps you?

**Comment by KiriyaKeat** [comment]
Yeah, that would be great. I just have to go through all the DB index references and a lot of testing on Wildfly.

**Comment by domesticmouse** [comment]
Btw, I believe this specific issue was just fixed by @astachelek in https://github.com/googlemaps/google-maps-services-java/commit/947d21b095e6ef58a3b606b1815d87577f6e8ac9

This will be in the next release.

**Comment by domesticmouse** [comment]
@KiriyaKeat Just checking in on how you are situated for a bump to minimum of 1.8 next month?

**Comment by KiriyaKeat** [comment]
Hi Brett,

Thanks for checking.
We are all good to upgrade.

Kiriya

**Comment by domesticmouse** [comment]
Thanks for the update @KiriyaKeat, we've uplifted to Java 1.8 minimum now.
