### ISSUE TITLE
Warning: Unknown type for enum com.google.maps.model.AddressType: 'car_wash'

### ISSUE THREAD

**Issue by martijnvanderwoud** [googlemaps/google-maps-services-java#425]
It looks an entry for "car_wash" needs to be added to the AddressType enum

**Comment by apjanke** [comment]
Fixed in https://github.com/googlemaps/google-maps-services-java/commit/28fe395b00673b39681d39e0f2bf5ed99f1dcd63.

**Comment by domesticmouse** [comment]
This is included in Version 0.2.9, which is rolling out now.
