### ISSUE TITLE
Unknown type for enum com.google.maps.model.AddressType: 'hardware_store'

### ISSUE THREAD

**Issue by Meilarium** [googlemaps/google-maps-services-java#426]
When i try to use : GeocodingApi.geocode(geoApiContext, "kiloutou, Houilles").await();
This error is raised : Unknown type for enum com.google.maps.model.AddressType: 'hardware_store'
Version : 0.2.7
Thanks for an update ?

**Comment by apjanke** [comment]
Fixed in https://github.com/googlemaps/google-maps-services-java/commit/28fe395b00673b39681d39e0f2bf5ed99f1dcd63.

**Comment by domesticmouse** [comment]
Actually, I'll close these out when I release

**Comment by domesticmouse** [comment]
This is included in Version 0.2.9, which is rolling out now.
