### ISSUE TITLE
NearbySearchRequest only returning results for a single place type

### ISSUE THREAD

**Issue by dvankley** [googlemaps/google-maps-services-java#430]
I haven't had a problem with this until recently, but it seems that the Google Places API is only returning results for the first place type set in the request.

To be more specific, I'm setting multiple `PlaceType`s [here](https://github.com/googlemaps/google-maps-services-java/blob/9b54a6ff5bef9afb4ae185f6f78c28ea69bf806e/src/main/java/com/google/maps/NearbySearchRequest.java#L169), but I only get results back for the first type in the string. This doesn't appear to be a problem with this library because I see the same issue with older versions of the library, but thought someone here might have some insight on if I'm doing something wrong or if there's an actual bug/change in the API. Thanks.

**Comment by psmagin** [comment]
According to [guide](https://developers.google.com/places/web-service/search#PlaceSearchRequests):
Only one type may be specified (if more than one type is provided, all types following the first entry are ignored)
So, deprecated method?

**Comment by dvankley** [comment]
@psmagin good call, that looks like it.
Yeah, that method should be deprecated.
