### ISSUE TITLE
PlaceDetails.types should be of class AddressType[] not String[]

### ISSUE THREAD

**Issue by shsachin** [googlemaps/google-maps-services-java#434]
[PlaceDetails.java](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/model/PlaceDetails.java) defines 
     `public String[] types;`
[GeocodingResult.java](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/model/GeocodingResult.java) defines
     `public AddressType[] types;`

This looks inconsistent.

**Comment by apjanke** [comment]
I agree. The [Place Details API documentation](https://developers.google.com/places/web-service/details) refers to types as being one of the supported Address Types, and [links to the list we use for AddressType](https://developers.google.com/places/web-service/supported_types#table2).
