### ISSUE TITLE
Inappropriate method name : baseUrlForTesting can be used for Google Maps China

### ISSUE THREAD

**Issue by shsachin** [googlemaps/google-maps-services-java#435]
[GeoApiContext.java](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/GeoApiContext.java) names a method as baseUrlForTesting
`Builder baseUrlForTesting(String baseUrl)`
As per [Google Maps China documentation](https://developers.google.com/maps/documentation/javascript/localization#GoogleMapsChina),
this method can also be used for, overriding base Url.
Please consider method name change, or provide overridden method, or mark this method as deprecated and need to improve documentation comment.

**Comment by apjanke** [comment]
I agree. Here's a PR that replaces it with a usage-neutral `baseUrlOverride(...)` method: #471.
