### ISSUE TITLE
Value-based toString() for model objects?

### ISSUE THREAD

**Issue by apjanke** [googlemaps/google-maps-services-java#450]
Would you be interested in a PR that added value-based `toString()` implementations to the classes in `com.google.maps.model`?

Right now, most of them use the default `java.lang.Object` `toString()`, which returns something like `<ClassName>@<hashCode>`, and since they use the default `hashCode()`, that gives a value based on object identity.

These are value classes, so their content is probably more important than object identity. For example, `Bounds` could be represented as `[(<ne-lat>,<ne-lng>),(<sw-lat>,<sw-lng>)]` instead of `Bounds@8713648763`.

This could be useful for incorporating objects into log messages, or for interactive use in scripting environments like Matlab or Jython. Particularly for log messages: object identity is not significant outside of the current process, so the default `Object.toString()` representation is probably not very useful in logs.

**Comment by domesticmouse** [comment]
Yup, that sounds reasonable to me.

**Comment by apjanke** [comment]
Here's what I'm thinking: #452. If that looks good to you, I'll add some tests to it.

**Comment by domesticmouse** [comment]
Yup, it looks good to me. After adding tests, please make sure the formatting is correct with:

```(bash)
$ ./gradlew googleJavaFormat
```

Thanks!

**Comment by apjanke** [comment]
> $ ./gradlew googleJavaFormat

Thought I already did that! Running it locally is showing no changes to do.

```
[~/local/repos/google-maps-services-java]
$ ./gradlew googleJavaFormat                                                                                                                                        model-value-based-toStrings ✭

BUILD SUCCESSFUL in 0s
[~/local/repos/google-maps-services-java]
$ git diff |cat                                                                                                                                                     model-value-based-toStrings ✭
[~/local/repos/google-maps-services-java]
$ git status                                                                                                                                                        model-value-based-toStrings ✭
On branch model-value-based-toStrings
Your branch is up to date with 'origin/model-value-based-toStrings'.

nothing to commit, working tree clean
```

**Comment by domesticmouse** [comment]
All good, I can't check validity of a PR until after I merge it =)

**Comment by domesticmouse** [comment]
Ping me when you have added tests and I'll merge. Thanks!

**Comment by apjanke** [comment]
Will probably be tomorrow; it's 1:00 AM out here right now. :)

You're welcome!

**Comment by domesticmouse** [comment]
Sleep is good, i'll still be here tomorrow =)

**Comment by apjanke** [comment]
Cool, thanks!
