### ISSUE TITLE
Is SLF4J 1.8.0-beta2 premature?

### ISSUE THREAD

**Issue by apjanke** [googlemaps/google-maps-services-java#457]
In https://github.com/googlemaps/google-maps-services-java/commit/ba40166a0113948765b03fb8725b76a2f350b220, the SLF4J dependency was updated from 1.7.25 to 1.8.0-beta2. Maybe this is premature? google-maps-services-java is a production quality library – should it be using a beta version of a dependency?

I'm also wondering if you might want to wait a bit before upgrading to SLF4J 1.8. SLF4J has had great back-compatibility up until now. However, SLF4J 1.8 introduces a new back-end service provider architecture, which seems to break back-compatibility. So this would require GMSJ clients to upgrade to SLF4J 1.8, which they might not be prepared to do yet. (I'm one of those people; I'm using GMSJ inside Matlab, which is stuck on an older version of SLF4J.)

**Comment by domesticmouse** [comment]
I'm happy to revert.

**Comment by apjanke** [comment]
Thanks!
