### ISSUE TITLE
Javadoc version warning when building

### ISSUE THREAD

**Issue by apjanke** [googlemaps/google-maps-services-java#467]
When I do `gradlew build` now, I get a warning about Javadoc versions.

```
[~/local/repos/google-maps-services-java]
$ ./gradlew build test

> Task :javadoc
javadoc: warning - You have not specified the version of HTML to use.
The default is currently HTML 4.01, but this will change to HTML5
in a future release. To suppress this warning, please specify the
version of HTML used in your documentation comments and to be
generated by this doclet, using the -html4 or -html5 options.
1 warning
```

This is on macOS 10.13.5 , and I think it's running `javadoc` from JDK 10.

```
$ javadoc --version
javadoc 10.0.1
```

Sounds like we should add an explicit version switch, as long as that switch is recognized by Java 1.7 as well.

**Comment by apjanke** [comment]
Darnit.

For newer JDK versions, you could just [include  the `-html4` or `-html5` option](https://stackoverflow.com/questions/50222047/enable-html5-javadoc-in-gradle).

```
javadoc {
    include 'com/company/project/pkg/*'
    options.addBooleanOption('html5', true)
}
```

But that fails with JDK 1.7, because it doesn't support those options yet.

```
$ ./gradlew clean build

> Task :javadoc FAILED
usage: javadoc [options] [packagenames] [sourcefiles] [@files]
javadoc: error - invalid flag: -html4
-overview <file>          Read overview documentation from HTML file
-public                   Show only public classes and members
-protected                Show protected/public classes and members (default)
-package                  Show package/protected/public classes and members
-private                  Show all classes and members
-help                     Display command line options and exit
```

Need more smarts in gradle to detect the version and set javadoc options appropriately. Maybe they already exist and somebody knows how to do this.

**Comment by apjanke** [comment]
> Please stop to mail me.....give me process of how stop your service in
Goole console... please

I'm sorry; I don't understand what you're talking about here. Are you using Google cloud services of some sort?

**Comment by apjanke** [comment]
Looks like there's a relevant upstream Gradle issue: https://github.com/gradle/gradle/issues/4841

**Comment by apjanke** [comment]
Turns out that issue isn't relevant. I've opened a new upstream issue.

Upstream issue: https://github.com/gradle/gradle/issues/5891

**Comment by dapengzhang0** [comment]
As commented here https://github.com/grpc/grpc-java/blob/v1.33.1/build.gradle#L278,  we must specify one html version for java 10. For java 11+, 'html4' option is removed. So we may choose 'html5' option to support all jdk version.
