### ISSUE TITLE
Gradle complains about deprecated features: annotation processor path

### ISSUE THREAD

**Issue by apjanke** [googlemaps/google-maps-services-java#473]
When I run the build, it complains about deprecated Gradle features being used, making it incompatible with Gradle 5.

```
$ ./gradlew clean test
Starting a Gradle Daemon, 3 incompatible Daemons could not be reused, use --status for details

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings
```

Full warnings:

```
$ ./gradlew --warning-mode=all clean test

> Task :compileJava
The following annotation processors were detected on the compile classpath: 'com.google.appengine.tools.compilation.DatastoreCallbacksProcessor'. Detecting annotation processors on the compile classpath is deprecated and Gradle 5.0 will ignore them. Please add them to the annotation processor path instead. If you did not intend to use annotation processors, you can use the '-proc:none' compiler argument to ignore them.

BUILD SUCCESSFUL in 26s
6 actionable tasks: 6 executed
```

**Comment by apjanke** [comment]
Relevant pages:
* https://discuss.gradle.org/t/regarding-the-annotation-processors-on-compile-classpath-warning-in-gradle-4-6/26144/13
* https://deors.wordpress.com/2011/10/08/annotation-processors/
* https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javac.html
* https://blog.gradle.org/incremental-compiler-avoidance

**Comment by apjanke** [comment]
BTW, can we agree in principle that a 100% warning-free build is a goal of this project?

**Comment by domesticmouse** [comment]
I'm very supportive of having a 100% warning free build. I'll find out the appropriate upstream maintainer.

**Comment by domesticmouse** [comment]
Upstream maintainers of the AppEngine jar are currently figuring out how to appropriately update the code without breaking everything.

**Comment by domesticmouse** [comment]
I'm wondering if we can drop the Google App Engine library, as by my reading of the [Java on Google App Engine](https://cloud.google.com/appengine/docs/java/) documentation, both our Standard and Flexible offerings have full Java 8, no whitelist restrictions.

I'll take an action item to spin up a version without GAE libraries and see if it works on both of the supported platforms.

**Comment by amuramoto** [comment]
Closing since `./gradlew clean test` is not displaying any errors at HEAD
