### ISSUE TITLE
Including intermediate stops in transit_mode bus

### ISSUE THREAD

**Issue by russellhoff** [googlemaps/google-maps-services-java#477]
We have realised that when requesting directions fusing transit mode bus from point A to point B, the answer does not include intermediate stops' information, but only it does include the number of them.

For instance, when you request directions from Bilbao to Galdacano, you get the number of stops of a route/leg, but not which of them they are. However, if you do the same task in Google Maps, you get the exact stops. How can it be Directions API not be answering so? Take into account GTFS information is loaded.

**Comment by domesticmouse** [comment]
There are two points of potential deviation between what you see when you look into Google Maps on iOS, Android, or the web, and at the results returned via the Java client library.

The first deviation is between the results available inside Google that the Google Maps front ends rely on, and what is exposed by our Google Maps Web Service endpoints. The second point of deviation is between the information returned via Google Maps Web Service endpoints and what is visible when inspecting the the Java objects returned by the client library.

So, the first step in helping debug this situation is to understand which API endpoint you are calling, look at the returned JSON result, I usually use a handy web browser with a JSON rendering plugin for ease of use, and figure out if the information you need is in that result set. If yes, then we can fix the client library by adding the missing parts to the client library to capture and convert the returned data.

If, however, the information you need is not in the returned JSON endpoint result, then the next step is to raise a feature request on our [API bug tracker](https://developers.google.com/maps/support/) requesting the additional information.

So, which endpoint are you calling, and with what arguments?

**Comment by domesticmouse** [comment]
Closing as stale for the time being. Please re-open with additional information. Thanks!
