### ISSUE TITLE
Creating SessionToken from existing string

### ISSUE THREAD

**Issue by MithilShah** [googlemaps/google-maps-services-java#478]
The PlacesApi.placeAutocomplete() method takes in a SessionToken. There is no way to create a SessionToken from an existing token. The class SessionToken only allows creating new tokens, but for the second request in the same autocomplete session, we need to send the sessionToken created during the first call. Can we modify the SessionToken inner class to add a constructor that takes in an existing token string?

**Comment by MithilShah** [comment]
That would be perfect.

**Comment by domesticmouse** [comment]
Released with version 0.2.10.
