### ISSUE TITLE
Render directions in google maps from DirectionsAPI

### ISSUE THREAD

**Issue by becerriljc** [googlemaps/google-maps-services-java#488]
I need help, im using DirectionsAPI, i send request and response (DirectionsResult) is successful but at insert in

`directionsDisplay.setDirectionsResponse(response)` 
output this error:
not a LatLngBounds or LatLngBoundsLiteral: unknown property northeast

any idea?

**Comment by domesticmouse** [comment]
It’d need a full repro case. I can’t debug from just this error message. I’m not sure how you’d get that message while using the java client library.
