### ISSUE TITLE
Add a warning for undocumented/unsupported values

### ISSUE THREAD

**Issue by broady** [googlemaps/google-maps-services-java#49]
For example, postal_code_suffix / postal_code_prefix are not documented [here](https://developers.google.com/maps/documentation/geocoding/#Types) but it still probably adds value having them in the library.

Let's mark them as `@Deprecated`

**Comment by domesticmouse** [comment]
I believe this issue is dealt with by `SafeEnumAdaptor` logging a warning when mapping an unknown enum type. We have also added a bunch of undocumented AddressTypes.
