### ISSUE TITLE
Geocoding Address

### ISSUE THREAD

**Issue by randysecrist** [googlemaps/google-maps-services-java#491]
Could someone please specify what type of String GeocodingApi.geocode takes for Address?

Our search granularity is City, State, PostalCode.  Currently we a bunch of parameters through the function below then pass that result to the geocode function.  The google client library returns a geocode result for most of our customers however there are a few City,State,PostalCode combinations which don't find any data unless we change our granularity.

Please advise on the correct way to pass a address into this api.  Thanks!

(edit:  does the client library support component filtering?)
https://developers.google.com/maps/documentation/geocoding/intro#ComponentFiltering

```java
    public static final String buildFullAddress(String address, String city, String state, String postalCode, String country) {
        return new StringBuilder()
            .append(Optional.ofNullable(address).orElse(""))
            .append(" ")
            .append(Optional.ofNullable(city).orElse(""))
            .append(" ")
            .append(Optional.ofNullable(state).orElse(""))
            .append(" ")
            .append(Optional.ofNullable(postalCode).orElse(""))
            .append(" ")
            .append(Optional.ofNullable(country).orElse("US"))
            .toString();
    }
```

**Comment by domesticmouse** [comment]
This API is a thin wrapper atop the API, designed to reflect the results returned by the API in a language idiomatic way. We do a bit of sanity checking on inputs, but very little in the way of transformations. If there is something that is exposed in the API that isn't in the client library, please raise a bug request, or better yet, issue a Pull Request with a fix.

Thanks!
