### ISSUE TITLE
Unlike Autocomplete call, placeDetails call in PlacesApi is not supporting SessionToken

### ISSUE THREAD

**Issue by Meyy-DL** [googlemaps/google-maps-services-java#492]
SessionToken is not supported for placeDetails call. Any plans of supporting it? 
The reason being Autocomplete call often goes hand in hand with place details call.

**Comment by Meyy-DL** [comment]
@domesticmouse I understand PlaceDetailsRequest supports it but not PlacesApi. Ref: https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/PlacesApi.java#L103-L107

It makes PlacesApi.placeDetails() kinda unusable when comes to SessionToken

**Comment by domesticmouse** [comment]
How's #493 look like as a potential fix?

**Comment by Meyy-DL** [comment]
@domesticmouse yup. looks good to me

**Comment by domesticmouse** [comment]
I'm rolling a new release that includes this fix. Thanks!

**Comment by Meyy-DL** [comment]
@domesticmouse I got one more question. Not sure whether I have to create one more issue but would like to your thoughts first. 
Is there any reason why SessionToken is not Serializable ?

**Comment by domesticmouse** [comment]
I can’t think of a good reason to make it not serialisable. Wanna submit a
PR?

**Comment by Meyy-DL** [comment]
@domesticmouse Yes. Its in https://github.com/googlemaps/google-maps-services-java/pull/495
