### ISSUE TITLE
how to create a server key?

### ISSUE THREAD

**Issue by ejChathuranga** [googlemaps/google-maps-services-java#496]
To use maps service we need to create server key : [mention here at 4th from list](https://github.com/googlemaps/google-maps-services-java#api-keys)

Most of the reference is saying, when we creating API in GCP console it's asking the type of the API. But now it won't ask in the console. It just creates an API key quickly.

I need guidence for creating new server key.

**Comment by domesticmouse** [comment]
You can edit the key in the console to add server restrictions.
