### ISSUE TITLE
How to use sessionToken from JSApi in getPlaceDetails

### ISSUE THREAD

**Issue by albertjose** [googlemaps/google-maps-services-java#497]
We have a mix using autocomplete in JS with get details on server, but now google change your costs to session-based, is there any way to reuse the token from autocompleteWidget in the request to get place details?

**Comment by domesticmouse** [comment]
I'd put a request up on the [Google Maps JS API Issue Tracker](https://developers.google.com/maps/documentation/javascript/support#issue-tracker) asking for access to the autocomplete widget's session identifier. Once you have that you can construct a session in this client library to match.
