### ISSUE TITLE
java.net.ConnectException: Failed to connect to maps.googleapis.com/172.217.160.74:443

### ISSUE THREAD

**Issue by jasonleelover** [googlemaps/google-maps-services-java#499]
I am using ShadowsocksR for proxying in China, and intellij's http proxy test is successful for accessing maps.googleapis.com, but I made an error when doing unit testing, what should I do?

_maven_

`
<dependency>
            <groupId>com.google.maps</groupId>
            <artifactId>google-maps-services</artifactId>
            <version>0.2.11</version>
</dependency>
<dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
            <version>1.7.25</version>
</dependency>
<dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.8.5</version>
</dependency>
`

_code_

           ` GeoApiContext context = new GeoApiContext.Builder().apiKey("AIza*********")
            .connectTimeout(50, TimeUnit.SECONDS).build();
            GeocodingResult[] results =  GeocodingApi.geocode(context,
                    "1600 Amphitheatre Parkway Mountain View, CA 94043").await();
            Gson gson = new GsonBuilder().setPrettyPrinting().create();
            System.out.println(gson.toJson(results[0].addressComponents));`

**Comment by domesticmouse** [comment]
I'm unsure how to debug this issue, as I'm guessing it's a networking issue. Can you test if the java application is using your network proxy?
