### ISSUE TITLE
Error with Proguard

### ISSUE THREAD

**Issue by davisoqt** [googlemaps/google-maps-services-java#500]
After use the lib and enabled Proguard im getting these error 

Warning: com.google.maps.GaeRequestHandler: can't find referenced class com.google.appengine.api.urlfetch.URLFetchServiceFactory
Warning: com.google.maps.GaeRequestHandler: can't find referenced class com.google.appengine.api.urlfetch.FetchOptions$Builder
Warning: com.google.maps.GaeRequestHandler: can't find referenced class com.google.appengine.api.urlfetch.HTTPRequest
Warning: com.google.maps.GaeRequestHandler: can't find referenced class com.google.appengine.api.urlfetch.HTTPMethod
Warning: com.google.maps.GaeRequestHandler: can't find referenced class com.google.appengine.api.urlfetch.HTTPRequest
Warning: com.google.maps.GaeRequestHandler: can't find referenced class com.google.appengine.api.urlfetch.HTTPHeader
Warning: com.google.maps.GaeRequestHandler: can't find referenced class com.google.appengine.api.urlfetch.HTTPHeader
Warning: com.google.maps.GaeRequestHandler: can't find referenced class com.google.appengine.api.urlfetch.HTTPRequest
Warning: com.google.maps.GaeRequestHandler: can't find referenced class com.google.appengine.api.urlfetch.HTTPRequest
Warning: com.google.maps.GaeRequestHandler: can't find referenced class com.google.appengine.api.urlfetch.FetchOptions
Warning: com.google.maps.GaeRequestHandler: can't find referenced class com.google.appengine.api.urlfetch.URLFetchServiceFactory

If i use -dontwarm the app crash. Any suggestion..?

**Comment by domesticmouse** [comment]
My suggestion is not to use this library in an Android app, as you risk losing your API Key to an attacker.

**Comment by feinstein** [comment]
How's this library security different from other Google Maps APIs for Android?

**Comment by domesticmouse** [comment]
Simplest answer is this library is designed for server side usage, not Android.

**Comment by feinstein** [comment]
It's about time you guys make a Rx version, so we can make this whole Network Request, error handling, cancellation and retry easier and reactive.

I am not going to open an issue about it because I think this should be done for all the code bases and not just this one.
