### ISSUE TITLE
navigation

### ISSUE THREAD

**Issue by alexd555** [googlemaps/google-maps-services-java#504]
Hi,
I'm looking for source code example of waze or someting other program where I can navigate and filter my choices.
Can you help ?

**Comment by domesticmouse** [comment]
It looks like waze has an api: https://developers.google.com/waze/

Fair warning, I know nothing about the waze product and api offerings.

Here’s the documentation for Directions API, which gives you routes between two locations: https://developers.google.com/maps/documentation/directions/intro
