### ISSUE TITLE
When should I expect to see NotFoundException and ZeroResultsException?

### ISSUE THREAD

**Issue by shirley-salesforce** [googlemaps/google-maps-services-java#505]
My use case is when geocode addresses causing NotFoundException or ZeroResultsException, we would like to mark those addresses for validation.

But in the following sample code, GeocodingApi won't throw exceptions for address "1234 street someplace", instead the GeocodingResult is empty. My question is should I expect NotFoundException and ZeroResultsException here? otherwise how do I know what caused the 0 results?

```
GeocodingApiRequest req = GeocodingApi
     .newRequest(context)
     .address("1234 street someplace");

try {
    GeocodingResult[] results = req.await();
    // Handle successful request.
} catch (NotFoundException |  ZeroResultsException e) {
    // Handle error
}

**Comment by domesticmouse** [comment]
The ZeroResultsException is thrown when the result from the API contains the error "ZERO_RESULTS". Have a look at the mapping code in `ApiException.java`.
