### ISSUE TITLE
Missing support for fields param on place details requests

### ISSUE THREAD

**Issue by nathan-poquette** [googlemaps/google-maps-services-java#508]
The Places API describes a `fields` parameter that can be passed to indicate which place data types will be returned on a Place Details request. It recommends to include this, as omitting it will default to ALL fields being returned and warns that "you will be billed accordingly". https://developers.google.com/places/web-service/details#fields

I've curious if there is support, either currently or planned, for being able to specify `fields` on place details requests issued via the Java client (i.e. when building a `PlaceDetailsRequest` object). I did some digging but have been unable to find such functionality.

Thanks in advance for any help!

**Comment by domesticmouse** [comment]
I thought I had implemented fields support. Please raise bugs on the API calls that aren't exposing fields setters that should do so. Thanks!

**Comment by nathan-poquette** [comment]
You're right, my bad. I thought I was looking at the latest version but I wasn't. I see it here: https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/PlaceDetailsRequest.java#L80
