### ISSUE TITLE
How can I compile google-maps-services?

### ISSUE THREAD

**Issue by wgarn** [googlemaps/google-maps-services-java#51]
More specifically I am attempting to use javac via command line to build the classes. Here is what I did:
1) downloaded and extracted the zip file.
2) went to the src\main\java folder
3) copied gradle-wrapper.jar into a src\main\java\lib folder
4) tried to build classes: javac -cp lib* -d build com/google/maps/_.java com/google/maps/errors/_.java com/google/maps/internal/_.java com/google/maps/model/_.java 
This leads to errors such as: "com\google\maps\internal\OkHttpPendingResult.java:176: error: cannot find symbol ... Request"; or Response; etc. 
What am I missing? Is there a google-maps-services jar?

**Comment by broady** [comment]
You shouldn't need to put gradle in your classpath if you're using the gradlew script. It'll go and fetch the appropriate gradle version from the internet.

Again, compile it using `gradlew.bat` rather than `javac` directly.

**Comment by broady** [comment]
You shouldn't need to change your `CLASSPATH` at all.

Could you run `gradlew.bat jar` with a clean environment and paste the output?

How come you want to build the project from scratch rather than fetching the dependency from Maven Central?
