### ISSUE TITLE
[Android] This IP, site or mobile application is not authorized to use this API key. Request received from IP address XXX, with empty referer

### ISSUE THREAD

**Issue by jeMarques** [googlemaps/google-maps-services-java#510]
I'm Trying to use Geocoding api into my Android app to do Reverse geocode in order to get an Adress from a LatLon.

Keep failing with error: This IP, site or mobile application is not authorized to use this API key. Request received from IP address XXX, with empty referer

API Key are created. And the Geocoding API is ON and Attached to API Key.

Have read in some forums that i need to create an proxy server to use Geocoding API and i cant ise directly from the App, is that right?

Thanks in Advance.

**Comment by domesticmouse** [comment]
Please do not use this library on Android, as it opens you up to the risk of a third party stealing your API key and abusing your account. Implementing a server side proxy gives you the ability to monitor and manage you API usage.

**Comment by stkent** [comment]
@domesticmouse:

I've seen this sentiment echoed in several places, but I'm struggling to see how the risk of exposure you describe is any different from e.g. the risk of exposure of a Google Cloud Platform key added to an Android manifest as recommended in the official Google Places Android SDK setup instructions: https://developers.google.com/places/android-sdk/signup#use-key

<img width="858" alt="screen shot 2018-11-07 at 2 45 56 pm" src="https://user-images.githubusercontent.com/6463980/48156677-de2b7b80-e29b-11e8-8933-be6e28943c75.png">

As far as I can tell, the same console-side restrictions can be applied to the key in each case (e.g.: limit usages to Android apps with a given application id and signed with a certificate with a given SHA), so there appears to be no difference in security from that point of view.

Please help me understand the difference between these cases. Thanks in advance for your insights!

**Comment by stkent** [comment]
After further investigation, maybe this part is not accurate?

> As far as I can tell, the same console-side restrictions can be applied to the key in each case (e.g.: limit usages to Android apps with a given application id and signed with a certificate with a given SHA)

My key gets rejected if I enable those restrictions but works from an Android app fine otherwise.

**Comment by stkent** [comment]
Thanks @domesticmouse :) I recently discovered a [Google Groups discussion](https://groups.google.com/d/msg/google-cloud-endpoints/I-u3sAUU3Ts/AjdAsWkjAwAJ) that seems to demonstrate how to use an Android-restricted API key with e.g. the Geocoding API endpoints. A small implementation of the above that I put together outside the context of this library seem to be working ok, so I wonder if this is something that might be officially supported in the future? Either way, thanks again for the reply and insight on current truths!
