### ISSUE TITLE
The result returned by the client is not in the correct language

### ISSUE THREAD

**Issue by zhangchunxing** [googlemaps/google-maps-services-java#519]
- **my request** : 
https://maps.googleapis.com/maps/api/place/nearbysearch/json?key=XXXXX&location=34.9962228,135.7183618&language=jp&keyword=京都光華女子大学&radius=50000

- **question**:
I specified that the argument "language" was "jp"，but the name of result  returned was english.
Why?

**Comment by domesticmouse** [comment]
Please raise this issue on the API Issue tracker: https://developers.google.com/maps/support/#issue_tracker

This issue tracker is for the Java client library itself. Thanks!
