### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError at com.google.maps.GeoApiContext.<init>

### ISSUE THREAD

**Issue by zheng022** [googlemaps/google-maps-services-java#52]
Hi, I just have a very stupid question:
I have created a java application like this:

package test;

import com.google.maps.DistanceMatrixApi;
import com.google.maps.GeoApiContext;
import com.google.maps.GeocodingApi;
import com.google.maps.model.DistanceMatrix;
import com.google.maps.model.DistanceMatrixRow;
import com.google.maps.model.GeocodingResult;
import com.google.maps.model.TravelMode;

public class TestGoogle {
    public static void main(String[] args)  {
        GeoApiContext context = new GeoApiContext().setApiKey("AIz***");
        GeocodingResult[] results;
        try {
            results = GeocodingApi.geocode(context,"1600 Amphitheatre Parkway Mountain View, CA 94043").await();
            System.out.println(results[0].formattedAddress);
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }
}

But when I ran it, I got an error:
Exception in thread "main" java.lang.NoClassDefFoundError: com/squareup/okhttp/OkHttpClient
    at com.google.maps.GeoApiContext.<init>(GeoApiContext.java:49)
    at test.TestGoogle.main(TestGoogle.java:40)
Caused by: java.lang.ClassNotFoundException: com.squareup.okhttp.OkHttpClient

Do you know, what could be the reason? I have tried with both server key and browser key.

Thank you!

**Comment by levratinov** [comment]
I'm building as follows:  ./gradlew jar and I'm running into the same problem. I don't want to build my project with Maven or Gradle.

I tried to build the okhhtp jar following the directions on their github  (https://github.com/square/okhttp ) but the package is now okhttp3.OkHttpClient , not com.squareup.okhttp.OkHttpClient . So adding the dependency doesn't solve the problem.

How can I compile the Maps API with dependencies or compile okhttp with the "right" package name?

Thanks.

**Comment by erickarizaa** [comment]
it hasn't been closed, google have a link a library that can be downloaded without use of Maven or Gradle, when i use this throw the same error
