### ISSUE TITLE
DirectionApi could have a shortcut for departure_time = "now"

### ISSUE THREAD

**Issue by feinstein** [googlemaps/google-maps-services-java#524]
Even though `departure_time` defaults to `now` if not specified, the `duration_in_traffic` response will only be returned if we make sure to specify the `departure_time` in the request.

Currently the library only provides `DirectionsApiRequest departureTime(Instant time)`, which could be tricky to pass the current time, since the Directions API won't accept past values and the network latency could transform our current time in a past time. I assume the Directions API will have some sort of "time window" for considering a shortly elapsed time as still the current time, but that's totally an assumption of mine.

I propose a new method to simplify things, something like:
```
public DirectionsApiRequest departureTimeNow() {
    return param("departure_time", "now");
}
```

If approved I could implement this right now and submit the pull request.

**Comment by domesticmouse** [comment]
Have you tried what the API returns when you pass `departure_time=now` to the Directions API? Another option is to request a `departure_time` 1 minute into the future, for example.

**Comment by feinstein** [comment]
I didn't try the library yet, but I tried with an https request and with `departure_time=now` I get `duration_in_traffic` (as stated in the docs), but without `departure_time=now`, I don't get it. I am also not defining `driving` since it defaults to `driving` when omitted.

> Another option is to request a departure_time 1 minute into the future

Yeah, I thought about setting it to 1 minute in the future, it just made sense to me to expose `departure_time=now` in the library, since this is something the API already gives us. Also it avoids coding some jodatime boilerplate code for getting the current time plus 1 minute (not even mentioning a small performance improvement of saving the system calls for fetching the current time).

**Comment by domesticmouse** [comment]
If it works against the servers, I'm happy to add it to the client library. You were saying you are willing to put this together as a PR? =)

**Comment by feinstein** [comment]
Gladly, but I am not familiar enough with the tests to include this change there, do you think it needs to be incorporated into the tests as well? Looks kinda trivial to me...

**Comment by domesticmouse** [comment]
I can add tests for this. =)
