### ISSUE TITLE
Include package-list file in Javadoc

### ISSUE THREAD

**Issue by pushbit** [googlemaps/google-maps-services-java#531]
Please include the `package-list` file when publishing Javadocs so that we can link to it when generating our own Javadocs.  For example, I would expect to find it at the below URL, but a 404 is returned.

https://googlemaps.github.io/google-maps-services-java/latest/javadoc/package-list

**Comment by apjanke** [comment]
It seems like the `package-list` file is not being generated during the javadoc generation step of the build. (I don't see it in the `build/docs/javadoc` directory after running `./gradlew package`. Anyone know if there's an option we need to pass to the gradle `javadoc` target to enable the `package-list` file?

**Comment by domesticmouse** [comment]
Hmm, if anyone can figure out how to force the generation of said `package-list` file, I'm happy to accept the pull request.

**Comment by apjanke** [comment]
I've got nothing. I fiddled around with it for a while and couldn't figure out how to make the `package-list` file appear.

**Comment by pushbit** [comment]
When I run `./gradlew assemble` it generates `build/docs/javadoc/package-list`, which is included in `build/libs/google-maps-services-java-0.9.2-SNAPSHOT-javadoc.jar`.  I tried to run `./gradlew package`, but I get `Task 'package' not found in root project 'google-maps-services-java'.`  I don't see any recent changes to the gradle files that could explain this.  Could our build environments be different somehow to causes these differences?

**Comment by jpoehnelt** [comment]
It's available at https://static.javadoc.io/com.google.maps/google-maps-services/0.10.1/package-list.
