### ISSUE TITLE
Problems running the tests.

### ISSUE THREAD

**Issue by antonianemi** [googlemaps/google-maps-services-java#532]
I just downloaded the project but i have some issues running the tests, the error message i have is this.

Process finished with exit code 1
Class not found: "com.google.maps.PlacesApiTest"

i resolved all the dependencies but i am still having this issue, thanks.

**Comment by apjanke** [comment]
Can you give us some more information about your development environment and the exact commands you're running to execute the tests?

**Comment by antonianemi** [comment]
Well, i found the fix it was about intellij's problem, turns out that the IDE was holding two gradle's configurations one for java and another for droid so they are not compatible i had to delete the projects file generated by intellij and create it back again. Thanks a lot.
