### ISSUE TITLE
Replace gson with standard JSR libraries

### ISSUE THREAD

**Issue by ptahchiev** [googlemaps/google-maps-services-java#533]
Is there any particular reason why you use gson? I'm trying to create an application where the customer can inject a json implementation library at runtime of their own choice and currently it is not possible because google-maps-services brings gson as a transitive dependency.

**Comment by apjanke** [comment]
Are you referring to [JSR-353](https://jcp.org/en/jsr/detail?id=353)? Or [JSR-374](https://javaee.github.io/jsonp/)? Or [JSR-367](https://jcp.org/en/jsr/detail?id=367)?

I did some Googling and I get the impression these aren't very popular standards. GSON and Jackson don't implement them natively. It looks like Eclipse Yasson and Apache Johnzon are the only major implementations right now.

GSON's API has a nice direct conversion with POJOs. The JSR-353 API looks like it requires more boilerplate work.

GSON doesn't seem like a very onerous dependency. Why can't your customer use it in this case?

**Comment by domesticmouse** [comment]
I’m happy to review PRs looking at making this change, but I doubt it will be a fun job.

**Comment by domesticmouse** [comment]
I'd need to see a downside that is stronger than the number of dependencies to motivate me to do the porting work required to move from GSON to a new pluggable JSON provider interface. I'll happily review PRs that implement this change, but I won't be instigating the work myself.

It has taken a number of years of work to get this library to its current relatively stable state, and I'm about ready to version it 1.0. This change would probably be sufficient for a 2.0, as I'm guessing it will break the exposed API surface somewhere.

**Comment by domesticmouse** [comment]
Closing this out as it isn't something I'm going to do.
