### ISSUE TITLE
App crashing running DirectionsApi.newRequest on api version lower than 26

### ISSUE THREAD

**Issue by jeffreyliu8** [googlemaps/google-maps-services-java#545]
![screen shot 2019-01-24 at 10 44 10 am](https://user-images.githubusercontent.com/12398645/51700959-3170b880-1fc5-11e9-870f-44c8daa246b3.png)

zonedDateTime is for api 26 or above, but my app is running on something lower than that(24)
https://developer.android.com/reference/java/time/ZonedDateTime

DirectionsResult result = DirectionsApi.newRequest(context)
                                .mode(TravelMode.DRIVING)
                                .origin(new com.google.maps.model.LatLng(start.latitude, start.longitude))
                                .destination(new com.google.maps.model.LatLng(end.latitude, end.longitude))
                                .await();
                        results.add(result);

**Comment by domesticmouse** [comment]
Supporting Android is not in scope for this project, per the README.
