### ISSUE TITLE
For all zipcode throws exception java.lang.RuntimeException: Unknown address type 'health'

### ISSUE THREAD

**Issue by mahesh2492** [googlemaps/google-maps-services-java#546]
Below code works fine for all postal code but it throws an exception for every zipcodes i.e 90210

import com.google.maps.GeocodingApi
import com.google.gson.GsonBuilder

object GoogleMapApiPoc extends App {
 val context = (new GeoApiContext).setApiKey(API_KEY)
 val geoCodingApiResult  = new GeocodingApiRequest(context).components(GeocodingApi.ComponentFilter.postalCode("90210"))
println(geoCodingApiResult.await()(0).addressComponents)
}

And the same thing works fine if I hit below URL on the browser

> https://maps.googleapis.com/maps/api/geocode/json?key=API_KEY&components=postal_code:90210

**Comment by apjanke** [comment]
Looks to me like you're using an older version of GMSJ. As of 0.9.2, there's no `GeocodingApi.ComponentFilter` type that I can see.

Could you try this against the latest version of the code?

**Comment by mahesh2492** [comment]
Yes, It is working fine with the latest version but when I give an incorrect postal code. It returns empty json instead of Zero_Result .

```
val result = GeocodingApi.newRequest(context).components(new ComponentFilter("postal_code", "00000")).await()

  val gson = new GsonBuilder().setPrettyPrinting().create()
  println(gson.toJson(result(0).addressComponents))

```So, it throws array out of bound exception because result is empty but it should throw zero_result json,

**Comment by domesticmouse** [comment]
Yes, that was an explicit change in defaults. I can't remember which version contains the change. We should probably delete the Zero result exception to force people to update their expectations.

**Comment by amuramoto** [comment]
closing this since the reported issue of using zip code causing the method to throw was determined to be due to an old version
