### ISSUE TITLE
Test support for places API

### ISSUE THREAD

**Issue by delta-bravo** [googlemaps/google-maps-services-java#547]
Hi!
I would like to cover our application with some black box and load tests and for obvious reasons I would like to stub out calls to Google APIs to prevent charges for requests sent during the tests.
Is there a recommended approach for this or are there any classes that could be used for testing? 

I know I can extend GeoApiContext's Builder to set base url - which seems a bit hacky. Are there any other ways you would suggest?

Thanks!

**Comment by domesticmouse** [comment]
I'd suggest going with the extension approach.

**Comment by jbarop** [comment]
Can you please provide an example how this extension approach does like?

- `GeoApiContext` cannnot be extended because the constructor is package private.
- `GeoApiContext.Builder.baseUrlOverride()` cannot be overridden because it is package private.
- `GeoApiContext.Builder.build()` cannot be implemented because the constructor of `GeoApiContext` is package private

**Comment by delta-bravo** [comment]
@jbarop What I did I extended `GeoApiContext.Builder` class, so that I could override the `baseUrl`

**Comment by jbarop** [comment]
I still don't see how I am able to provide the baseUrl because it is package private.

**Comment by delta-bravo** [comment]
Kotlin code:
```
class TestGeoContextBuilder : GeoApiContext.Builder() {
    init {
        val wiremockBaseUrl = System.getProperty("wiremockBaseUrl") ?: "http://localhost:13373"
        baseUrlOverride(wiremockBaseUrl)
    }
}
```

**Comment by jbarop** [comment]
`Cannot access 'baseUrlOverride': it is invisible (private in a supertype) in 'TestGeoContextBuilder'`

**Comment by delta-bravo** [comment]
@jbarop all you need to do is extend the Builder and call the method in your Builder. If Kotlin code doesn't help, here is Java:

```
public class TestGeoApiContextBuilder extends GeoApiContext.Builder {
    public TestGeoApiContextBuilder(String urlOverride) {
        super();
        baseUrlOverride(urlOverride);
    }
}
```

somewhere in your code:

```
GeoApiContext context = new TestGeoApiContextBuilder("your-mock-base").build();
```

**Comment by jbarop** [comment]
May be we have different versions of the libaray. In 0.9.2 baseUrlOverride is only accessible from classes inside the `com.google.maps` package.

**Comment by delta-bravo** [comment]
@jbarop that's right- your extended class should be in this package. 
```
package com.google.maps;

public class TestGeoApiContextBuilder extends GeoApiContext.Builder {
    public TestGeoApiContextBuilder(String urlOverride) {
        super();
        baseUrlOverride(urlOverride);
    }
}
```

**Comment by jbarop** [comment]
This is very hacky and thus will not work with newer Java versions (9+) and it's module system

**Comment by PaulLockett** [comment]
Im new to java and Im trying to test my code that calls the places API.

I am running my test with maven and have gotten to the point that I need to place the extended class in the package and Im not sure how.

I get the this error:
error: cannot find symbol
symbol:   class TestGeoApiContext
location: package com.google.maps

how can I make maven think that the extended class is coming from the package com.google.maps package?

for referance this is my TestGeoApiContextBuilder.java class file

package com.google.maps;

public class TestGeoApiContextBuilder extends GeoApiContext.Builder {
    public TestGeoApiContextBuilder(String urlOverride) {
        super();
        baseUrlOverride(urlOverride);
    }
  }
