### ISSUE TITLE
Error when parsing some geocoding response

### ISSUE THREAD

**Issue by jbenoit2011** [googlemaps/google-maps-services-java#553]
While geocoding some address we found out Google Maps SDK Java throw some warnings when the geocoding response contains a place of following types:
* `archipelago`
* `museum`
* `campground`
* `rv_park`
* `museum`

Here is full log lines:
```
19/03/19 14:13:00 WARN SafeEnumAdapter: Unknown type for enum com.google.maps.model.AddressComponentType: 'archipelago'
19/03/19 14:13:00 WARN SafeEnumAdapter: Unknown type for enum com.google.maps.model.AddressType: 'archipelago'
19/03/19 14:14:48 WARN SafeEnumAdapter: Unknown type for enum com.google.maps.model.AddressComponentType: 'museum'
19/03/19 14:12:44 WARN SafeEnumAdapter: Unknown type for enum com.google.maps.model.AddressComponentType: 'campground'
19/03/19 14:12:44 WARN SafeEnumAdapter: Unknown type for enum com.google.maps.model.AddressComponentType: 'rv_park'
19/03/19 14:12:44 WARN SafeEnumAdapter: Unknown type for enum com.google.maps.model.AddressComponentType: 'campground'
```
I think this issue is highly related to #433 .
This prevent us to reliably geocode our data since the results objects is empty because of this issue.
How this can be fixed?

We are using 0.9.2 version on Spark/EMR 5.21.

Thanks.

**Comment by domesticmouse** [comment]
Please raise a PR with the types you need and I'll roll a new release.

/cc @amuramoto for visibility

**Comment by apjanke** [comment]
Here's a PR:  #554.

**Comment by domesticmouse** [comment]
Version 0.9.3 is in the process of rolling out.
