### ISSUE TITLE
PlaceDetailsRequest: `fields` method creates NOT_FOUND err

### ISSUE THREAD

**Issue by sihaiyang0215** [googlemaps/google-maps-services-java#556]
This is not an SDK issue. Please remove it. 
Thanks.

**Comment by domesticmouse** [comment]
I'm confused as to what the ask here is. If it is a change to the client library, please put together a PR showing the required change. If, however, it is an issue with the API, then https://developers.google.com/maps/support/#issue_tracker is the correct bug tracker.
