### ISSUE TITLE
HmacSHA1 doesn't implement cloneable

### ISSUE THREAD

**Issue by AmbroiseS** [googlemaps/google-maps-services-java#557]
Hello, 

**Issue**:  
When doing request to direction service : it throws 

> java.lang.IllegalStateException: java.lang.CloneNotSupportedException: Class com.android.org.conscrypt.OpenSSLMac$HmacSHA1 doesn't implement Cloneable

**Context**:
compileSdkVersion 28
Library version: 0.9.3
I use GeoApiContext and set entrepriseCredentials to make my request. 

HmacSHA1 does implement Cloneable.
This happened after I updated to 0.9.3. 

Thank you for your consideration, I am available for more details.

**Comment by AmbroiseS** [comment]
I see that the library is not meant for Android because of the risks of leaking the API key. 
I do not have such risks in my situation. My app is distributed internally and the devices are safe. 
Did the last versions break compatibility with Android?

**Comment by domesticmouse** [comment]
No idea. Happy to accept pull requests if you debug this and figure out the root cause.

**Comment by amuramoto** [comment]
@AmbroiseS were you able to track this down?

**Comment by AmbroiseS** [comment]
No sorry I spent some time but could not make sense of it

**Comment by amuramoto** [comment]
@AmbroiseS can you provide an example of the call that's throwing?
