### ISSUE TITLE
Nearby Places Search doesnt return correct results for type FOOD

### ISSUE THREAD

**Issue by roozel41** [googlemaps/google-maps-services-java#558]
Whenever I use PlaceType.FOOD, the results dont include the type food. 

But when I use the same radius and use PlaceType.RESTAURANT, I get the right results. And the type includes Restaurant AND Food.

The results are non-food related even when I remove radius and use Rank by Distance

**Comment by domesticmouse** [comment]
We happily accept PRs!

/cc @amuramoto

**Comment by wangela** [comment]
Please see the [documentation: Table 1](https://developers.google.com/places/web-service/supported_types) lists the types supported for place searches (includes restaurant, but not food). Even though a type might be returned in responses, ([Table 2](https://developers.google.com/places/web-service/supported_types#table2) lists those additional types), you can use those response types for post-response processing but not for searching.
