### ISSUE TITLE
Depending on `java.time.Instant` is problematic on Android

### ISSUE THREAD

**Issue by syslogic** [googlemaps/google-maps-services-java#559]
These two methods, which depend on `java.time.Instant`:

https://github.com/googlemaps/google-maps-services-java/blob/b56d71c89a32a40640d1eb895c4bcb3ef192f1b5/src/main/java/com/google/maps/DirectionsApiRequest.java#L172

https://github.com/googlemaps/google-maps-services-java/blob/b56d71c89a32a40640d1eb895c4bcb3ef192f1b5/src/main/java/com/google/maps/DirectionsApiRequest.java#L185

May cause in this warning on Android devices with an API level `< 26`:

> Call requires API level 26 (current min is 23): java.time.Instant#now

Which means, that one can currently only set value `now` on Android devices with an API level `< 26`:

https://github.com/googlemaps/google-maps-services-java/blob/b56d71c89a32a40640d1eb895c4bcb3ef192f1b5/src/main/java/com/google/maps/DirectionsApiRequest.java#L196

---

Suggested backwards-compatibility fix:

Please add two alternative methods, which permit setting `UNIX` epoch time - alike the API expects it.

---

For reference: https://stackoverflow.com/questions/55550936/call-requires-api-level-26-current-min-is-23-java-time-instantnow/55556222

**Comment by domesticmouse** [comment]
Per the README, Android isn’t a supported platform.

**Comment by syslogic** [comment]
that's a rather limited way of thinking - which vastly limits possible applications.

**Comment by domesticmouse** [comment]
The issue is that including an API key in an Android app opens a developer up to a denial of service attack on their credit card through API key theft.

**Comment by domesticmouse** [comment]
As to Java 7 support, if you look at the release notes and other closed bugs you will see that moving to Java 8 minimum was a community decision. With that said, I'm happy with people forking the codebase and adapting it for their requirements. I'm optimising for getting developers started quickly and securely.

**Comment by syslogic** [comment]
> The issue is that including an API key in an Android app opens a developer up to a denial of service attack on their credit card through API key theft.

Not really, because Maps API keys [should be restricted](https://developers.google.com/maps/api-key-best-practices#restrict_apikey) by package-name and signature fingerprint.

The current situation is that Android is supported - even if unofficially, but API `>= 26` is required to set the timestamps, while the Directions API does accept `UNIX` epoch time.

**Comment by domesticmouse** [comment]
The problem is that Google Maps API keys can't be protected by package name and secure fingerprint.

**Comment by syslogic** [comment]
Of course this is possible; you might be referring to outdated information. Just go to the [Credentials Panel](https://console.cloud.google.com/apis/credentials), select such an "Api key" for an Android app... there it reads `Restrict and rename API key` ...`Restrict usage to your Android apps > Add your package name and SHA-1 signing-certificate fingerprint to restrict usage to your Android apps`.

**Comment by domesticmouse** [comment]
I understand what the console says. However, the Maps API backends do not honour that restriction as this wasn't designed as an API to be used from mobile. It was always meant for usage from servers. We have APIs for Android, iOS and the Web for client usage scenarios.
