### ISSUE TITLE
Add user_ratings_total field to place details

### ISSUE THREAD

**Issue by prettyvoid** [googlemaps/google-maps-services-java#560]
user_ratings_total is missing from placedetails and fieldmasks, can it be added?

Thanks,

**Comment by domesticmouse** [comment]
We gladly accept Pull Requests =)

**Comment by apjanke** [comment]
@prettyvoid Per [this](https://issuetracker.google.com/issues/35820858#comment275), `user_ratings_total` is only available as part of the "Atmosphere SKU". Can you provide an example of how to run a query that does the Atmosphere thing and gets a `user_ratings_total` field in the response?
