### ISSUE TITLE
Add implementation of Serializable into AutoCompletePrediction$MatchedSubstring class

### ISSUE THREAD

**Issue by danieldsf** [googlemaps/google-maps-services-java#563]
Hello!

I am using Spring framework alongside Google Map Services and one of the features that you would like to suggest are the serialization of the class MatchedSubstring, which is located inside of the class AutoCompletePrediction. 

So far the class above mentioned does not implement Serializable, so if I try to use cache features returning data from a model that has a composition with the AutoCompletePrediction class, an error similar to the following may occur:

`Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: com.google.maps.model.AutocompletePrediction$MatchedSubstring` 

Once the class MatchedSubstring implements Serializable, it will be possible to use certain cache strategies that I am trying out. 

Thank you.

**Comment by domesticmouse** [comment]
We happily accept PRs!

/cc @amuramoto

**Comment by danieldsf** [comment]
I just created a PR for this issue. #565
