### ISSUE TITLE
TextSearchRequest requires `query` even when it contains `type`

### ISSUE THREAD

**Issue by danoscarmike** [googlemaps/google-maps-services-java#564]
[Docs](https://developers.google.com/places/web-service/search#TextSearchRequests) suggest that `query` parameter becomes optional when `type` parameter is included. However this doesn't seem to work with this library. The [`validateRequest()`](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/TextSearchRequest.java#L164) method of the `TextSearchRequest` class wants a `query` parameter in all cases that don't include a `pageToken`.

Are the docs incorrect?

**Comment by domesticmouse** [comment]
The documentation is considered the golden source of truth. Differences between the docs and this library are generally a bug in this code, except in the cases where we are enforcing best practices. Please feel free to submit a PR to fix the `validateRequest()` logic.

/cc @amuramoto

**Comment by danoscarmike** [comment]
Thanks @domesticmouse. LMK if PR needs anything.
