### ISSUE TITLE
Can't retrieve status messages from Google Directions

### ISSUE THREAD

**Issue by danielolssonIT** [googlemaps/google-maps-services-java#572]
The DirectionResponse class doesn't have a status attribute, where errors like `MAX_ROUTE_LENGTH_EXCEEDED` can be handled. I have tried to get information via the Throwable parameter in the callback `onFailure`, but the responses there seem inconsistent. 

Is it possible to access the status message somehow?

**Comment by rchopda** [comment]
static class is defined without access modifier (default) if we change the modifier to public similar to GeolocationApi Response we will be able to use google-maps-services sdk to parse the json response returned by maps api. 
Any specific reason static  api response classes are created with default access modifier

**Comment by domesticmouse** [comment]
There have been several maintainers through the years, but it’s probably my fault. Please feel free to create a PR to make said class public. Thanks!

**Comment by rchopda** [comment]
Hi Brett,

PR raised please validate and approve

**Comment by amuramoto** [comment]
Looks like this can be closed? @domesticmouse
