### ISSUE TITLE
How to add timestamp in TimeZoneApi.getTimeZone()？

### ISSUE THREAD

**Issue by Michael-crazyman** [googlemaps/google-maps-services-java#575]
This is my pom version, and I cannot figure out how to specify a timestamp parameter when I use TimeZoneApi.getTimezone() function with Java client

```
<dependecy>
     <groupId>com.google.maps</groupId>
     <artifactId>google-maps-services</artifactId>
      <version>0.1.20</version>
</dependency>
```

so can someone teach me?

**Comment by amuramoto** [comment]
Hello! Please post how-to questions to our StackOverflow tag:

https://stackoverflow.com/questions/tagged/google-maps
