### ISSUE TITLE
how to use the geometry library with this java client

### ISSUE THREAD

**Issue by NAVODYA123** [googlemaps/google-maps-services-java#576]
I need to use compute offsets method defined in the google.maps.geometry library. I have already downloaded the java client for google maps API and used some of the defined API methods.but  it says in the documentation to add the required library request in the bootstrap.I need to know the code to how to to that in java instead of java script.

**Comment by domesticmouse** [comment]
This client library is a wrapper for Google Maps Web Services APIs. This don't include functionality for Geometry calculations.
