### ISSUE TITLE
Unsupported field name 'alt_id'

### ISSUE THREAD

**Issue by KevinRamsunder** [googlemaps/google-maps-services-java#589]
Today, inexplicably, the maps API stopped supporting the ALT_ID field, and all of our place detail requests started failing.

Why? It's still listed here: https://github.com/googlemaps/google-maps-services-java/blob/183e6c13324bdc03debd48b24980e761809d2d05/src/main/java/com/google/maps/PlaceDetailsRequest.java#L122

**Comment by domesticmouse** [comment]
Please raise your issue at https://developers.google.com/maps/support/#issue_tracker

This issue tracker is just for the client library. Thanks!
