### ISSUE TITLE
Version 0.10.0 doesn't specify any dependencies in the pom.xml in maven central

### ISSUE THREAD

**Issue by Edholm** [googlemaps/google-maps-services-java#599]
#### Steps to reproduce

  1. Check pom.xml in mvn central:https://repo1.maven.org/maven2/com/google/maps/google-maps-services/0.10.0/google-maps-services-0.10.0.pom

The earlier version does specify dependencies, but the newest one does not, leading to `ClassNotFoundExeptions`

Is this intended or something that has gone wrong when converting from Gradle to maven?

**Comment by amuramoto** [comment]
This is fixed in https://github.com/googlemaps/google-maps-services-java/pull/606. We'll publish the fix as v0.10.1 on Monday.

Thanks for catching this!

**Comment by jpoehnelt** [comment]
Reopening until published.

**Comment by jpoehnelt** [comment]
0.10.1 is available: https://search.maven.org/artifact/com.google.maps/google-maps-services/0.10.1/jar
