### ISSUE TITLE
Geocoding - Possible All APIs - okhttp3 and gson are undocumented dependencies?

### ISSUE THREAD

**Issue by mleach-sr** [googlemaps/google-maps-services-java#607]
Please be sure to include as much information as possible:

#### Environment details

1. This was discovered using the Geocoding API, but may apply to all
2. Mac Mojave
3. Kotlin Project, using 0.10.0 of the Google Maps Service Client

#### Steps to reproduce

  1. While trying to test geocoding I ran into several errors on using the sample code (below) - these errors seem to be related to dependencies that are required but not mentioned in the documentation: gson and okhttp3.

Adding them as dependencies to my gradle build file (code below) solved the problem. I could see an argument made that perhaps gson is not really a dependency - perhaps there are other libraries out there that can decode the results and in the initial "getting started" phase perhaps you just want to debug and inspect the results object. okhttp3 does seem required to at least get the tutorial code working. 

Maybe no one sees this issue very often because they already have these libraries as dependencies in their projects? Or I could be way offbase and am simply Using It Wrong - I am admittedly new to the Java/Kotlin world. If these are dependencies, my suggestion is to add this to the docs.

#### Code example
```java
GeoApiContext context = new GeoApiContext.Builder()
    .apiKey("AIza...")
    .build();
GeocodingResult[] results =  GeocodingApi.geocode(context,
    "1600 Amphitheatre Parkway Mountain View, CA 94043").await();
Gson gson = new GsonBuilder().setPrettyPrinting().create();
System.out.println(gson.toJson(results[0].addressComponents));
```

```
implementation 'com.squareup.okhttp3:okhttp:4.2.0'
implementation 'com.google.code.gson:gson:2.8.5'
```

**Comment by jpoehnelt** [comment]
This was an issue with 0.10.0 that should be corrected with version 0.10.1(coming soon). See https://github.com/googlemaps/google-maps-services-java/issues/599.
