### ISSUE TITLE
[Debugging features] Request serialization

### ISSUE THREAD

**Issue by denismakogon** [googlemaps/google-maps-services-java#621]
I'm trying to debug certain problems Static Maps API, constantly receiving HTTP 403.
So, I was trying to get a raw representation of the request. At first, I thought that `toString()` will actually provide raw request, but it doesn't seem to be implemented that way.

So, would be nice to have a way to serialize the request in order to see how was it formed and analyze it later via wget/curl/browser, i.e.:
```java
var req = StaticMapsApi.newRequest(context, new Size(WIDTH, HEIGHT));
System.out.println(req.toString());
```

**Comment by denismakogon** [comment]
It is still a thing, would be nice to get this tiny feature.

**Comment by jpoehnelt** [comment]
Agreed, I'm looking through all of the client libraries to refactor to better expose transport internals and simplify the layers of abstraction. Currently working through the node client library and I'll probably move to this library next.

**Comment by angelarosario** [comment]
Is there an update to this?
