### ISSUE TITLE
Open source Google maps?

### ISSUE THREAD

**Issue by paaljoachim** [googlemaps/google-maps-services-java#623]
Thanks for stopping by to let us know something could be better!

---> Thank you for the above message! I really hope you also mean it!
I have come across many web sites from various countries where once upon a time Google maps worked nicely. After the shift to a much tighter and more difficult to handle Google maps API A LOT of sites now have a none working Google maps. Showing instead a Google maps error message. 

I am adding this issue, as I am having a difficult time reaching through to an understanding ear at Google. This is really the first major issue I have with Google Maps. An error that shows that Google Maps is just not working and many will just ignore the error message because it is not that easy to fix. 

Bottom line then becomes: Does Google want to show a non working product on likely thousands of web sites? Google is not dealing with the real issue here. Going from an Open Source Google maps that was easy to use for many years to a closed Google Maps which is a lot harder to use.

It is about time Google maps is made Open Source again. Freely and easily available for everyone. Showing that Google maps actually does work.

Thanks for reading. Forgive me if this is the wrong place to add this issue. I have tried a few different places but feel that there is really no good thank you for sharing your thoughts with us feedback to the response that I give. Have a great day! Please make the best product you can! Having an easy to use Google Maps for everyone.

**Comment by jpoehnelt** [comment]
Hi @paaljoachim, 

These are known issues and a result of changes over many months to give the website owners the opportunities to add a key to their Google Maps Usage. Unfortunately, this change was necessary to limit unrestricted and abusive users that degrade the experience for others. It should be noted that many of the sites having issues will use less than the credited amount each month. However, there is no mechanism to directly reach out to the affected sites. 

For other general billing related questions, please use one of the links on this page https://developers.google.com/maps/support to contact support.

**Comment by paaljoachim** [comment]
Hey Justin

This is a tricky/difficult process and on top of that one has to also insert a credit card number which is something a lot of people just do not want to do including myself. It would have been a lot better if it had been a lot easier to go from what was earlier to the new just by following a few simple steps. Kinda like taking the hand and guiding all users through the setup of the new map procedure. As this in a sense makes one think that Google is just out to trick the person into getting the credit card. As there is some very negative stigma in giving ones credit card number to something online one is not planned on giving money to.

So two things:
1. A much clearer hand holding procedure. Explaining why and the how.
2. Inserting just parts of the credit card and getting a notice from Google if one is close to the max of what the free version holds. Meaning one feels like one does not have to just give the credit card numbers and then one day have a sudden charge one does not know where it came from. Meaning: User can hold off on inserting the full credit card number until or if the time comes that it is needed.

These things would help a lot. In the mean time all users will see a lot of sites out there that shows a Google maps does not work. Of course there are valid reasons for the change but if one mostly just think about the technical know how users or so it feels then one loses out on the many users who have just inserted a WordPress plugin that contains a map that today does not work any longer.

So as a teacher I would have added a very simple hand holding guide and a simple reasoning to the change. Not forcing people to have to insert their credit card numbers.

Going from a just insert that Google map plugin to a whole new insert the API number is a huge learning curve which is something a lot of less technical users just do not want to relate to. It is too bad that Google did not find a much simpler way of handling this change.
