### ISSUE TITLE
How do I use the GeocodingApi.Response class to get the overall response?

### ISSUE THREAD

**Issue by onclave** [googlemaps/google-maps-services-java#630]
Hello,

I have just started using this library for geocoding. The basic example given in the README helps me get the `results` in a `GeocodingResult[]` array. But I'd like to use the `GeocodingApi.Response` object to access the `status` as well as `errorMessage` of the entire JSON response.

The `GeocodingResult[]` can be obtained using:

```
GeoApiContext context = new GeoApiContext.Builder().apiKey("apikey").build();
GeocodingResult[] results = GeocodingApi.geocode(context, "address").await();
```

Is there any way I can get a `GeocodingApi.Response` object of the resultant response? I am a bit lost within the docs.

Thanks!

**Comment by arwa123** [comment]
facing the same issue. Please respond

**Comment by arriolac** [comment]
Getting the `GeocodingApi.Response` class is not possible right now with the current design. If you want to get the error, you'll have to catch the exception thrown by `await()`. So:

```java
try {
    GeocodingResult[] results = GeocodingApi.geocode(context, "address").await();
    // Execution here means a success
} catch (ApiException e) {
    // Inspect `e` to read the error message
}
```
