### ISSUE TITLE
MAX_ROUTE_LENGTH_EXCEEDED Exception is not supported

### ISSUE THREAD

**Issue by darshitpp** [googlemaps/google-maps-services-java#631]
According to Google documentation of [Directions API](https://developers.google.com/maps/documentation/javascript/directions#DirectionsStatus), 

> `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. This error occurs when more complex directions are returned. Try reducing the number of waypoints, turns, or instructions.

Unfortunately, the documentation also doesn't deterministically explain _when_ the API would return this error.

Nevertheless, there is no Exception class for the above Exception in the library.

**Comment by darshitpp** [comment]
@domesticmouse, please feel free to suggest if these changes are required. I have created a PR for the issue at https://github.com/googlemaps/google-maps-services-java/pull/632

Not sure why Github shows 4 commits because two of them have already merged.

**Comment by domesticmouse** [comment]
Hey Darshit,

I've assigned @jpoehnelt as the reviewer for your PR as I no longer work on Google Maps. Thanks for the PR, much appreciated =)

brett

**Comment by darshitpp** [comment]
Closing this issue as the fix has been merged into the master branch from #632
