### ISSUE TITLE
documentation problem

### ISSUE THREAD

**Issue by ironblaster** [googlemaps/google-maps-services-java#641]
in the readme file, the call of the shutdown () method is not specified at the end of a request.

this is a problem because after n requests java creates multiple threads not closed
and in the case of tomcat the instance goes into error

**Comment by jpoehnelt** [comment]
Mind submitting a pr?

**Comment by ironblaster** [comment]
have create new pr

**Comment by jpoehnelt** [comment]
closed by #642
