### ISSUE TITLE
NearbyPlacesRequest Api does not work with android fusedLocationProviderLocation! I want to place as markers on map the nearby places, however the LatLng says that is not compatible with android. Do I need to find user location using this library, because at the moment I am using androidx library. Also, do I need Google App Engine for that or it is not mandatory?

### ISSUE THREAD

**Issue by Biseamon** [googlemaps/google-maps-services-java#657]
I try to display all the nearby places by name around user location. For the user location, I am using android places sdk, however the sdk does not provide nearby places functionality. So, I am trying to apply google-maps-services-java for that. Could you clarify me if I am doing something wrong? I cannot understand how to use correctly this lib. 

1. NearbyPlacesRequest Api:

`@RequiresApi(api = Build.VERSION_CODES.M)
    @Override
    public void onMapReady(GoogleMap googleMap) {
        mMap = googleMap;
        fusedLocationProviderClient.getLastLocation().addOnSuccessListener(this, location -> {
            LatLng currentLoc = new LatLng(location.getLatitude(), location.getLongitude());
            if(location != null) {
                mMap.addMarker(new MarkerOptions().position(currentLoc).title("Marker in Birmingham"));
                mMap.moveCamera(CameraUpdateFactory.newLatLng(currentLoc)); // here the currentLoc is underlined with red saying that google.android.gms.mapsmodel.LatLng is not compatible with google.maps.model.LatLng
                mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(currentLoc, 15));

                GeoApiContext context = new GeoApiContext.Builder().apiKey("KEY").build();
                NearbySearchRequest nearbySearchRequest = new NearbySearchRequest(context);
                nearbySearchRequest.name("restaurants");
                nearbySearchRequest.radius(3000);
                nearbySearchRequest.location(currentLoc);

            }
         });
    }`

2. Android 6.0.1 Marshmellow
3. google-maps-services-java

Thanks!

**Comment by arriolac** [comment]
As stated under the [Intended Use of This Library](https://github.com/googlemaps/google-maps-services-java/blob/master/README.md) in our README, this library is not meant to be used in an Android app. Instead, you can compose an HTTP network call directly using the Place Search API in your Android app. You can read more about the Place Search API [here](https://developers.google.com/places/web-service/search#PlaceSearchRequests).

**Comment by Biseamon** [comment]
It says clearly that it can be used for android development by using google app engine and this library...

**Comment by rwaldura** [comment]
Biseamon: is this merely a typing issue? i.e. incompatible types? 
Note there are 2 LatLng classes: `com.google.maps.model.LatLng` vs. `com.google.android.gms.maps.model.LatLng`
You need to convert between the two, e.g. using these utility functions: 

```
private fun l2l(loc: com.google.android.gms.maps.model.LatLng): com.google.maps.model.LatLng = (
    com.google.maps.model.LatLng(loc.latitude, loc.longitude) )

private fun l2l(loc: com.google.maps.model.LatLng): com.google.android.gms.maps.model.LatLng = (
    com.google.android.gms.maps.model.LatLng(loc.lat, loc.lng) )
```

Your code becomes:

```
 mMap.moveCamera(CameraUpdateFactory.newLatLng(l2l(currentLoc))); // convert between LatLng types with l2l()
```
