### ISSUE TITLE
Using Gzip compression 

### ISSUE THREAD

**Issue by edumucelli** [googlemaps/google-maps-services-java#673]
I'd be interested on adding Gzip compression support into the calls to Google API. For instance, I have been using this library for Directions API and I have been digging into the code to discover whether some compression is in place. For the Directions use case the payload size percentiles I am seeing on my end are shown below

![payload-size-percentiles](https://user-images.githubusercontent.com/959623/78273698-7f5d4680-750f-11ea-8ed4-1b2d27ec5ae7.png)

On my side I have tried to add an OkHttp interceptor to enable compression, but I have ended up seeing that it will break due to how the string is expected to be [de-serialized from plain text](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/internal/OkHttpPendingResult.java#L294).

I am wondering if you guys would be interested on having Gzip compressed on this library. I could implement it.

**Comment by jpoehnelt** [comment]
I think it is already enabled transparently. See https://github.com/square/okhttp/issues/2132#issuecomment-169500736 and the following comment.

**Comment by Abosnd02** [comment]
35177729+Abosnd02@users.noreply.github.com

**Comment by jpoehnelt** [comment]
@edumucelli Let me know if I am incorrect in my reading of the above. Closing for now.
