### ISSUE TITLE
NoClassDefFoundError in 0.11.0

### ISSUE THREAD

**Issue by edpi** [googlemaps/google-maps-services-java#674]
Hi,

I have done a very simple MatrixDistanceAPI example to test how it works, but I don't know why I get the following error:

Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/TypeCastException
	at okhttp3.ResponseBody.create(ResponseBody.java:214)
	at okhttp3.internal.Util.<clinit>(Util.java:69)
	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:124)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:449)
	at com.google.maps.OkHttpRequestHandler$Builder.<init>(OkHttpRequestHandler.java:112)
	at com.google.maps.GeoApiContext$Builder.<init>(GeoApiContext.java:356)
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

This is the code:

public static void main(String[] args) {

        try {
            GeoApiContext context = new GeoApiContext.Builder().apiKey("AIza......").build();

            String[] origins
                    = new String[]{
                        "Perth, Australia", "Sydney, Australia", "Melbourne, Australia",
                        "Adelaide, Australia", "Brisbane, Australia", "Darwin, Australia",
                        "Hobart, Australia", "Canberra, Australia"
                    };
            String[] destinations
                    = new String[]{
                        "Uluru, Australia",
                        "Kakadu, Australia",
                        "Blue Mountains, Australia",
                        "Bungle Bungles, Australia",
                        "The Pinnacles, Australia"
                    };
            DistanceMatrix matrix
                    = DistanceMatrixApi.getDistanceMatrix(context, origins, destinations).await();
            System.out.println(matrix.toString());
        } catch (ApiException | IOException | InterruptedException ex) {
            System.out.println("Exception ->" + ex.getMessage());
        }
    }

I'm not used to gradle nor maven, so I have included libraries directly as .jar in my java project. I have included the next ones: google-maps-services-0.11.0.jar, gson-2.8.5.jar, okhttp-3.14.4.jar, opencensus-api-0.25.0.jar, okio-2.5.0.jar & slf4j-api-1.7.26.jar.

Am I missing some other library?

Same request is done directly via http request to Google Maps with same API Key and it gets a valid result (just to be sure it is not a problem related to API Key).

Any help is more than welcome.

Thanks

**Comment by arriolac** [comment]
@edpi looks like you have a missing dependency that's required by the `okhttp` library. Based on the stacktrace you shared, it's missing `kotlin-stdlib`. 

I do recommend using gradle/maven to pull in this library so that the dependency tree can be initialized for you rather than pulling in individual .jar files.

Closing this since it's not related to this library.
