### ISSUE TITLE
Google Directions discrepancy on ZERO_RESULTS

### ISSUE THREAD

**Issue by edumucelli** [googlemaps/google-maps-services-java#675]
The ZERO_RESULTS logic differ when using this library and the HTTP API for Google Directions. The result will be that the `ZeroResultsException` is never thrown and we have to recreate it. For instance, make this call that goes from the middle of the ocean to the middle of the ocean returns `ZERO_RESULTS` when `curl`ing the API:

`https://maps.googleapis.com/maps/api/directions/json?origin=9.198727,-40.167322&destination=49.066051,-18.812792&key=API_KEY`

```
{
   "geocoded_waypoints" : [ {}, {} ],
   "routes" : [],
   "status" : "ZERO_RESULTS"
}
```

However, using the library it will return an object like the following:

```
{
   "geocoded_waypoints" : [ {}, {} ],
   "routes" : [],
   "status" : "OK"
}
```

This is because the following part of the code is buggy:

1. Once the `resp` is received [here](https://github.com/googlemaps/google-maps-services-java/blob/5837e9e20c7f4b1029af8fbab67341d9d42afee4/src/main/java/com/google/maps/internal/OkHttpPendingResult.java#L294) it has the value the API has above with the `ZERO_RESULTS` status as it should.
2. [Here](https://github.com/googlemaps/google-maps-services-java/blob/5837e9e20c7f4b1029af8fbab67341d9d42afee4/src/main/java/com/google/maps/internal/OkHttpPendingResult.java#L309) will evaluate to true because [this](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/DirectionsApi.java#L74) condition will be true for either `OK` or `ZERO_RESULTS`.
3. From here on it wont use the `ApiException` mapper because it will never evaluate the [else](https://github.com/googlemaps/google-maps-services-java/blob/5837e9e20c7f4b1029af8fbab67341d9d42afee4/src/main/java/com/google/maps/internal/OkHttpPendingResult.java#L313) into `resp.getError()` that would have correctly mapped `ZERO_RESULTS` into a [ZeroResultsException](https://github.com/googlemaps/google-maps-services-java/blob/5837e9e20c7f4b1029af8fbab67341d9d42afee4/src/main/java/com/google/maps/errors/ApiException.java#L62).

This bug requires that on the client side we check whether the `routes.isEmpty()` in order to rewrite the `status` as we can't trust it as the routes might be empty but still `"status": "OK"`.

**Comment by sumitskj** [comment]
Hi @arriolac, can I work on this bug.

**Comment by jpoehnelt** [comment]
@sumitskj Please do! 👍

**Comment by abdul4samad** [comment]
Hi @jpoehnelt, it's been a long and there is no response from @sumitskj. I guess this is an easy fix and for this I just need to change the return condition of the line [this](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/DirectionsApi.java#L74).
So may work on it?

**Comment by jpoehnelt** [comment]
Absolutely.

**Comment by abdul4samad** [comment]
Thanks! @jpoehnelt ! #709 is assigned to @arriolac
