### ISSUE TITLE
Support Streetview Metadata API

### ISSUE THREAD

**Issue by jdwilkin** [googlemaps/google-maps-services-java#681]
Is there any appetite to add the Streetview Metadata API?
https://developers.google.com/maps/documentation/streetview/metadata

thanks

**Comment by arriolac** [comment]
This is not an API we were looking to add afaik. @jpoehnelt can you confirm?

However, if this addition would be good for your use case, feel free to send us a pull request and we'd be happy to review and integrate it.

**Comment by ryanshepps** [comment]
I have a use case in my application for this:

1. Verify if Street View image is available using the StreetView Metadata API.
2. If yes, generate a Street View image.
3. If no, generate a Static Map image.

Please let me know if this is a valid use case. I'd be happy to open a PR.
