### ISSUE TITLE
Allow using existing session token(String) in place autocomplete

### ISSUE THREAD

**Issue by vojtapol** [googlemaps/google-maps-services-java#689]
In our case the session token is not generated on the service that does the Google Places API call. Instead an existing token is passed from the client to facilitate correct billing. The token is not necessarily a UUID and there is no reason why only UUID should be allowed as implemented here #478. The API accepts any string as a token.

My request is to add another constructor to `SessionToken`:
```java
public SessionToken(String token) {
  this.token = token;
}
```

**Comment by vojtapol** [comment]
Workaround:

```java
String token = "some token coming from the client";
UUID uuid = UUID.nameUUIDFromBytes(token.getBytes());
SessionToken sessionToken = new SessionToken(uuid); 
```

This could be also used in the constructor so that the field in `SessionToken` can remain of type `UUID`.

**Comment by jpoehnelt** [comment]
Mind submitting a pr?

**Comment by vojtapol** [comment]
Will do.

**Comment by vojtapol** [comment]
It is still valid.
