### ISSUE TITLE
Expand Mapping Locations on Trails and Rivers

### ISSUE THREAD

**Issue by mpara0** [googlemaps/google-maps-services-java#693]
I like how Google Maps does a phenomenal job with connecting users from Point A to Point B by providing users a variety of routes and information on location and time of arrival for efficiency!

I constantly use Google Maps to navigate my trips on the road and wanted to know if it is possible to expand the platform for providing navigation for outdoor activities, namely hiking and kayaking. The reason why I am proposing this feature is that I originally tried to set up locations via Google Maps when I am hiking at a forest or a way to track the location of where I am kayaking to let my friends know where I am to track it and how long it will take to go to the dock port to be picked up at - however, I noticed that Google Maps doesn't have a strong route suggestions for paths and was wondering if a feature like this could be developed? I know some apps like Nike Run allows you to track your path but to have to map and navigate the route would be ideal.

**Comment by jpoehnelt** [comment]
Thanks for the feedback! I am an avid hiker/biker/trail runner myself and this is of personal interest to me. There are efforts to always improve the maps and routing experiences. As a consumer of this platform, you can encourage organizations to submit these routes and layers at https://support.google.com/mapcontentpartners/answer/9359574?hl=en. If you have additional feedback on this, I suggest submitting that from within the Google Maps application(google.com/maps or mobile app).
