### ISSUE TITLE
GeoApiContext to implement java.util.Closeable

### ISSUE THREAD

**Issue by ZeroOne3010** [googlemaps/google-maps-services-java#701]
**Is your feature request related to a problem? Please describe.**
The API doesn't make it obvious that a `shutdown()` method of `GeoApiContext` objects should be called, nor that any subsequent calls after shutdown will fail.

 **Describe the solution you'd like**
`GeoApiContext` should implement the [`java.io.Closeable`](https://docs.oracle.com/javase/8/docs/api/index.html?java/io/Closeable.html) interface so that `close()` would call the `shutdown()` method. While seemingly trivial, this would have a few benefits:
1. Code would become cleaner when you could use the [try-with-resources statement](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html).
2. Static code analysis tools can pick it up that there exists a Closeable object that is not closed.
3. `close()` is just the standard way of doing this in Java, no need to guess or remember whether it's `shutdown()`, `shutDown()`, `terminate()`, or something else, so there's less mental burden for the programmer.

 **Describe alternatives you've considered**
The alternative is to not do anything, which would make us miss the benefits described above.

Another alternative is to convert the API so that the need for the `shutdown()` method would be removed completely, but as it is there, I'm sure someone has good reasons why the API was designed this way in the first place.

**Comment by vaibhavdesai16** [comment]
Hi, @ZeroOne3010 I would like to fix this issue. Should implement Closeable interface and call shutdown() method from close() ?

**Comment by ZeroOne3010** [comment]
> Hi, @ZeroOne3010 I would like to fix this issue. Should implement Closeable interface and call shutdown() method from close() ?

Hey, please feel free to go ahead! That's how I'd do it too. 😎

**Comment by yihtserns** [comment]
I'm here because PMD complained that my singleton `GeoApiContext` is not closed after use, because of this change.

@ZeroOne3010 can you share how you're using `GeoApiContext`?  Are you creating a new instance for every request to Google Maps API?

**Comment by ZeroOne3010** [comment]
@yihtserns Sorry, I'm not in that project anymore where this library was used, and cannot remember the context anymore. 🙁
