### ISSUE TITLE
Directions: Missing VehicleType LONG_DISTANCE_TRAIN

### ISSUE THREAD

**Issue by LumnitzF** [googlemaps/google-maps-services-java#718]
The vehicle type "LONG_DISTANCE_TRAIN" (as described [here](https://developers.google.com/maps/documentation/directions/overview#VehicleType)) is missing from the [VehicleType](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/model/VehicleType.java) enum.

This will result in the `type` attribute beeing `null` inside the [Vehicle](https://github.com/googlemaps/google-maps-services-java/blob/master/src/main/java/com/google/maps/model/Vehicle.java).

I would further suggest to add a `SafeEnumAdapter` for the `VehicleType` in the [OkHttpPendingResult](https://github.com/googlemaps/google-maps-services-java/blob/a78722087bff37d36b403b853ce28517c32037ac/src/main/java/com/google/maps/internal/OkHttpPendingResult.java#L266) and the [GaePendingResult](https://github.com/googlemaps/google-maps-services-java/blob/a78722087bff37d36b403b853ce28517c32037ac/src/main/java/com/google/maps/internal/GaePendingResult.java#L188).

**Comment by arriolac** [comment]
Thanks for reporting. Feel free to send us a PR for this.
