### ISSUE TITLE
No variant of PlacesApi#placeAutocomplete() takes no session token

### ISSUE THREAD

**Issue by DevCeN** [googlemaps/google-maps-services-java#728]
PlacesApi#placeAutocomplete(GeoApiContext, String, PlaceAutocompleteRequest.SessionToken) hinted user to use a session token (of course user can pass in a null value if they really don't want it), this causes people to add in a session token unnecessarily even when they are not trying to reuse the tokens. This is very bad because sending a placeAutocomplete request with token is charged a few times more than without a token.

PlacesApi#placeDetails() on the other hand offers variants to include a session token or not, which is clear to user that a session token is optional.

Consider adding a variant PlacesApi#placeAutocomplete(GeoApiContext, String) that does not need a session token.

**Comment by apjanke** [comment]
This sounds like a good idea to me. Even if it weren't for the pricing aspect of it, expecting callers to frequently pass `null` for a parameter isn't very modern-Java-y.

Looking at the [Google Maps Pricing Table](https://cloud.google.com/maps-platform/pricing/sheet/) (scroll down to "Places" and compare the "per request" and "per session" pricing), it looks like it's $3 per 100K requests, and $17 per 100K sessions. If I'm reading that right, it means if you're sending Places Autocomplete requests through short-lived sessions that do not issue several requests per session, you've just multiplied your cost by up to 5x. Is that what you're referring to?

**Comment by DevCeN** [comment]
@apjanke spot on! $17 vs $2.83 is like 6 times more if someone is just calling the API one off with a session token unnecessarily or worst, to generate a new session token in each call. Thanks for supporting the idea!

**Comment by arriolac** [comment]
Agreed that `PlacesApi` should support a variant that does not take in a `SessionToken` as a more developer-friendly API to support use cases where autocomplete requests are kept at a minimum.

Requested API:
```
PlaceAutocompleteRequest request = placesApi.placeAutocomplete(context, queryText);
```

Would you like to send us a PR for this feature?

**Comment by DevCeN** [comment]
Thanks @arriolac, I will find my time as I haven't done it before and obviously haven't signed any CLA. Meanwhile if anyone wants to do a PR feel free to do so.

**Comment by vaibhavdesai16** [comment]
Hi @arriolac I am interested to work on the issue.

**Comment by arriolac** [comment]
@vaibhavdesai16 please feel free to send a PR. Thanks!
