### ISSUE TITLE
Missing language parameter 

### ISSUE THREAD

**Issue by larsf96** [googlemaps/google-maps-services-java#729]
**Is your feature request related to a problem? Please describe.**
The language parameter that can be set e.x. for the Places API is not available with this Library. In some older examples I've seen a language parameter for GeoApiContext, but this property isn't available any more?!

 **Describe the solution you'd like**
A language parameter should either be re-added to the GeoApiContext or to the particular calls on the different API's

 **Additional context**
It's mostly impossible to localize an application when the language parameter is missing within this library

**Comment by arriolac** [comment]
You should be able to set the language on a per-request basis. This is supported in the abstract base class [PendingResultBase](https://github.com/googlemaps/google-maps-services-java/blob/main/src/main/java/com/google/maps/PendingResultBase.java#L145) which the request objects inherit from. What version of the library are you using?
