### ISSUE TITLE
Places: NearbySearchRequest callback not being called

### ISSUE THREAD

**Issue by william-vw** [googlemaps/google-maps-services-java#733]
---
#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
Places API

2. OS type and version
Ubuntu 20.04

3. Library version and other environment information
google-maps-services 0.18.1
OpenJdk 11.0.11

#### Steps to reproduce

  1. See code snippet below. The callback is simply not being called. Sorry if I'm missing something obvious.

#### Code example

```java
public class NearbyPlacesTest implements Callback<PlacesSearchResponse> {

	public static void main(String[] args) {
		new NearbyPlacesTest().test();
	}

	public void test() {
		double lat = 38.899509;
		double lon = -77.041792;

		GeoApiContext context = new GeoApiContext.Builder().apiKey("...").build();
		LatLng myLocation = new LatLng(lat, lon);

		try {
			NearbySearchRequest request = PlacesApi.nearbySearchQuery(context, myLocation).radius(1000);
			
			// does not work
			request.setCallback(this);
			
			// this does work
//			onResult(request.await());
//			context.shutdown();

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	@Override
	public void onResult(PlacesSearchResponse response) {
		for (PlacesSearchResult result : response.results)
			System.out.println(result);
	}

	@Override
	public void onFailure(Throwable e) {
		e.printStackTrace();
	}
}
```

#### Stack trace
No stack trace - the callback is simply not being called.

**Comment by arriolac** [comment]
You will need to call `.await()` or `.awaitIgnoreError()` on the request to trigger the request. See https://github.com/googlemaps/google-maps-services-java/blob/1ff58c604e43f544ffbddd35abf1325305715f7a/src/main/java/com/google/maps/PendingResultBase.java#L56...L64

**Comment by william-vw** [comment]
@arriolac that will perform the request synchronously - the [API doc](http://googlemaps.github.io/google-maps-services-java/v0.1.12/javadoc/com/google/maps/NearbySearchRequest.html#setCallback-com.google.maps.PendingResult.Callback-) states the following about `setCallback`:

> Performs the request asynchronously, calling onResult or onFailure after the request has been completed.

So is there no asynchronous way to perform the request (no problem if there's not - in that case maybe the API doc should be updated).

**Comment by william-vw** [comment]
See https://github.com/googlemaps/google-maps-services-java/blob/1ff58c604e43f544ffbddd35abf1325305715f7a/src/main/java/com/google/maps/PendingResultBase.java#L51

The `makeRequest` method is also called by `setCallback` ..

**Comment by arriolac** [comment]
Apologies, I misunderstood your question. `setCallback` should give you the result asynchronously. The reason you are not seeing a result is likely due to the request object getting deallocated before the result comes back. You'll need to keep a reference to the `NearbyPlacesTest ` object or impose a thread sleep after invoking `test()` (there are a several ways to handle this).

**Comment by william-vw** [comment]
Thanks, will look into it!
