### ISSUE TITLE
Add local_icon for vehicle in transit details (not documented)

### ISSUE THREAD

**Issue by NicolasPoirier** [googlemaps/google-maps-services-java#75]
A local_icon field is available for vehicle in transit details. It could be very useful but it's not documented ([doc](https://developers.google.com/maps/documentation/directions/#TransitDetails)).

For instance in Paris we have:
- icon: ![icon](http://maps.gstatic.com/mapfiles/transit/iw/6/subway.png)
- local_icon: ![local_icon](http://maps.gstatic.com/mapfiles/transit/iw/6/fr-paris-rail.png)

What do you think about it? Can we add this field?

**Comment by broady** [comment]
I don't think we should, unless it's added to the official documentation. I just filed an internal issue to see if we can do that.

**Comment by domesticmouse** [comment]
@NicolasPoirier could you give me an example request that generates this data in the results?

**Comment by NicolasPoirier** [comment]
@domesticmouse, you can find this in Paris or in London. For instance:

- [Direction in Paris](https://maps.googleapis.com/maps/api/directions/json?origin=paris%20%20metro%20bibliotheque%20francois%20mitterrand&destination=paris%20metro%20pyramides&mode=transit)
- [Direction in London](https://maps.googleapis.com/maps/api/directions/json?origin=london%20city&destination=london%20hyde%20park&mode=transit)

**Comment by domesticmouse** [comment]
This should now work. Please re-open if it isn't. Thanks!
