### ISSUE TITLE
Add support for the language param

### ISSUE THREAD

**Issue by huanlenguyen** [googlemaps/google-maps-services-java#767]
Language param is missing from PlaceAutocompleteRequest.  Are there plans to add it?

**Comment by arriolac** [comment]
`PlaceAutocompleteRequest` extends from `PendingResultBase` which supports setting a [language](https://github.com/googlemaps/google-maps-services-java/blob/main/src/main/java/com/google/maps/PendingResultBase.java#L176) param.

**Comment by huanlenguyen** [comment]
Thanks, missed that.
