### ISSUE TITLE
Vulnerability in com.google.code.gson:gson

### ISSUE THREAD

**Issue by egrotowska** [googlemaps/google-maps-services-java#769]
Hello,

There is a vulnerability being reported affecting com.google.code.gson:gson@2.8.7, which is a dependency of google-maps-services@1.0.0: https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLECODEGSON-1730327

Could the gson library please be updated to @2.8.9?

**Comment by arriolac** [comment]
Thanks for flagging. Looks like it's already updated to the 2.8.9 in https://github.com/googlemaps/google-maps-services-java/blob/main/build.gradle#L56 but will need to push out a new version. Will do that shortly

**Comment by arriolac** [comment]
Please use 1.0.1 moving forward. Thanks!
