### ISSUE TITLE
Channel to follow Maps For Work usage

### ISSUE THREAD

**Issue by BenjaminMercier19** [googlemaps/google-maps-services-java#77]
Hi everybody,

It's quite my beggining in Github so excuse me in advance if I missuse it right now.

Actually I wonder if there is any way to set a Channel on the GeoApiContext. It's really useful for me to follow the usage and quotas of my Google Maps For Work end users.

Thanks in advance for any answers !

**Comment by broady** [comment]
Does it make sense on the `GeoApiContext` or per-request?

**Comment by BenjaminMercier19** [comment]
In my opinion, on the GeoApiContext is enough as I use a channel per application to follow usage by app. But, indeed, some people could follow usage per request... I don't know how to answer this one.

To ensure the majority needs, you should add it on per request perhaps.

**Comment by markmcd** [comment]
My instinct on this one is that channel is part of the request context, and therefore multiple channels within one application could/should use multiple contexts.

Having it on the context will mean that any automatic request throttling will need to be overridden by the developer, which is an annoyance. However it does save them from having to add channel to *every* different request. But then again that might a useful case...

**Comment by miguev** [comment]
Just in case anyone is thinking in the possibility of giving each request a channel:
"The channel value must be a static value assigned per application instance, and must not be generated dynamically. You may not use channel values to track individual users, for example."
https://developers.google.com/maps/documentation/business/webservices/quota#channel_reports
