### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by clicktravel-robin** [googlemaps/google-maps-services-java#79]
Hi

We have been using this package for a few weeks without any issues but its suddenly not working with a message 403 forbidden. Normally i would put this down to usage limits etc however if i take the URL that appears in my log with the client id and signature and post it in my browser the service responds as normal with a 200 and the results

Can anyone point me in the right direction as i really don't want to have pull this package back out of my code base, but it only seems to have an issue when i use this package

Thanks

**Comment by clicktravel-robin** [comment]
OK it looks like this might be an issue with the android integration...

----
Disruption in Google Maps API and Android Geocoding services
The Google Maps Geocoding API, Directions API, Distance Matrix API, as well as the related services in the JavaScript API. The Android geocoding service has also been affected. The issue was first detected around March 3, 1:35 AM US Pacific time, and resolved for the Maps APIs at around 3:25 AM US Pacific time. However, the Android geocoding service is still affected at the time of writing.
-----


Would it be fair to assume that this is why this tool is no longer working?

**Comment by pgsandstrom** [comment]
I as well have this problem. And it also works if I simply query from the browser instead. Could you please link to the source of that status message about API?

**Comment by clicktravel-robin** [comment]
Its from the gmaps support portal 

https://google.secure.force.com/home/home.jsp

a support engineer also responded to me 

"I can confirm that a 403 forbidden response is what is currently being returned by the native Android Geocoder. This would suggest that the results you are having issue with are actually coming from this service. "

**Comment by clicktravel-robin** [comment]
looks like this is now resolved 

thanks

**Comment by broady** [comment]
Yes, this was an outage on the server-side. Thanks for the reports, folks.
