### ISSUE TITLE
Get directions of a list of Latitude-Longitude objects.

### ISSUE THREAD

**Issue by russellhoff** [googlemaps/google-maps-services-java#82]
Is it possible to get directions of, say, List<LatLng>? I know there is a method getDirections(GeoApiContext context, java.lang.String origin, java.lang.String destination) in DirectionsApi, but it would be nice if there would be a method in DirectionsApi getDirections(GeoApiContext context, List<LatLng> path), but it would be necessary to create another getDirections(GeoApiContext context, LatLng origin, LatLng destination);

Would it be possible?

Thanks

**Comment by broady** [comment]
Not exactly sure what you mean by a list of lat/longs. What do you expect to get out of that?

**Comment by broady** [comment]
Do you mean stopovers?

**Comment by broady** [comment]
If so, use `waypoints` option for that:

http://googlemaps.github.io/google-maps-services-java/v0.1.3/javadoc/com/google/maps/DirectionsApiRequest.html#waypoints(java.lang.String...)

**Comment by russellhoff** [comment]
@broady Thanks you and I'm sorry for the inconvenience.

**Comment by broady** [comment]
np!
