### ISSUE TITLE
Latest release is not available in the Maven repository

### ISSUE THREAD

**Issue by irineuruiz** [googlemaps/google-maps-services-java#865]
Is there any reason that version 2.1.1 is not yet available in the Maven repository?

https://search.maven.org/search?q=a:google-maps-services

**Comment by wangela** [comment]
This has been released as [v2.1.2](https://github.com/googlemaps/google-maps-services-java/releases/tag/v2.1.2) ([maven](https://search.maven.org/artifact/com.google.maps/google-maps-services)).
