### ISSUE TITLE
Making requests without an api key or enterprise credentials

### ISSUE THREAD

**Issue by martinez8859** [googlemaps/google-maps-services-java#91]
Hi,

I am new to using maps so I'm not sure if I have this right but I am writing an android app and as far as I can tell it would be better for me to not use an API key for my requests and instead rely on the IP address usage limits.
It looks like this library does not allow this.
Just wondering if this could be added as an option.

Cheers

**Comment by markmcd** [comment]
Unfortunately we won't implement this feature. While some of the APIs will technically function without an API key, they may not work that way forever and you will generally get a better experience by providing an API key.

The main benefits are that you'll often get a higher number of queries per second (and they're in line with what this library is configured to use by default) and Google will be able to contact you if it's ever necessary (or conversely, if you aren't providing an API key then your requests are being made anonymously and you could potentially have your app blocked without prior warning).

I would also recommend against relying on the IP address limits, as service providers and mobile carriers often use proxies/NATs that result in many users sharing a single IP address. Your app will end up burning through quota much faster in these cases.
