### ISSUE TITLE
Allow Non-Stopover Waypoints

### ISSUE THREAD

**Issue by pcoughran** [googlemaps/google-maps-services-java#93]
From https://developers.google.com/maps/documentation/directions/ -->

You can use waypoints to influence your route without adding a stopover by prefixing the waypoint with via:. Waypoints prefixed with via: will not add an additional leg to the route.

Sample Request:

```
https://maps.googleapis.com/maps/api/directions/json?origin=Boston,MA&destination=Concord,MA&waypoints=Charlestown,MA|via:Lexington,MA&key=API_KEY
```

**Comment by markmcd** [comment]
Thanks for the FR. I'm not going to be able to get to this in the next couple of weeks but if anyone else wants to send a pull request through I'd be happy to take a look at it.

**Comment by domesticmouse** [comment]
@pcoughran could you propose an API interface that would make sense for this use case? I have done a bit thinking of how best to expose this in the API, but would love your thoughts. Thank you!

**Comment by gardster** [comment]
[Javascript AP](https://developers.google.com/maps/documentation/javascript/directions?hl=ru#Waypoints)I  has ```stopover``` property to set up a waypoint type. Maybe implement this feature with the same way?

**Comment by raulastu** [comment]
how do I set up stopover=false in the sample request? I would like duration_in_traffic to be returned in every leg, and via: prefix does not add a leg entry.

**Comment by apjanke** [comment]
How about this: We currently have String and LatLng waypoint variants in DirectionsApiRequest.

```
public DirectionsApiRequest waypoints(LatLng... waypoints)
public DirectionsApiRequest waypoints(String... waypoints)
```

We could add a Waypoint class, and a `public DirectionsApiRequest waypoints(Waypoint... waypoints)` method. The Waypoint class could have a `boolean isStopover` flag that defaults to false, and constructors:

```
Waypoint(String str)
Waypoint(String str, boolean isStopover)
Waypoint(LatLng point)
Waypoint(LatLng point, boolean isStopover)
```

The DirectionsApiRequest's internal `waypoints` field could either be converted to `Waypoint[]`, or it could remain `String[]`, and the Waypoint objects converted to String in the `waypoints(Waypoint...)` method. (I like the former.)

**Comment by domesticmouse** [comment]
I like your proposal @apjanke. Feel free to put together a PR for your preferred approach if you have time, otherwise I'll loop back and implement when I get a spare moment. Thanks!

**Comment by apjanke** [comment]
Here's a PR: #468. I made Waypoint a nested class in DirectionsApiRequest, since that seems consistent with the existing design.
