### ISSUE TITLE
Add "subway_station" to AddressComponentType enum

### ISSUE THREAD

**Issue by etki** [googlemaps/google-maps-services-java#94]
Hi, i'm getting quite usual warning message:

> WARNING: Unknown type for enum com.google.maps.model.AddressComponentType: 'subway_station'

I guess this may be fixed by simply listing that value in appropariate enum (or enums, i think AddressType should be patched as well).
Thank you!

**Comment by domesticmouse** [comment]
Can you tell us the request that caused this error, so I can confirm the proposed fix is correct?

**Comment by etki** [comment]
@domesticmouse Hi.
I'm afraid i can't reproduce it - as i can judge from what i see from gmaps geocoder http output now, there are no subway stations anymore; i guess they were just removed. I was, however, retrieving administrative area hierarchy for random points in Saint-Petersburg, Russia.

**Comment by domesticmouse** [comment]
@etki thanks!

**Comment by etki** [comment]
@domesticmouse got it:

    https://maps.googleapis.com/maps/api/geocode/json?latlng=59.891551,30.318196&key=%API_KEY%

returning payload will include *Moskovskie Vorota* / `ChIJR4GZsG4wlkYR5FquAa-fXck` entry which is subway station
