### ISSUE TITLE
java.lang.IllegalStateException: Expected a name but was STRING at line 17 column 23 path $.routes[0].fare.text

### ISSUE THREAD

**Issue by harrychangdev** [googlemaps/google-maps-services-java#95]
I use DirectionsApi, but some place at transit mode will have Exception

for example

DirectionsRoute[] routes = DirectionsApi.newRequest(context)
                    .mode(TravelMode.TRANSIT)
                    .origin("Taipei 101")
                    .destination("Tainan")
                    .await();

and it will throw an error

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a name but was STRING at line 17 column 23 path $.routes[0].fare.text

some place's direction is okay but some will go wrong

I don't know why

**Comment by domesticmouse** [comment]
Is this still an issue for you? I have tried the above code and it works as intended.

**Comment by domesticmouse** [comment]
Given the lack of response I'm taking this as fixed. Please comment to re-open if not.
