### ISSUE TITLE
Are these API's still supported?

### ISSUE THREAD

**Issue by Caperezp** [googlemaps/google-maps-services-java#96]
I got some news from some places that some API's from google maps will not longer be supported and maybe they will be replaced with "mymaps" API's. So I will like to know if these API's are still working fine.

**Comment by markmcd** [comment]
I'm not entirely sure what APIs you might be talking about, but I believe the only deprecation relating to MyMaps is the Google Maps Engine API, which is not in this library.

Each of the APIs covered by this library is still active and supported.
