### ISSUE TITLE
localhost:8158/Timeline Edits.GeoJSON.json.html

### ISSUE THREAD

**Issue by R4113R** [googlemaps/google-maps-services-java#987]
http://localhost:8158/Timeline%20Edits.GeoJSON.json.html

**Comment by Ly1207** [comment]
> http://localhost:8158/Timeline%20Edits.GeoJSON.json.html

**Comment by Ly1207** [comment]
[MessageFabric.cs.txt](https://github.com/user-attachments/files/15596644/MessageFabric.cs.txt)
[MessageFabric.cs.txt](https://github.com/user-attachments/files/15596645/MessageFabric.cs.txt)

**Comment by Ly1207** [comment]
https://github.com/googlemaps/google-maps-services-java/issues/987#issue-2297707236
