### ISSUE TITLE
On Quota Over Limit callbacks not called

### ISSUE THREAD

**Issue by juliocotta** [googlemaps/google-maps-services-java#99]
If the web services return OverQueryLimitException
these lines in the OKHttpPenedingResult.java 
ApiException e = resp.getError();
                if(e instanceof OverQueryLimitException && this.cumulativeSleepTime < this.errorTimeOut) {
                    return request.retry();
                } else {
                    throw e;
                }
Will make the call retry() and the onFailure or onResult are not being called.

**Comment by domesticmouse** [comment]
Your `onFailure` callback should be called once `cumulativeSleepTime` exceeds `errorTimeOut`. You can configure the `errorTimeOut` here by calling `setRetryTimeout` on your `GeoApiContext` singleton.

**Comment by domesticmouse** [comment]
Given the lack of reply, I'm taking this as fixed. Please comment to re-open.
